### ISSUE TITLE
Add more documentation on CORS

### ISSUE THREAD

**Issue by bjesuiter** [stablekernel/aqueduct#100]
Hello Joe @joeconwaystk  :) 

Here's Benjamin, we met at DartDev Summit, if you remember ;) 

Now, after the summit, I'm trying to implement a little server with aqueduct. 
But I'm not able to figure out how to do that CORS support. 

There is some documentation here: 
http://stablekernel.github.io/aqueduct/http/request_controller.html

I managed to come up with that: 

```
EmailController() {
    if (policy.allowedOrigins == null) policy.allowedOrigins = [];

    policy.allowedOrigins
      ..add("http://fewo-birkennest.de/*");
}
```

And that: 

```
@httpPost
Future<Response> sendEmail(@HTTPHeader("Origin") String origin) async {
}
```

If I try to make a post request with [Postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop) to that url and debug the EmailController, the defined origin variable is not shown in intelli j watcher window. 

Also, the request is allowed instead of blocked. Normally it should be blocked in this config, because localhost is not allowed. 

But even if I fake the origin to something different with Postman , e.g. "http://chip.de", the request arrives at the sendEmail method.

Can you help me with this? :)

**Comment by joeconwaystk** [comment]
Docs to come soon. In the meantime, it's the * in the allowed origins causing this. I need to go recheck the spec to see if this is correct or not, but if any allowed origin *contains* an asterisk, it is the "match any" origin. Remove the asterisk and you should be good.

**Comment by bjesuiter** [comment]
Thanks for your help Joe :) 

Unfortunately, this didn't help. :(
Thus, I did some more testing on this. 

If i remove this null check `if (policy.allowedOrigins == null)` to delete the `*`inside allowed origins and then adding in my own allowedOrigins, my `sendEmail`method is called regardless of the request having an invalid origin value. 
I would expect an not allowed error to be thrown by aqeduct and sendEmail not to be called in this case. Is that right? 

Secondly there seems to be an issue with header extraction with `@HTTPHeader`. Or me doing something wrong
First i've added the following line as the first line in `sendEmail()`:
    
    @httpPost
    Future<Response> sendEmail(@HTTPHeader("Origin") String origin) async {
        String originInternal = request.innerRequest.headers.value("origin");
    }

When I set a breakpoint on this first line, the vm is not able to determine the value of òrigin`. 
It seems simply to be non-existant. When watching the origin variable in the Variables panel of intellij idea, I get: `origin = Collecting data...`

But the value in originInternal shows the correct origin header content as sent in the requests. 
Do you have an idea why that happens? 

Maybe it's useful for you to know that I used the aqueduct cli to create the project. But this should not matter, as far as my understanding goes?

**Comment by joeconwaystk** [comment]
For the first one, I just read your sample code. The line `if (policy.allowedOrigins == null) policy.allowedOrigins = [];` will not execute. policy.allowedOrigins is never null, it defaults to ["*"]. Therefore, your allowed origins are ["*", "http://fewo-birkennest.de/"]. Just set policy.allowedOrigins = ["http://fewo-birkennest.de/"]; If this doesn't resolve, let me know, otherwise will close the issue.

Also, I just reread the code in Aqueduct - the * in the path is not checked in the way I described. Read a .contains wrong.

Per the second issue, that sounds like an IntelliJ debugger/Dart debugger issue. If you print the value of origin from the console or load up observatory I'd imagine you'd see the real value.

**Comment by bjesuiter** [comment]
No, I'm sorry, there is a missunderstanding.  🙈 

I wrote: 

> If i remove this null check if (policy.allowedOrigins == null)  to **delete** the *inside allowed origins

So I changed this line
`if (policy.allowedOrigins == null) policy.allowedOrigins = [];`
to this only: 
`policy.allowedOrigins = [];`

You are right, the content of my allowedOrigins list is now: `["http://fewo-birkennest.de/"];`
But nevertheless my sendEmail function is called, even if origin does not match. :/

Okay, i'll test that with observatory :)

**Comment by bjesuiter** [comment]
Now I have a test result with observatory. 
I attached a screenshot, because I never had this case in my own code, that a local variable does not show up. 😮 

<img width="1440" alt="bildschirmfoto 2016-11-01 um 08 48 56" src="https://cloud.githubusercontent.com/assets/2365676/19882916/6005b1a4-a011-11e6-9943-43d79d7581d2.png">

I tried to get the content of the origin variable with writing origin to the command line, but maybe i missed something there. But anyway, the local variable `origin` does not show up in the side panel, which should be the case, right?

**Comment by joeconwaystk** [comment]
@bjesuiter This issue should be resolved in 1.0.3.. will leave open for a bit to get your feedback.

**Comment by bjesuiter** [comment]
@joeconwaystk  
Thanks for your reply! 

I found the reason for the @HTTPHeader not working. If the origin variable will not be use later somewhere, it will not be allocated by the vm. It's simply removed. 
When you run the following code with a breakpoint somewhere, the @HTTPHeader annotation works as expected. But when you remove the originInternal2 variable with the assignment, the annotation is not working anymore. (this is no problem anymore, only observation ;) ): 

    @httpPost
    Future<Response> sendEmail(@HTTPHeader("origin") String origin) async {
        String originInternal = request.innerRequest.headers.value("origin");
        String originInternal2 = origin;
    }

Now to the part with CORS. 

My EmailController constructor looks like this: 

    EmailController() {
        policy.allowedOrigins = [];
        policy.allowedOrigins
          ..add("http://fliesenleger-lieberwirth.de");
    }

So it should block my request with a 403, when my origin is different than http://fliesenleger-lieberwirth.de, right? 

But when i try to make a post request with postman, my sendEmail method gets still executed, ignoring that the origin of postman (being `chrome-extension://aicmkgpgakddgnaphhhpliifpcfhicfo`) is not on the allowedOrigins list. 

Do i have to evaluate these policies on my own with 
`policy.isRequestOriginAllowed(request.innerRequest);` in `sendEmail()`?

**Comment by joeconwaystk** [comment]
It doesn't block the request if the origin doesn't match, instead, it doesn't attach the CORS response headers. If you issue a preflight request that doesn't match, it will issue a 403. The specification does not proscribe a particular response if there is no origin match, but because CORS is not meant to authorize endpoints, Aqueduct defines this behavior to continue executing the request as normal but not as a CORS request.

**Comment by bjesuiter** [comment]
Ahhhh! :) Okay, that was my misconception! :) 

So when i want to block it, i could simply use the isRequestOrigin allowed method and send back a 403 response, right? 

So, when this is the case, this issue can be closed :) 
Really big thanks for your help, it's not very common to get direct support from the CEO ^^

**Comment by joeconwaystk** [comment]
If you're looking to do any sort of authorization, you'll want to use the OAuth 2.0 implementation. The template has the implementation already available, and I'm currently writing the documentation for it. But yes, if you wanted to override the default behavior you could send back a 403. If you are using HTTPController, you can override willProcessRequest to do this or you can create your own subclass of ReqeustController and insert it into a chain of request controllers.
