### ISSUE TITLE
Error when creating a new project from command line on Windows 7

### ISSUE THREAD

**Issue by aelayeb** [stablekernel/aqueduct#101]
When I'm trying to create a new project from command line with the "aqueduct create" command, I'm getting an error on Windows 7.

Here is the output :

```
C:\Users\Aelayeb>aqueduct create -n web_dart
Fetching Aqueduct as:
  aqueduct: "any"
Determining Aqueduct template source...
ProcessException: Le fichier sp├®cifi├® est introuvable.

  Command: pub get --no-packages-dir
```

Tested on Windows 7 64bits.

**Comment by joeconwaystk** [comment]
So forgive me for not understanding a thing about Windows, but this would seem to indicate that `pub` is not in your PATH. What happens when you run `pub get` from the command line by itself?

**Comment by aelayeb** [comment]
pub is in my PATH and it works fine, but it seems that the "aqueduct create" fails to switch directory before making the pub get command.

**Comment by joeconwaystk** [comment]
So, it must be here: https://github.com/stablekernel/aqueduct/blob/master/lib/commands/template_creator.dart#L75

The template generator works by creating a directory and putting a pubspec.yaml file in that directory. Then it runs pub get to fetch the entire package, which contains the templates. Then it effectively copies over the template contents to that directory. It's either having problems with setting the CWD to the project directory, or finding the pubspec.yaml file in the project directory.

Would you be able to step through the template generator code on your machine? If you instead clone this repository and reactive aqueduct to point at the local installation (`pub global activate -s path path/to/aqueduct`), you should be able to dig into the state of the filesystem at this point.

**Comment by aelayeb** [comment]
Yeah it seems the problem come from this line : 
`var result = Process.runSync("pub", ["get", "--no-packages-dir"], workingDirectory: projectDirectory.path);`
in template_creator.dart.

I tried to do somehing with a minimal code and it failed with the same error.
```
import 'dart:io';

main () {
	var result = Process.runSync("dir", []);
    if (result.exitCode != 0) {
		throw new Exception("${result.stderr}");
    }
}
```
("dir" command is equivalent to "ls" on linux)
It's as if the "Process.runSync" method doesn't use the PATH on windows.
I think it's a dart problem, not an aqueduct one.

**Comment by aelayeb** [comment]
When I add the "runInShell: true" parameter its seems to work but I dont know why it works like this on windows...

**Comment by joeconwaystk** [comment]
Can you also try includeParentEnvironment = true (with runInShell = false)? I wonder if the PATH doesn't get inherited on Windows, and runInShell runs detached in some way so that it does?

**Comment by joeconwaystk** [comment]
Oh nvm, that is already true by default. I'll check to see if runInShell creates issues on macOS and if it doesn't, I'll simply add that to the script.

**Comment by joeconwaystk** [comment]
@aelayeb Would you be able to clone this repo with branch jc/runinshell, then install that as your global aqueduct (`pub global activate /path/to/local/`) and see if the project creation script works? And potentially the setup script as well?

**Comment by aelayeb** [comment]
For the "PATH" problem it's good !
Now I have another error :
```
C:\Users\Jin>aqueduct create -n web_dart
Fetching Aqueduct as:
  aqueduct: "any"
Determining Aqueduct template source...
        Using template source from: /C:/Users/Jin/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/aqueduct-1.0.1.
FileSystemException: Exists failed, path = '/C:/Users/Jin/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/aqueduct-1.0.1/example/templates/default'
(OS Error: La syntaxe du nom de fichier, de r├®pertoire ou de volume est incorrecte.
, errno = 123)
```
The error says "File, directory or drive name syntax is incorrect" (in french).
I think it's because of the first slash in the directory path.
In Windows there is no things such as the "root" filesystem.
Every drives is mounted with a letter which gives path starting by thoses letters.

The incorrect path comes probably from the package uri resolver I think : https://github.com/stablekernel/aqueduct/blob/jc/runinshell/lib/commands/template_creator.dart#L81

I'll try to figure out what's causing this.

**Comment by aelayeb** [comment]
I made a PR against your branch which solve the issue on Windows : https://github.com/stablekernel/aqueduct/pull/111
I don't have a macOS, so if you can try on your side if everything is OK ?
