### ISSUE TITLE
Create discussion forums for Aqueduct

### ISSUE THREAD

**Issue by joeconwaystk** [stablekernel/aqueduct#116]
To facilitate discussion outside of Issues.

Currently interested in http://flarum.org as an option. Google Groups is lowest barrier to entry, but UI leaves much to be desired.

**Comment by aelayeb** [comment]
Flarum seems very nice but it's still in beta and have a lot of bug. 
Moreover it doesn't officially work on php 7 which is sad given the growing popularity of the latter. 
But if you're ready to stumble on some bugs and taking time to resolve them, why not! 
I quite like flarum myself if it was not for the bugs.

**Comment by joeconwaystk** [comment]
Does it? I haven't used it yet - definitely looking for something stable with zero maintenence and looking for recommendations.

**Comment by aelayeb** [comment]
I know Discourse, which is somehow similar to Flarum.
It's written in Ruby and I know few large project which use it (e.g https://www.codingame.com/forum/).
You can have a glimpse at : https://try.discourse.org/
And the project's github : https://github.com/discourse/discourse

I don't know other discussion forum which don't look like websites from '90s.

**Comment by joeconwaystk** [comment]
Oh cool, Discourse looks great. We will have to evaluate that.

**Comment by erikist** [comment]
We could use Aqueduct to create a simple forum. 🎱

**Comment by jkleiser** [comment]
This could be a solution: https://gitter.im/stablekernel/aqueduct

**Comment by anachlas** [comment]
👍 For Gitter since the official Dart chat rooms moved there from Slack.

**Comment by vadimtsushko** [comment]
https://discordapp.com/ is interesting. You not have to install anything on your server. Clients can use very decent web interface or native apps for Windows, IOS or Android. One may read forum in guest mode (without registering at discortd). And so on.

**Comment by MarcusSmith** [comment]
http://slackaqueductsignup.herokuapp.com
