### ISSUE TITLE
Problems getting started with development on windows.

### ISSUE THREAD

**Issue by Fonseca1990** [stablekernel/aqueduct#119]
Hello,

I've been searching everywhere, but no luck. At the moment on my machine i have postgresql and aqueduct installed. The command line recognizes the 2 commands just fine, yet aqueduct keeps saying that i don't have PostgreSQL installed. Might this be a issue with aqueduct? Or somehting i may be doing wrong?

Thanks in advance

> C:\WINDOWS\system32>psql -V
> psql (PostgreSQL) 9.3.5
> 
> C:\WINDOWS\system32>aqueduct
> Invalid command, options are: create, db, setup
> 
> C:\WINDOWS\system32>aqueduct setup
> No psql found in PATH.
> 
> If you do not have PostgreSQL installed locally, you must do so to run tests in an Aqueduct application. For macOS users, download Postgres.app from http://postgresapp.com. Once installed, open the application at least once and add the following line to ~/.bash_profile:
> 
>         export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin
> 
> You may have to reload the shell you ran this command from after installation. For non-macOS users, you must install a local version of PostgreSQLand ensure the command line executable 'psql' is in your PATH.

**Comment by joeconwaystk** [comment]
This appears to be near finished in #118

**Comment by joeconwaystk** [comment]
This is now resolved in 1.0.3.
