### ISSUE TITLE
aqueduct quickstart not working

### ISSUE THREAD

**Issue by geekrumper** [stablekernel/aqueduct#125]
Just did the quickstart instructions and "aqueduct" is failing with following output:
> D:\WORKSPACE\DART\aqueduct_playground>pub run aqueduct setup
> Could not find bin\aqueduct.dart in package aqueduct.

My "path" environment setting is set for dart:
> D:\WORKSPACE\DART>dart --version
> Dart VM version: 1.20.0-dev.10.3 (Wed Oct 12 11:04:40 2016) on "windows_x64"

By activating "aqueduct", pub is telling me aqueduct is already activated:
> D:\WORKSPACE\DART>pub global activate aqueduct
> Package aqueduct is currently active at version 0.9.0.
> Resolving dependencies...

Also by checking my local packages, it seems under "bin" path is only a "test.dart" file:
![aqueduct_package](https://cloud.githubusercontent.com/assets/662318/20207703/7f6871fa-a7e9-11e6-8cef-d0cf10387953.png)

**Additional information**
I also tried the alternative by just adding the dependency (1.0.2) in an empty project:
> D:\WORKSPACE\DART\aqueduct_playground>pub get
> Resolving dependencies...
> Package aqueduct has no versions that match 1.0.2 derived from:
> - aqueduct_playground depends on version 1.0.2

It worked with "any" and still informs about a newer package version
> D:\WORKSPACE\DART\aqueduct_playground>pub get
> Resolving dependencies...
> + analyzer 0.27.3 (0.29.0 available)
> + aqueduct 0.9.0 (1.0.2 available)
> ...

The result is still the same, due to missing "aqueduct.dart" file under "bin" path. The terminal is being ran with "admin" priveleges.

Anyone with similar experiences on windows 64 bit?

**Comment by geekrumper** [comment]
nvm, dart version was already too old... sorry for the fuss... :)

**Comment by joeconwaystk** [comment]
No worries - but there will be one issue for you on Windows with v1.0.2 that has been fixed in a yet-to-be-released 1.0.3 when running aqueduct setup. You can get around that by running the commands it intends to run manually, which is a few postgresql commands.

**Comment by geekrumper** [comment]
Yeah, just got it sorted... the generated tests are running successfully... thx for the reply @joeconwaystk
