### ISSUE TITLE
README.md doesn't tell what to expect after server start

### ISSUE THREAD

**Issue by jkleiser** [stablekernel/aqueduct#128]
I followed the Getting Started, and after doing the `aqueduct create -n my_project` I followed the instructions in the README.md. All went well (on one of my Macs), but after starting my new server, I didn't know what to expect. When I tried just `localhost:8000` in my browser, I got an empty page. If I tried `localhost:8000/users`, I got {"error":"No authorization header."}. At least some response. I think the README.md should give a hint about what one have to provide next.

**Comment by joeconwaystk** [comment]
Yes, good idea. 

Add link to template tutorial (#114) in README.md for generated projects.

**Comment by joeconwaystk** [comment]
Addressed in 2.0 branch
