### ISSUE TITLE
Response.notFound() and 404, logging

### ISSUE THREAD

**Issue by jkleiser** [stablekernel/aqueduct#129]
In my generated test project I have commented out the `.pipe(new Authorizer(authenticationServer))` on the line under `.route("/users/[:id]")` (in my lib/src/aque_test_sink.dart) so I won't get the {"error":"No authorization header."} when I try `localhost:8000/users`. Now I just get an empty page instead. I would have expected a 404. Do I have to provide something for a Response.notFound() to give me a visible 404 page?
What's the easiest way to insert logging lines into a file like lib/src/controller/user_controller.dart?

**Comment by joeconwaystk** [comment]
Aqueduct doesn't provide any behavior for HTML templating. There are other tools that can be used with Aqueduct to provide that behavior.

If you want an endpoint to return HTML, you can configure that by setting the content type of the response (or in the case of an HTTPController, setting the responseContentType). For a router, you can set the `unhandledRequestController` property to a closure that responds to the request with a 404 and html body:

```
router.unhandledRequestController = (req) {
  req.respond(new Response.notFound(headers: {"Content-Type" : "application/html"}, body: htmlString));
};
```

Any `RequestController` subclass has a `logger` property that can be used to log:

```
logger.info("A log statement in a controller");
```

**Comment by jkleiser** [comment]
I didn't ask for HTML templating. I just wanted to produce a very simple HTML response. This far I have not succeeded in doing that. A tutorial example on how to do this would help me. It would also be nice to deliver static HTML files. If other tools are needed for this kind of behavior, it would be nice if the docs had some suggestions.

**Comment by jkleiser** [comment]
In the router.unhandledRequestController above, I guess it should have been `{"Content-Type" : "text/html"}`.
