### ISSUE TITLE
Avoid using parts

### ISSUE THREAD

**Issue by kevmoo** [stablekernel/aqueduct#133]
What Bob said here: https://groups.google.com/a/dartlang.org/d/msg/misc/6Pc7hNfyPUM/FzV5WRj_CgAJ

> Personally, I believe the best practice for using "part" is: don't.
>
> As far as I'm concerned, it has always been a misfeature of the language. I've never liked it, and stopped using it the day export was added to the language. Instead, I make each file its own library. If I want users to be able to import one library and get stuff defined in multiple files, I make a "parent" library that exports those sub-libraries.

**Comment by adaojunior** [comment]
related https://github.com/stablekernel/aqueduct/issues/64

**Comment by kevmoo** [comment]
Ah @joeconwaystk – trust us. All of the imports all over are helpful. It makes dependencies super clear. It makes refactoring super clear.

It makes testing super easy – since you can make implementation code public, just not exported from your primary libraries.

**Comment by joeconwaystk** [comment]
@kevmoo Not a trust thing, I can't find documentation on how this part of Dart behaves. There is https://www.dartlang.org/guides/libraries/create-library-packages, but it's very surface level and I can't tell from the language which parts are convention and which parts are enforced (i.e., is /lib/src privacy enforced by something?). The behavior must be different between dart2js and the VM, and I'd like that understanding, too. In C or any of its derivatives, an import is just a fancy copy-paste, a compiler creates object files, and object files are linked together... I need to know that story for Dart.

**Comment by joeconwaystk** [comment]
Addressed in #141
