### ISSUE TITLE
Possible typo in tutorial, doesn't make sense to me

### ISSUE THREAD

**Issue by jkleiser** [stablekernel/aqueduct#137]
On this page http://stablekernel.github.io/aqueduct/tut/deploying-and-other-fun-things.html, just under the line "GRANT CONNECT ON DATABASE quiz TO quiz_app;", there is a line that start with a small dark rectangle with a backslash inside, followed by a "c". The HTML code for that rectangle is `<span class="err">\</span>`. I cannot make any sense of it. Is it a typo?

**Comment by jkleiser** [comment]
It seems it should have been a plain `\c quiz`. When I tried that, I got `You are now connected to database "quiz" as user ...`. And then `\dt`works fine.

**Comment by joeconwaystk** [comment]
Fixed
