### ISSUE TITLE
db upgrade: invalid byte sequence for encoding "UTF8"

### ISSUE THREAD

**Issue by jkleiser** [stablekernel/aqueduct#138]
I tried to put some non-standard characters into the seed() answersIterator values, like "Mount Æverest", but when I did the `aqueduct db upgrade`, I got this:
```
Applying migration versions: 1
Upgrade failed. Version is now at 1.
[PostgreSQLSeverity.error 22021: invalid byte sequence for encoding "UTF8": 0xc6 0x76 Detail: null Hint: null Table: null Column: null Constraint: null, #0      PostgreSQLPersistentStore.execute.<execute_async_body> (package:aqueduct/db/postgresql/postgresql_persistent_store.dart:117:7)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#2      _RootZone.runBinary (dart:async/zone.dart:1410)
...
```
I use the latest BBEdit on my Mac, and BBEdit says that the ...migration.dart file is UTF-8.
If I do `show client_encoding;` in psql, I get "UTF8".

This is no big problem.

**Comment by joeconwaystk** [comment]
This has been fixed in a recent release of the underlying postgres adapter. Run pub upgrade postgres or just pub upgrade.

**Comment by jkleiser** [comment]
Thanks! `pub upgrade postgres ` did it. Now I get the correct UTF-8 characters from the db in my requests.

**Comment by joeconwaystk** [comment]
just fyi, there is one more small bug in the utf8 change that we plan to fix this week.
