### ISSUE TITLE
How to return HTML page with correct character encoding?

### ISSUE THREAD

**Issue by jkleiser** [stablekernel/aqueduct#140]
In my QuizRequestSink.setupRouter I have a route that returns a plain HTML page:
```
router
  .route("/page")
  .listen((req) async {
    return new Response.ok(await pageText(req),
      headers: {"Content-Type": "text/html", "Charset": "UTF-8"});
  });
```
and the file with my pageText function looks like this:
```
part of quiz;

String pageText(Request request) async {
  return
"""
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Page</title>
</head>
<body>Page ÆØÅ: ${new DateTime.now()}</body>
</html>
""";
}
```
However, when I run my quiz app and try http://localhost:8080/page, the three characters ÆØÅ does not get rendered like they should. What could be missing in my code?

![chars](https://cloud.githubusercontent.com/assets/107986/20627357/b75020e0-b31f-11e6-9858-441fa697b317.png)

**Comment by joeconwaystk** [comment]
change Content-Type header to "text/html; charset=utf-8"

**Comment by jkleiser** [comment]
Thanks!
