### ISSUE TITLE
Problem with proper UTF-8 from quiz database

### ISSUE THREAD

**Issue by jkleiser** [stablekernel/aqueduct#145]
I'm trying to find out why the text that aqueduct fetches from my quiz db seems to have wrong encoding. Using psql I can see this, incl. the "æøå" in the row at the end:
```
quiz=# show client_encoding;
 client_encoding 
-----------------
 UTF8
(1 row)

quiz=# select * from _answer;
 id |      description       | question_index 
----+------------------------+----------------
  1 | Depends on if they can |              1
  2 | Mount Everest          |              2
  3 | Yes, and so are "æøå". |              3
(3 rows)
```
With a simple route like this "/hello" I get the right characters in my browser:
```
router
  .route("/hello")
  .listen((req) async {
    return new Response.ok("Hello ÆØÅ",
      headers: {"Content-Type": "text/plain; charset=utf-8"});
  });
```
However, with routes that displays text coming from the db, the encoding seems to be wrong. I have tried both `"text/plain; charset=utf-8"` and `"application/json; charset=utf-8"`. The text in the 3rd answer shows like this: `Yes, and so are "Ã¦Ã¸Ã¥".`
Any suggestions?

**Comment by joeconwaystk** [comment]
This is an issue that is currently being addressed in https://github.com/stablekernel/postgresql-dart, the underlying database driver and will be incorporated into Aqueduct 1.0.4
