### ISSUE TITLE
Response.ok(someListOfInt) is received as String at the client side

### ISSUE THREAD

**Issue by zoechi** [stablekernel/aqueduct#155]
In the controller
```dart
    final json = resource.toJson();
    final jsonString = JSON.encode(json);
    final data = UTF8.encode(jsonString);
    _log.finest('_toResponse: $data');
    return new Response.ok(data);
```
int the client
```
final request = await client.openUrl(method, uri);
final response = await request.close();
final responseData = await response/*.transform(UTF8.decoder)*/.join();
```
```
[91, 49, 50, 51, 44, 51, 52, 44, 49, 49, ....]
```

![image](https://cloud.githubusercontent.com/assets/405837/21074851/b725678e-bf03-11e6-9478-d69ac3f21127.png)

The same code works fine when I use `shelf` as server where I get `List<int>`

**Comment by joeconwaystk** [comment]
See the docs for Response.addEncoder and Response.contentType... you'll need to set the content type you the response. I don't think there is a default encoder for binary data, so you'll want to add one

Aqueduct doesn't use shelf at all

**Comment by zoechi** [comment]
Just 

```dart
    final json = resource.toJson();
    return new Response.ok(json);
```

worked fine. Thanks for your time.
