### ISSUE TITLE
CORS requests

### ISSUE THREAD

**Issue by zoechi** [stablekernel/aqueduct#156]
I tried to get CORS working

In the client (unit test) I have this code
```dart
      final client = new HttpClient();
      final request = await client.openUrl(
          'OPTIONS', Uri.parse('http://localhost:$port/abc?'));
      request
        ..headers.add('Origin', 'http://example.com/x')
        ..headers.add('Access-Control-Request-Headers')
//        ..headers.add(HttpHeader.accessControlRequestHeaders, "authorization")
 ;
```
The server is configured as

  @override
  void setupRouter(Router router) {
    router
        .route("/auth/token")
        .pipe(new Authorizer(authServer, strategy: AuthStrategy.client))
        .generate(() => new AuthController(authServer));

    router
        .route("/auth/code")
        .pipe(new Authorizer(authServer, strategy: AuthStrategy.client))
        .generate(() => new AuthCodeController(authServer));

    router
        .route("/identity")
        .pipe(new Authorizer(authServer))
        .generate(() => new IdentityController());

    router
        .route("/register")
        .pipe(new Authorizer(authServer, strategy: AuthStrategy.client))
        .generate(() => new RegisterController());

    router
        .route("/users/[:id]")
        .pipe(new Authorizer(authServer))
        .generate(() => new UserController());

    router
        .route("/baseDstu2/:resourceType/:id")
        .generate(() => new FhirGetByIdController(_fhirServer));

    router
        .route("/baseDstu2/:resourceType")
        .generate(() => new FhirSearchController(_fhirServer));

    router.unhandledRequestController = new CorsController();
  }
```
```dart
class CorsController extends HTTPController {
  Response call(Request request) {
    return new Response.ok(null, headers: {
      HttpHeader.accessControlAllowOrigin:
          request.innerRequest.headers[HttpHeader.origin]
    });
  }
}
```
`CorsController.call()` is called when the `OPTIONS` request is received (not sure if this is expected). Just came to that approach because I didn't find another way to make the `OPTIONS` request being handled.

After `return new `Response.ok(...)` the application hangs and my test times out.

**Comment by joeconwaystk** [comment]
Check out the docs http://stablekernel.github.io/aqueduct/http/http_overview.html of how requests are handled. Use the example project's (example/template/default) HTTPControllers as an example or check out the tutorial here: http://stablekernel.github.io/aqueduct/tut/getting-started.html. 

The signature of a responder method in HTTPController must be (Request) -> Future<Response> and have HTTPMethod metadata (like @httpGet)

**Comment by zoechi** [comment]
Thanks for your response.
The example project seems to be the same as created by `aqueduct create -n my_project` - that's where I started from.
I read the docs a few times but seems I don't fully understand yet how it is supposed to be used. 
I also found #100.

> The signature of a responder method in HTTPController must be (Request) -> Future and have HTTPMethod metadata (like @httpGet)

I have such a responder but `@httpPost` or `@httpGet` only makes the methods being called for the actual GET and POST requests, but not the preflight (OPTIONS) requests. I haven't found an `@httpOptions` annotation.

The docs mention that CORS is supported by default but I don't get an `Access-control-allow-origin` header back. I saw while debugging that [isPreflightRequest](https://github.com/stablekernel/aqueduct/blob/bef73f393fb731c104e9f3e7a00317473582ced6/lib/src/http/request_controller.dart#L134) recognizes the `OPTIONS` request as preflight request but then still doesn't add the CORS header to the response.
I then was stuck debugging when the debugger steps into async code, and I wasn't able yet to figure out the following program flow and was hoping to get some pointers.

**Comment by joeconwaystk** [comment]
So it'll automatically implement the preflight request. Every RequestController has a policy property, so you can set its allowedOrigins, headers, etc. in their constructor. @httpGet is just @HTTPMethod("GET"), so you can do @HTTPOptions("OPTIONS"), but you shouldn't have to because everything should be handled by setting up the policy. You can also set CORSPolicy.defaultPolicy with values you want for every request controller

**Comment by zoechi** [comment]
Thanks a lot for you help! I think I got it. 
The main issue that led me astray was that the request URL didn't match any route.
I like Aqueduct so far. Quite powerful without too much complexity.
