### ISSUE TITLE
user_controller_test in template fails

### ISSUE THREAD

**Issue by renefloor** [stablekernel/aqueduct#179]
For the setup the following code is used.
```
     var responses = await Future.wait([0, 1, 2, 3, 4, 5].map((i) {
        return (app.client.clientAuthenticatedRequest("/register")
              ..json = {
                "email": "bob+$i@stablekernel.com",
                "password": "foobaraxegrind$i%"
              })
            .post();
      })); 
```
However, Future.wait can be used when "the order of execution of the functions is not important". But the test asumes that bob+0@stablekernel.com is the first user that is made.

Suggested change:
```
      var responses = new List();
      for(var i=0; i<6; i++){
        var response = await (app.client.clientAuthenticatedRequest("/register")
          ..json = {
            "email": "bob+$i@stablekernel.com",
            "password": "foobaraxegrind$i%"
          })
          .post();
        responses.add(response);
      }
```

**Comment by joeconwaystk** [comment]
👍 Thanks. The underlying database driver is a serial queue and in the tests there is only one database  connection, but those are some grand assumptions for the tests to make going forward.

**Comment by renefloor** [comment]
Hmm.. strange. I ran the test on my laptop and they failed most of the time. I got numbers ranging from 0 to 3. I didn't change anything on the standard template.

**Comment by joeconwaystk** [comment]
now in 2.0 branch
