### ISSUE TITLE
How to deploy dart-aqueduct server-side app into Google App Engine?

### ISSUE THREAD

**Issue by aberbegall** [stablekernel/aqueduct#186]
Is there any documentation/instructions about how to deploy a server-side app developed with aqueduct into Google App Engine?

I checked the samples here:
https://github.com/dart-lang/appengine_samples

but those dart samples are not using aqueduct framework.

**Comment by joeconwaystk** [comment]
There isn't yet. In the upcoming 2.0 release, we've added tools for deployment (you can see the upcoming documentation here: https://github.com/stablekernel/aqueduct/tree/jc/docs2/_posts/deploy). 

The issue with Google App Engine is that - from what I understand - only MySQL is supported, and Aqueduct currently only supports PostgreSQL. Aqueduct 2.0 will likely make it easier to implement MySQL support and I don't think it's a huge burden to then implement Google App Engine support.

**Comment by aberbegall** [comment]
Ok, it sounds promissing. 
I'm new to Google cloud but I think you are right in Google App Engine the PostgreSQL is not supported out-of-box and needs to be installed on the Google Compute Engine and configured to be accessible from App Engine: https://cloud.google.com/solutions/set-up-postgres

Before version 2.0 is released I'll try to deploy an small dart-aqueduct project, just to learn and get some experience.
Thanks for the quick feedback
