### ISSUE TITLE
WebSocket for aqueduct

### ISSUE THREAD

**Issue by devnasirali** [stablekernel/aqueduct#220]
I am facing problem to run server as socket base connection using aqueduct. I am trying this code for it:

start.dart:

`var server = app.server.server;
    await for (HttpRequest req in server) {
        if (WebSocketTransformer.isUpgradeRequest(req)){
            WebSocketTransformer.upgrade(req).then(handleWebSocket);
        }
    }`

is there any way to run server that can accept both http and socket connections ?

**Comment by joeconwaystk** [comment]
You can set up a route that upgrades the request:

```dart
router
        .route("/connect")
        .listen((req) async {
          if (!WebSocketTransformer.isUpgradeRequest(req.innerRequest)) {
            return new Response.badRequest();
          }
    
          var webSocket = await WebSocketTransformer.upgrade(req.innerRequest);
          webSocket.listen((event) {
            // send back whatever we received
            webSocket.add(event);
          });
        });
```

This behavior is currently planned (#115), so closing this issue as its a dupe. We'll eventually have more formal support for websockets. What I've shown here isn't rigorously tested; I just fired it up for a quick test and it was fine, though. 

Also, there shouldn't be a need to have a start.dart file with 2.0 - use `aqueduct serve` instead.

**Comment by devnasirali** [comment]
How can i set timeout for socket connection ? let say if the client didn't respond for more than 1 minute i want to close that connection automatically on the server.

**Comment by joeconwaystk** [comment]
https://api.dartlang.org/stable/1.22.1/dart-io/WebSocket-class.html#pingInterval

**Comment by devnasirali** [comment]
I am trying to save open connections in a map but every time a new request came, my map reset and it only show's the last connection. I am writing this code in "*_sink.dart" file.

`
final Map<String, WebSocket> connections = new Map<String, WebSocket>();

router
            .route("/connect")
            .listen((req) async {
if (!WebSocketTransformer.isUpgradeRequest(req.innerRequest)) {
                return new Response.badRequest();
            }else{
                String name = "c_${req.innerRequest.uri.queryParameters["from"]}_${req.innerRequest.uri.queryParameters["to"]}";
                WebSocket webSocket;
                if(connections[name] != null){
                   //TODO: check state of socket before using
                    webSocket = connections[name];
                }else{
                    webSocket = await WebSocketTransformer.upgrade(req.innerRequest);
                    connections[name] = webSocket;
                }

                print("Open Connection: ${connections.length}");

                webSocket.listen((event) {
                    // send back whatever we received
                    webSocket.add(event);
                });
            }
        });
`

It always shows "Open Connection: 1".
