### ISSUE TITLE
[Feature Request] DB field with length support

### ISSUE THREAD

**Issue by sclee15** [stablekernel/aqueduct#223]
Hello.

Thanks for a awesome project!

I noticed that all the string attributes in persistence object instance creates text field in postgresql.

I hope that there is a way to set VARCHAR(64) in Aqueduct.

thank you.

**Comment by joeconwaystk** [comment]
What behavior are you trying to get to? Restricted length for input fields?

**Comment by sclee15** [comment]
@joeconwaystk Many tables are contain such fields like VARCHAR(64) and I think it would be cool if Aqueduct db migration support such fields.

Of course i would like to control the user inputs for length checking or other validity check.

**Comment by joeconwaystk** [comment]
Follow up here - there is an accepted proposal for this implementation. Will be available in 2.1.

**Comment by joeconwaystk** [comment]
Now available with validators in 2.1
