### ISSUE TITLE
[Feature] Auto server restart when *.dart file changes

### ISSUE THREAD

**Issue by sclee15** [stablekernel/aqueduct#224]
I am getting familiar with aqueduct.
I found that it is little tedious that i restart the server by typing aqueduct server every time i changed the code. May be this could be better with some little CLI automation.

Thank you.

**Comment by joeconwaystk** [comment]
Yes, this one is our internal tracker, so it is currently planned.

**Comment by joeconwaystk** [comment]
Merging this into #426 and closing
