### ISSUE TITLE
Unable to add AOuth Client

### ISSUE THREAD

**Issue by pjcunningham** [stablekernel/aqueduct#264]
I'm following the steps outlined [here](http://aqueduct.io/docs/deploy/deploy_local/) and get an error when trying to creating an AOuth client.

Aqueduct command (database connection details are in database.yaml):

`aqueduct auth add-client --id com.aqueduct_test.standard --secret abcdefghi`

Output:
```
-- Aqueduct CLI Version: 2.1.1
-- Aqueduct project version: 2.1.1
*** NoSuchMethodError: The getter 'dataModel' was called on null.
Receiver: null
Tried calling: dataModel
```

**Comment by joeconwaystk** [comment]
Yikes, yes, you are right. Thank you - there is a simple mistake in the tests prevented this from being picked up. 

2.2 is getting released this week and I'll make sure this fix is in. In the interim, you can add clients manually. The client secrets are hashed with a salt in the database, so run a quick Dart script to generate the credential pair and then execute the SQL:

```dart
import 'package:aqueduct/aqueduct.dart';

void main() {
  var credentials = AuthUtility.generateAPICredentialPair("com.aqueduct_test.standard", "abcdefghi");
 print("${credentials.id} ${credentials.hashedSecret} ${credentials.salt}");
}
```

Then those printed values (in order) are the three values below:

```sql
INSERT INTO _authclient (id, hashedSecret, salt) VALUES ('id', 'secret', 'salt');
```
