### ISSUE TITLE
Template language integration

### ISSUE THREAD

**Issue by cwchentw** [stablekernel/aqueduct#270]
Dear Aqueduct Team:

I am interested in this framework. However, there is no page about using any template language on aqueduct. It seems that currently only mustache is supported in Dart community. It any feasible mean to integrate mustache or other template language into this framework, e.g. through plugin?

Sincerely,
Michael

**Comment by joeconwaystk** [comment]
Sure, you can use the Dart mustache package with Aqueduct. Something like mustache produces a String, and Aqueduct can send a `text/html` response with that String as a body. 

I'll give you a really naive implementation with Mustache and then some tips on where else to look in Aqueduct.

1. Create an `RequestController` subclass that reads template files from the filesystem and replaces the values:

```dart
class TemplateController extends RequestController {
  @override
  Future<Response> processRequest(Request request) async {
    var templateDirectory = new Uri("templates/");
    var templateFile = new File.fromUri(templateDirectory.resolve(request.path.remainingPath);
    var templateContents = templateFile.readAsStringSync();
    var template = new Template(templateContents);

    var rendered = template.renderString({"thing" : "value"});
    
    return new Response.ok(rendered)
      ..contentType = ContentType.HTML;
  }
}
```

2. Hook that controller up to a route in a `RequestSink` subclass, the initialization point of an app:

```dart
class MyRequestSink extends RequestSink {
  @override
  void setupRouter(Router router) {
    router.route("/web/*").pipe(new TemplateController());
  }
}
```

I just spit this code out, so there may be errors. Some other places to look are at the source code for the [static file controller](https://github.com/stablekernel/aqueduct/blob/master/lib/src/http/file_controller.dart) and the documentation on how [response bodies are sent](https://aqueduct.io/docs/http/request_and_response/#response-objects-and-http-body-encoding)

**Comment by cwchentw** [comment]
Thanks, I will try this later.
