### ISSUE TITLE
Aqueduct CLI create config file problem

### ISSUE THREAD

**Issue by KRIOFT** [stablekernel/aqueduct#293]
Hi,

I recevied the next error 
```*** FileSystemException: Cannot copy file to '/home/ioan/dev/autoprofile.net/backend/config.yaml', path = '/home/ioan/dev/autoprofile.net/backend/config.yaml.src' (OS Error: No such file or directory, errno = 2)```

The CLI installer try to copy ```config.yaml.src``` but the project use ```config.src.yaml```

**Comment by joeconwaystk** [comment]
Can you upgrade your CLI to 2.3 with pub global activate? The templates got modified recently.

**Comment by KRIOFT** [comment]
Yes, problem solved. :+1:  Thanks

**Comment by joeconwaystk** [comment]
👍 Going forward, will be a non-issue since the templates will get pulled from local pub cache instead of remotely. Had to rip the bandaid on this version :)
