### ISSUE TITLE
a unencodedInitialValue error value is generated

### ISSUE THREAD

**Issue by sclee15** [stablekernel/aqueduct#299]
I am following the tutorial
https://aqueduct.io/docs/db/modeling_data/

I added email field and ran aqueduct db generate.
It was awesome except i see following

class Migration2 extends Migration {
  Future upgrade() async {
    database.addColumn("_User", new SchemaColumn("email", ManagedPropertyType.string, isPrimaryKey: false, autoincrement: false, isIndexed: false, isNullable: false, isUnique: true), unencodedInitialValue: <<set>>); ////<-- error after unencodedInitialValue:

  }

  Future downgrade() async {
  }
  Future seed() async {
  }
}

When i delete that, it looks ok.
anyway, when i see the replaying version 1 i got goosebumps.
AWESOME. 

Well designed indeed.

**Comment by joeconwaystk** [comment]
When adding a column to an existing table that isn't nullable, you must have a value for any existing rows in the database for that column. The migration generator intentionally puts an invalid token `<>` in this parameter to indicate that you'll need to specify it. It can be some default value ("'unknown@unknown.com'") or you can let `email` be nullable. Or, if you know you have no rows yet, you can simply delete the previous migrations and re-generate them.

Note that unencodedInitialValue is a String that is passed verbatim to the underlying database, so for email, you do need inner quotes `"'abcdef'"`.

**Comment by sclee15** [comment]
Wow. it is very thoughtful design.
Case Closed
