### ISSUE TITLE
Documentation does not work for headers

### ISSUE THREAD

**Issue by erikist** [stablekernel/aqueduct#306]
When using `aqueduct document` and overriding `documentRequestBodyForOperation` from `HTTPController`, you cannot actually document headers as parameters for requests.  

I used this to attempt to generate the correct documentation of a header: 
```
      operation.parameters.add(new APIParameter()
        ..parameterLocation = APIParameterLocation.header
        ..name = 'Accepts-Language'
        ..schemaObject = new APISchemaObject.string()
      );
```

**Comment by joeconwaystk** [comment]
👍 Plus query/header/body bindings should automatically be added, I don't think they are currently

**Comment by erikist** [comment]
Indeed!

**Comment by joeconwaystk** [comment]
done :+1:
