### ISSUE TITLE
why not mysql or when mysql support ?

### ISSUE THREAD

**Issue by krircc** [stablekernel/aqueduct#321]
mysql is most popular database, i want use aqueduct but we use mysql.

**Comment by joeconwaystk** [comment]
1. What is missing from PostgreSQL that you can do with MySQL?
2. Using the ORM to retrofit an existing database isn't going to work all that well, so you'd be starting with a new database anyhow.
3. You can use MySQL with Aqueduct with https://pub.dartlang.org/packages/sqljocky, you just can't use the ORM.
4. You could alternatively implement the PersistentStore interface in Aqueduct with MySQL.

**Comment by krircc** [comment]
ok.

**Comment by NTMS2017** [comment]
@joeconwaystk, I have similar question. I don't need ORM, so where I can find that I can use aqueduct with mysql or oracle? from channel I create my controller on as NtmsApiController.dart and I have the 
Future<RequestOrResponse> handle. but I don't know how to call mysql send the request and get data back and attach to response.

Do you know or have any examples?


```
class NtmsApiController extends Controller {
  @override
  Future<RequestOrResponse> handle(Request request) async {
    try {
            if (request.path.remainingPath != null) {
           _requestValue = request.path.remainingPath;
          …
          …
```
