### ISSUE TITLE
TechEmpower benchmark implementation?

### ISSUE THREAD

**Issue by foliot** [stablekernel/aqueduct#332]
Are there any plans to add Aqueduct to the TechEmpower benchmark suite? 

[https://github.com/TechEmpower/FrameworkBenchmarks](https://github.com/TechEmpower/FrameworkBenchmarks)

**Comment by sclee15** [comment]
Although i am curious about the result , but i am expecting that the result will be much same as redstone

**Comment by joeconwaystk** [comment]
No. If someone wants to, we'd certainly help.

**Comment by indiealexh** [comment]
I'm gonna take a crack at this.

**Comment by joeconwaystk** [comment]
Great! Make sure to turn off logging 🚤

**Comment by indiealexh** [comment]
I have finished writing the benchmark code.
Its open for review before I PR it back to the TE repo.

https://github.com/indiealexh/FrameworkBenchmarks/pull/1

**Comment by sclee15** [comment]
@indiealexh Great job. How much RPS are you expecting?

**Comment by foliot** [comment]
Could you run that and a benchmark for some other framework so we can get a frame of reference?

**Comment by joeconwaystk** [comment]
I think there would be value in a pure dart:io implementation as a reference point. There should be some minimal overhead between a framework and dart:io, because the framework will add some.

**Comment by indiealexh** [comment]
@sclee15 depends on their hardware.
Its going through CI rn, so we should get some estimates soon
https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/366197048?utm_source=github_status&utm_medium=notification

**Comment by indiealexh** [comment]
@foliot @joeconwaystk 
There is a Dart IO implementation in the Benchmark repo already, and the config marks to compare the speed directly against this.

**Comment by indiealexh** [comment]
Not a fair comparison, but on my laptop in docker I got these results 
![image](https://user-images.githubusercontent.com/1066212/38749643-33feb272-3f07-11e8-9b28-c494156c3ccc.png)

But not a fair test since Limited cores and a lot of application noise on laptop.

**Comment by joeconwaystk** [comment]
This is close to what I'd expect without being able to warm the VM. The challenge is that each isolate must be warmed individually, so there is a N*x increase where N is number of isolates. Is there a way to pre-warm in the benchmark?

**Comment by indiealexh** [comment]
The benchmark has two warm up stages.
Primer (pre warm up warm up), Warm up, Actual benchmarks.

I need to check my data isnt from warm up

**Comment by indiealexh** [comment]
Awaiting Travis build for PR approval and merge
https://github.com/TechEmpower/FrameworkBenchmarks/pull/3561

**Comment by joeconwaystk** [comment]
👍 Results are here: https://tfb-status.techempower.com/results/3f5e1eca-f530-403c-ab0a-39769ff7c8da. Comparable to Flask and Phoenix, based on the results.
