### ISSUE TITLE
Question about job

### ISSUE THREAD

**Issue by mobilemindtec** [stablekernel/aqueduct#374]
Hi,

How do I create a job that runs every few minutes? I tried create something like:

```
class CheckerJob{

  static bool started;

  static void start(){

    if(started)
      return;

    started = true;

    var stream = new Stream.periodic(const Duration(minutes: 10), (count) {
      print("run periodic stream");
      var job = new CheckerJob();
      job.job();
      return "ok";
    });


    stream.listen((result) {
      print("stream periodic result: ${result}");
    });
  }

  Future job() async {
    // do something
  }
}
```
And in `RequestSink` I call `CheckerJob.start()`. In `job` method I connect in MongoDB and do many verifications.. but apparently this is causing some crash that kill aqueduct application at any given moment.

Is there another way to implement a job like Java Quartz Job Scheduler? Or else, where I found app crash log? I start the server using `--detached` option.

Thanks!

**Comment by joeconwaystk** [comment]
A few things here.

You can listen for uncaught errors by adding an error listener to the current isolate. 

```dart
final port = new ReceivePort()
  ..listen((err) {
      logger.error("$err");
  });
Isolate.current.addErrorListener(port.sendPort);
```

This will print uncaught errors to the console. You should run without detached mode, or you'll need to adjust your logger listener to write to a file of the default (stdout). It's likely a better solution to write your failable job code in a try-catch block.

In general, you wouldn't want to run periodic tasks like these in your web server application; for example, an API deploy might interrupt a long-running job and leave it in an inconsistent state. Job scheduling depends on your environment; e.g. a CronJob object in a Kubernetes cluster.

But if you do want to do something like this in Aqueduct, you'd want to implement it in this method in your sink:

```dart
class Sink extends RequestSink {
   static Future initializeApplication(ApplicationConfiguration config) async {
    // start job/timer
   }
}
```

This starts the job/timer once per application launch. If you do it elsewhere in a RequestSink, you'll start it *once per isolate*.

**Comment by jyksnw** [comment]
I have been looking at using [Faktory](https://github.com/contribsys/faktory) to offload my non-API specific jobs. Of course, there are other services/solutions out there depending on your needs ([RabbitMQ](https://www.rabbitmq.com) comes to mind).

The downside at the moment with [Faktory](https://github.com/contribsys/faktory) is that it doesn't appear to have a Dart worker package yet. I had hoped on writing one when I got to that point in my own project. It does appear that there are few Dart packages for working with RabbitMQ though depending on your immediate needs.

**Comment by mobilemindtec** [comment]
Hi @joeconwaystk,

Thanks for the answer! I'm changed my project and added the logger as you suggested. My job already started  into `initializeApplication`. Now let's see how it behaves!

My code stayed like this:

```
static Future initializeApplication(ApplicationConfiguration config) async{

    var fileHandler = new SyncFileLoggingHandler("dart.job.log", transformer: new StringTransformer());
    var logger = new Logger("aqueduct");
    logger.onRecord.listen(fileHandler);
    logger.onRecord.listen((rec) => print("$rec ${rec.error ?? ""} ${rec.stackTrace ?? ""}"));

    final port = new ReceivePort()
      ..listen((err) {
         logger.severe("${err}", err);
      });

    Isolate.current.addErrorListener(port.sendPort);

    CheckerJob.start();
}
```

Thanks!

**Comment by mobilemindtec** [comment]
Hi, 

I have a new issue about this situation.  I was able to capture the error that breaks the aqueduct server.

```
../../runtime/vm/dart_api_impl.cc: 1878: error: Dart_GetMainPortId expects there to be a current isolate. Did you forget to call Dart_CreateIsolate or Dart_EnterIsolate?
```

So I'm trying, without success, run my job on a new Isolate.

Code into `CheckJob.start()` that is called on `initializeApplication`
```
    var stream = new Stream.periodic(const Duration(seconds: 15), (count) {

      ReceivePort response = new ReceivePort()
        ..listen((err) { print("${err}"); });

      Future<Isolate> remote = Isolate.spawn(runner, response.sendPort);

      remote.then((_) => response.first).then((sendPort) {
        print("isolate finished");
      }).catchError((err){
        print("error on create isolate: $err");
      });
 
     return "ok";

    });

    stream.listen((result) {
      logger.info("stream periodic result: ${result}");
    });
```

The "job" method:

```
void runner(SendPort replyTo) {
  print("job runner");
  var port = new ReceivePort();
  replyTo.send(port.sendPort);
}
```

But running this code I get this error:

```
error on create isolate: IsolateSpawnException: Unable to spawn isolate: Unhandled exception:
Could not load "file:///home/ricardo/sources/dart/sms_sender_ms/bin/.tmp_aqueduct_serve_start.dart": FileSystemException: Cannot open file, path = '/home/ricardo/sources/dart/sms_sender_ms/bin/.tmp_aqueduct_serve_start.dart' (OS Error: No such file or directory, errno = 2)

```

I do not understand what is happening, you can help me?

Thanks!

**Comment by joeconwaystk** [comment]
Is this still happening? 

I can't tell exactly what is happening, but I have some guesses. The first error comes from shutting down the application, but you still have an open `ReceivePort` in your spawned isolate that is keeping the VM running. 

The second error you get when trying to run may have more to do with the application not being cleaned up because of the first error. The `aqueduct serve` command generate a script file (`.tmp/aqueduct_serve_start.dart`) to run your application. For whatever reason, that file is not able to be found - I do wonder if it is because of the inability to shut down the application from the previous error? What happens when you run the application via `dart bin/main.dart`?

**Comment by mobilemindtec** [comment]
Hi,

Thanks for answering. Those errors is not related. The first occurred  when I started my job into `initializeApplication`, but I think that is because I not call `catchError` on my `Future`, so the application is killed. My foult.

But, the second, I use the same logic, but now running the job into a Isolate.  If I run `dart bin/main.dart` isolate's job work fine!
