### ISSUE TITLE
Aqueduct and the future of DartVM ?

### ISSUE THREAD

**Issue by sandrobilbeisi** [stablekernel/aqueduct#386]
I was wondering what does the Aqueduct team think about Google's intentions with DartVM

I know you have a major DartVM investment in the Aqueduct framework 
I also have been working heavily on server-side Dart

I'm a little bit worried about its future because Google seems to be obsessed about the front-end web and Flutter implementations 

the latest developers' conference didn't almost mention DartVM ...

**Comment by joeconwaystk** [comment]
This all seems overblown. The marketing has narrowed to better onboard people into the language, but nothing technical is changing. Server-side Dart and Aqueduct will continue to exist. We are continuing to invest in Aqueduct, and you can see the progress on the [3.0 branch](https://github.com/stablekernel/aqueduct/blob/3.0/CHANGELOG.md).

Members of our team spoke at the latest DartConf on server-side Dart. The Dart team has been very supportive of Aqueduct. They have been great about our feedback and communicating their direction, and I have participated in a regularly scheduled meeting with them for some time.

The best thing anyone can do for Dart server-side is to use, talk about, or contribute to Aqueduct.

**Comment by sandrobilbeisi** [comment]
thank you very much for reassuring us !

**Comment by joeconwaystk** [comment]
👍
