### ISSUE TITLE
Allow resource controller endpoints to take query params as optional arguments

### ISSUE THREAD

**Issue by itsjoeconway** [stablekernel/aqueduct#4]
An endpoint could have optional arguments to automatically grab query parameters. These shouldn't impact routing or which handler gets the query parameters. A signature for a handler could then look like this:

@httpGet 
Future<Response> getThings({String location, String name}) {}

where name and location are names of query parameters (case insensitive) and if they exist, those arguments are populated.

**Comment by seanmavley** [comment]
Good!

Now, how does one construct the URL?
`example.com/search?limit=5&page=10` how would that be constructed to be optional?

The routing doc here, https://aqueduct.io/docs/http/routing/ doesn't mention anything about query params routes construction

**Comment by EddieKamau** [comment]
By wrapping an argument in curly brackets:

```
@Operation.get()
Future<Response> foo({@Bind.query('name') String name}) async 
{}
```
This is documented here:  http://aqueduct.io/docs/http/resource_controller/#optional-bindings

**Comment by evertonfoz** [comment]
@EddieKamau , when I use 

```@Operation.get()
Future<Response> foo({@Bind.query('q') String name}) async {}```

and don´t send any query parameters, I receive the 

```
 The method '[]' was called on null.
Tried calling: []("q") #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
```

Can you help me please?
