### ISSUE TITLE
Failed "git clone" command

### ISSUE THREAD

**Issue by macropas** [stablekernel/aqueduct#417]
Failed git command from 3.0 branch documentation (Fedora 27 terminal)

```
$ git clone git@github.com:stablekernel/aqueduct.git
Cloning into 'aqueduct'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by joeconwaystk** [comment]
Try `git clone https://github.com/stablekernel/aqueduct.git`?

**Comment by macropas** [comment]
@joeconwaystk 
```
$ git clone https://github.com/stablekernel/aqueduct.git
Cloning into 'aqueduct'...
remote: Counting objects: 18041, done.
remote: Compressing objects: 100% (165/165), done.
remote: Total 18041 (delta 57), reused 31 (delta 16), pack-reused 17860
Receiving objects: 100% (18041/18041), 14.43 MiB | 813.00 KiB/s, done.
Resolving deltas: 100% (13222/13222), done.
```

**Comment by joeconwaystk** [comment]
👍 All good? Will close this issue.

**Comment by macropas** [comment]
@joeconwaystk But `git clone git@github.com:stablekernel/aqueduct.git` in documentation can embarrass readers ;)

**Comment by macropas** [comment]
@joeconwaystk [http://aqueduct.io/prerelease-3.0/docs/](http://aqueduct.io/prerelease-3.0/docs/)

**Comment by joeconwaystk** [comment]
👍 I'll add a note. The difference between the URLs is about your local setup. If you are using SSH key access (typically when using GitHub 2FA), the `git` protocol URL is used. Otherwise, the `https` URL. Thanks!
