### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by gedw99** [stablekernel/aqueduct#423]
Am learning dart and I noticed the Todo example shares the data store on both sides. Does it use sqllite client side ? Could not see it though so confused.

This framework is pretty nice.
Server side you just need dart.exe and your snapshot. But how obfuscated is the code ? I ask because I would be running that layer on desktops, not servers. 

Also what's the deal with open source. Are you going to extend are offer enterprises stuff like HA later. Hope you don't mind me asking, but I like what I see with aqueduct but not sure about the future roadmap etc

**Comment by joeconwaystk** [comment]
1. The shared code is shared between Flutter and Angular, not between client and server. Aqueduct 3 supports auto-generation of OpenAPI documents from your application to generate client data/service layer.

2. I don't know of anything in Dart for code obfuscation, but it is a common request - that's a better question for https://github.com/dart-lang/sdk.

3. Open source has benefits to our company, primarily around sales and recruiting. HA is best accomplished by combining other tools (AWS/GCP/Azure load balancers, Nginx, HAProxy, etc.) with Aqueduct. To get an idea of what is coming, check the CHANGELOG in the 3.0 branch.

Will close this issue, but feel free to continue discussing here and I'll answer best I can.

**Comment by gedw99** [comment]
Cheers
