### ISSUE TITLE
Hot Reload

### ISSUE THREAD

**Issue by decapo01** [stablekernel/aqueduct#426]
Would it be possible to add hot reload / refresh capabilities to this?

**Comment by joeconwaystk** [comment]
There isn't any work planned to do this. There is a keyboard shortcut to Save + Rerun in IntelliJ (it defaults to ^F5) when you run an application via `dart bin/main.dart`. (I don't know if this exists in VS Code.) 

This is preferable - it is the same number of keystrokes to 'reload on save', it doesn't require adding complexity and test surface to the `serve` command, and the application relaunches faster because it doesn't have to run in observatory and doesn't have to manage debouncing. 

If there is a compelling reason for hot reload that I'm not understanding, I am open to it.

**Comment by decapo01** [comment]
I've got it working on intellij but was unable to do it in vs code.  vs code has a hot reload feature on their debugger however it's not working properly due to the fact that it's not killing the process.  This happens also when you use the stop function on the debugger.  The debugger is released but the dart process continues and you have to kill it manually.  I may put an issue into the dart vs code repo later on.  I would think something like that would be caught pretty quickly any way.

**Comment by danieldaeschle** [comment]
Hotreload is just nice for faster development. Restarting on every change can be annoying

**Comment by TomasRup** [comment]
Guys, I've started looking to Dart and/or Flutter exactly for a **fast hot reload**. So AT LEAST a server restart upon file change would be a huge step forward, but an actual hot reload would be really necessary.

**Comment by hariangr** [comment]
Is there any progress on this?

**Comment by modulovalue** [comment]
For anyone interested, there's a 'comment' about why hot reload doesn't make sense in aqueduct [here](https://aqueduct.io/docs/cli/running/).

**Comment by sayhicoelho** [comment]
Currently using VS Code you can do the following:

1. Start the server by pressing `F5` in `bin/main.dart` file
2. Press `CTRL + SHIFT + F5` to restart the server *(this is a fast task)*

Done!

*PS: The Hot Restart feature should be implemented by adding a plugin for VS Code and not Aqueduct indeed.*

**Comment by MyracleDesign** [comment]
With the last comment in place, I would suggest closing that issue.

**Comment by marianocordoba** [comment]
Maybe a bit late, but I will leave this here in case it is helpful for anyone. I wanted my server to restart (not reload) every time i make a change to the code. My solution was to use [nodemon](https://nodemon.io/):

`nodemon --exec "aqueduct serve" --watch lib -e dart`

**Comment by ghtmpn** [comment]
In addition to nodemon method above. If you like to just type `nodemon<Enter>` to run your app, create a `nodemon.json` file with the following contents in your app directory:

```json
{
    "verbose": false,
    "delay": "10",
    "watch": [
        "."
    ],
    "ignore": [
        "build",
        "tmp"
    ],
    "ext": "dart html scss",
    "exec": "dart main.dart",
    "execMap": {
        "dart": "dart"
    }
}
```

@marianocordoba 's `nodemon.json` would look like this:

```json
{
    "watch": [
        "lib"
    ],
    "ext": "dart",
    "exec": "aqueduct serve"
}
```
---
To install `nodemon` itself: install latest Node.js and then run `npm i -g nodemon` in your terminal/cmd window

**Comment by devisions** [comment]
I manage to have a working _restart on changes of specific files and locations_ setup using [Watchman](https://facebook.github.io/watchman/) on my macOS (although it shouldn't be platform specific.

Therefore, to whom it may concern, I could share my notes. I will do it either way 😊 , just wanted to know if somebody is still keen to have it working.

**Comment by mmcc007** [comment]
If you want to use the debugger after a file save and a restart, and even rerun your last test debug session, see [this](https://github.com/Microsoft/vscode/issues/49209#issuecomment-675101308) for vscode. Should be something equivalent for other IDEs.
