### ISSUE TITLE
Dart 2 support

### ISSUE THREAD

**Issue by development-s365** [stablekernel/aqueduct#433]
Dart 2 compatibility for flutter support

**Comment by joeconwaystk** [comment]
Aqueduct 3.0 will support Dart 2.0. There are some blocking issues in Dart 2 that prevent Aqueduct from running.  I will resolve this issue when those issues are resolved.

**Comment by joeconwaystk** [comment]
- [ ] Update template pubspecs Dart SDK version to ^2.0.0
- [ ] Update/verify dependency packages to release versions
- [ ] Set package SDK constraint ^2.0.0
- [ ] Revert travis.yml to Dart stable when available
- [ ] Add code coverage back to travis.yml when available

**Comment by dviluk** [comment]
dart-lang/sdk#33207 is solved?

**Comment by joeconwaystk** [comment]
33207 has not yet reached the dev channel, but will soon.

**Comment by joeconwaystk** [comment]
A beta has been deployed to pub and Dart 2 support is complete. This issue will remain open until Dart 2 is in the stable channel and the remaining version constraint tasks can be completed.

**Comment by joeconwaystk** [comment]
Dependency checklist:

- [ ] isolate_executor ^2.0.0
- [ ] open_api ^2.0.0
- [ ] password_hash ^2.0.0
- [ ] postgres ^1.0.0
- [ ] safe_config ^2.0.0
- [ ] aqueduct_test ^1.0.0
- [ ] codable ^1.0.0
