### ISSUE TITLE
Failed test with harness returns `Instance of 'TestResponseBody` instead of meaningful data

### ISSUE THREAD

**Issue by edward-shen** [stablekernel/aqueduct#441]
**Aqueduct Version:** 3.0.0-alpha.1
**Expected Behavior:** Failing a test returns the body of the failed content rather than just `Instance of 'TestReponseBody'`. Additionally, sending an empty JSON array also causes the test to not return why it differs if it contains a `contains` matcher.
**Actual Behavior:**
```
package:test                             expect
test/search_controller_test.dart 177:5   main.<fn>
===== asynchronous gap ===========================
dart:async                               _Completer.completeError
test/search_controller_test.dart         main.<fn>
===== asynchronous gap ===========================
dart:async                               _asyncThenWrapperHelper
test/search_controller_test.dart 176:38  main.<fn>

Expected: --- HTTP Response ---
          - Status code must be 200
          - Headers can be anything
          - Body after decoding must be:
          
            contains 'tags'
          ---------------------
  Actual: TestResponse:<-----------
          - Status code is 200
          - Headers are the following:
            - content-encoding: gzip
            - content-length: 22
            - x-frame-options: SAMEORIGIN
            - content-type: application/json; charset=utf-8
            - x-xss-protection: 1; mode=block
            - x-content-type-options: nosniff
            - server: aqueduct/1
          Instance of 'TestResponseBody'
          -------------------------
          >
   Which: the body differs for the following reasons:
          


```
Note that the extra whitespace at the end is part of the data it returns, not my formatting.

**Steps to reproduce:**
1. Have an route that returns JSON data:
```dart
router.route('/').linkFunction((req) async => new Response(200, null, []));
```
2. Create a test that the return JSON data fails on.
```dart
test('GET root of website', () async {
  expect(
      await harness.publicAgent.get('/'),
      hasResponse(200, body: contains("tags")));
});
```

**Comment by joeconwaystk** [comment]
Thanks for filing. Adding reference information here for the forthcoming fix.

`TestResponseBody` must implement its `toString` method to return the decoded body. Previous to this regression, `TestResponse.toString` accessed the decoded body, but now directly references the body's `toString`. There is no test coverage to ensure that the decoded body are included in the failure. This coverage needs to be added.

**Comment by joeconwaystk** [comment]
The decoded body will now be part of the output. I'm leaving this open w.r.t. the empty list not showing the 'differing reasons'. This may be something in package:matcher, but it needs to be investigated further.

**Comment by joeconwaystk** [comment]
OK, the remaining issue is that `package:matcher` does not have output for a `contains` matcher that does not meet the criteria. Prob makes sense to file at https://github.com/dart-lang/matcher/issues
