### ISSUE TITLE
Update hosted IntelliJ keyboard shortcut settings

### ISSUE THREAD

**Issue by joeconwaystk** [stablekernel/aqueduct#452]
- [x] Create versioned settings.jar for 3.0 
- [x] Add 'ps' -> (o) -> o.# live template
- [x] Replace download link in README
- [x] Replace download link in documentation
- [x] Update documentation guide for usage

**Comment by Sacchid** [comment]
[Enabling settings sync or account sync in IntelliJ disables local settings](https://youtrack.jetbrains.com/issue/IDEA-198980)
So, can not import settings.jar

However live templates can be added, can we share those
for example - `iter` - dart live template - 
`for (var $VAR$ in $ITERABLE$) {
  $END$
}`
