### ISSUE TITLE
error on activating pub global activate aqueduct

### ISSUE THREAD

**Issue by NTMS2017** [stablekernel/aqueduct#468]
Last login: Fri Jun 22 14:42:18 on ttys000
Niyazis-MBP:~ niyazitoros$ pub global activate aqueduct
Package aqueduct is currently active at version 2.5.0+1.
Resolving dependencies... (16.1s)
+ analyzer 0.32.1
+ aqueduct 2.5.0+1
+ args 1.4.3
+ async 2.0.7
+ boolean_selector 1.0.3
+ charcode 1.1.1
+ collection 1.14.10
+ convert 2.0.1
+ crypto 2.0.5
+ csslib 0.14.4
+ dart2_constant 1.0.1+dart2
+ front_end 0.1.1
+ glob 1.1.6
+ html 0.13.3+1
+ http 0.11.3+16
+ http_multi_server 2.0.5
+ http_parser 3.1.2
+ io 0.3.2+1
+ js 0.6.1
+ json_rpc_2 2.0.8
+ kernel 0.3.1
+ logging 0.11.3+1
+ matcher 0.12.3
+ meta 1.1.5
+ mime 0.9.6+1
+ multi_server_socket 1.0.1
+ node_preamble 1.4.2
+ package_config 1.0.3
+ package_resolver 1.0.3
+ password_hash 1.0.0 (2.0.0-beta available)
+ path 1.6.1
+ plugin 0.2.0+2
+ pool 1.3.5
+ postgres 0.9.9 (1.0.0-beta.1 available)
+ pub_cache 0.1.1 (0.2.0 available)
+ pub_semver 1.4.1
+ safe_config 1.2.2 (2.0.0-beta.1 available)
+ shelf 0.7.3+1
+ shelf_packages_handler 1.0.3
+ shelf_static 0.2.7+1
+ shelf_web_socket 0.2.2+2
+ source_map_stack_trace 1.1.4
+ source_maps 0.10.5
+ source_span 1.4.0
+ stack_trace 1.9.2
+ stream_channel 1.6.7+1
+ string_scanner 1.0.2
+ term_glyph 1.0.0
+ test 0.12.42 (1.0.0 available)
+ typed_data 1.1.5
+ utf 0.9.0+4
+ vm_service_client 0.2.4+3
+ watcher 0.9.7+8
+ web_socket_channel 1.0.8
+ yaml 2.1.14
Precompiling executables... (6.8s)
Failed to precompile aqueduct:aqueduct:
.pub-cache/hosted/pub.dartlang.org/aqueduct-2.5.0+1/lib/src/commands/db.dart:203:21: Error: The function expression type '(dart.core::int, dart.core::int) → dart.core::int' isn't of expected type '(dynamic, dynamic) → dart.core::int'.
Change the type of the function expression or the context in which it is used.
    sortedKeys.sort((int a, int b) => a.compareTo(b));
                    ^
.pub-cache/hosted/pub.dartlang.org/aqueduct-2.5.0+1/lib/src/http/documentable.dart:105:14: Error: A value of type '(#lib1::APIPath) → dart.core::String' can't be assigned to a variable of type '(dynamic) → dynamic'.
Try changing the type of the left hand side, or casting the right hand side to '(dynamic) → dynamic'.
        key: (APIPath k) => k.path, value: (APIPath v) => v.asMap());
             ^
.pub-cache/hosted/pub.dartlang.org/aqueduct-2.5.0+1/lib/src/http/documentable.dart:105:44: Error: A value of type '(#lib1::APIPath) → dart.core::Map<dart.core::String, dynamic>' can't be assigned to a variable of type '(dynamic) → dynamic'.
Try changing the type of the left hand side, or casting the right hand side to '(dynamic) → dynamic'.
        key: (APIPath k) => k.path, value: (APIPath v) => v.asMap());
                                           ^
.pub-cache/hosted/pub.dartlang.org/aqueduct-2.5.0+1/lib/src/http/documentable.dart:298:16: Error: A value of type '(#lib1::APISecurityScope) → dart.core::String' can't be assigned to a variable of type '(dynamic) → dynamic'.
Try changing the type of the left hand side, or casting the right hand side to '(dynamic) → dynamic'.
          key: (APISecurityScope k) => k.name,
               ^
.pub-cache/hosted/pub.dartlang.org/aqueduct-2.5.0+1/lib/src/http/documentable.dart:299:18: Error: A value of type '(#lib1::APISecurityScope) → dart.core::String' can't be assigned to a variable of type '(dynamic) → dynamic'.
Try changing the type of the left hand side, or casting the right hand side to '(dynamic) → dynamic'.
          value: (APISecurityScope v) => v.description);
                 ^
.pub-cache/hosted/pub.dartlang.org/aqueduct-2.5.0+1/lib/src/http/documentable.dart:386:14: Error: A value of type '(#lib1::APIResponse) → dart.core::String' can't be assigned to a variable of type '(dynamic) → dynamic'.
Try changing the type of the left hand side, or casting the right hand side to '(dynamic) → dynamic'.
        key: (APIResponse k) => k.key, value: (APIResponse v) => v.asMap());
             ^
.pub-cache/hosted/pub.dartlang.org/aqueduct-2.5.0+1/lib/src/http/documentable.dart:386:47: Error: A value of type '(#lib1::APIResponse) → dart.core::Map<dart.core::String, dynamic>' can't be assigned to a variable of type '(dynamic) → dynamic'.
Try changing the type of the left hand side, or casting the right hand side to '(dynamic) → dynamic'.
        key: (APIResponse k) => k.key, value: (APIResponse v) => v.asMap());
                                              ^
.pub-cache/hosted/pub.dartlang.org/aqueduct-2.5.0+1/lib/src/db/managed/validate.dart:141:34: Error: The function expression type '(#lib1::ValidateOperation, #lib2::ManagedAttributeDescription, dart.core::Comparable<dynamic>, dart.core::List<dart.core::String>) → dart.core::bool' isn't of expected type '(#lib1::ValidateOperation, #lib2::ManagedAttributeDescription, dynamic, dart.core::List<dart.core::String>) → dart.core::bool'.
Change the type of the function expression or the context in which it is used.
      _expressionValidations.add((ValidateOperation operation,
                                 ^
.pub-cache/hosted/pub.dartlang.org/aqueduct-2.5.0+1/lib/src/db/managed/validate.dart:156:34: Error: The function expression type '(#lib1::ValidateOperation, #lib2::ManagedAttributeDescription, dart.core::Comparable<dynamic>, dart.core::List<dart.core::String>) → dart.core::bool' isn't of expected type '(#lib1::ValidateOperation, #lib2::ManagedAttributeDescription, dynamic, dart.core::List<dart.core::String>) → dart.core::bool'.
Change the type of the function expression or the context in which it is used.
      _expressionValidations.add((ValidateOperation operation,
                                 ^
.pub-cache/hosted/pub.dartlang.org/aqueduct-2.5.0+1/lib/src/db/managed/validate.dart:171:34: Error: The function expression type '(#lib1::ValidateOperation, #lib2::ManagedAttributeDescription, dart.core::Comparable<dynamic>, dart.core::List<dart.core::String>) → dart.core::bool' isn't of expected type '(#lib1::ValidateOperation, #lib2::ManagedAttributeDescription, dynamic, dart.core::List<dart.core::String>) → dart.core::bool'.
Change the type of the function expression or the context in which it is used.
      _expressionValidations.add((ValidateOperation operation,
                                 ^
Niyazis-MBP:~ niyazitoros$

**Comment by jhdoak** [comment]
@NTMS2017 - What is the output if you check your dart version with `dart --version`? If you're running Dart 2.0 you'll need to use Aqueduct 3.0, which is in prerelease now. You can find those steps [here](https://aqueduct.io/prerelease-3.0/docs/).

**Comment by joeconwaystk** [comment]
In addition to what Justin said, if you are on dart2-dev.64.1, there are a handful of blocking issues in the SDK. They should be ironed out by 65. Options are to install dart 1 and use aqueduct 2.5, downgrade to dev 63 with prerelease, or wait until 65 with prerelease. See #467 and #433

**Comment by NTMS2017** [comment]
Thanks all. My dart version is: Dart VM version: 1.24.3 (Wed Dec 13 23:26:59 2017) on "macos_x64"
It was and my mac openssl issue 77. First I couldn't install the stable dart version and while I try to fix I end up with corrupted path. This trigger the dart GitHub installation issue with my Mac openssl. Than I found that the actual problem was in home-brew. Didn't get all the dart packages. I manually clear everything solved the open ssl issue (macOS high Sierra 10.13.5) than I clean install the home-brew. After that I install the dart stable version and the dartium. I install the Dart dev version as well. Dart Stable is active one. Than I install the Aqueduct and and make my first rest api. Aqueduct is magnificent. So the issue is solved. Thank you very much. I followed and red the links that you provided. Before I post this, where I can get a info about aqueduct? Like I have server that runs the on VmWare. For security reason what is minimum configuration to run aqueduct server? Can I install in windows, ubuntu, Mac etc. And which one is more secure? At least where I can get this kind information. Sorry but I couldn't read all the aqueduct documentation. While wheel is running I need to work on my Flutter project and I choose the aqueduct as my backend framework. Thanks a lot.

**Comment by joeconwaystk** [comment]
Everything you need is at https://aqueduct.io/docs/. I'd recommend hosting an Aqueduct application behind a reverse proxy (Nginx, provider load balancers, etc.). Yes, you can install to any of those platforms - try a platform like Heroku.
