### ISSUE TITLE
IsolateSpawnException:

### ISSUE THREAD

**Issue by Algomoney** [stablekernel/aqueduct#477]
$ aqueduct serve
-- Aqueduct CLI Version: 3.0.0-beta.1
-- Aqueduct project version: 3.0.0-beta.1
-- Preparing...
*** Uncaught error
    IsolateSpawnException: Unable to spawn isolate: file:///Users/user/.pub-cache/hosted/pub.dartlang.org/path-1.6.0/lib/src/path_set.dart:76:32: Error: The method 'retype' isn't defined for the class 'dart.core::Set<dart.core::String>'.
Try correcting the name to the name of an existing method, or defining a method named 'retype'.
  Set<T> retype<T>() => _inner.retype<T>();
                               ^
  **** Stacktrace
  * #0      Isolate.spawnUri (dart:isolate/runtime/libisolate_patch.dart:450:14)
  * <asynchronous suspension>
  * #1      IsolateExecutor.execute (package:isolate_executor/src/executor.dart:59:23)
  * <asynchronous suspension>
  * #2      IsolateExecutor.executeWithType (package:isolate_executor/src/executor.dart:95:21)
  * <asynchronous suspension>
  * #3      CLIServer.deriveApplicationLibraryDetails (package:aqueduct/src/cli/commands/serve.dart:170:40)
  * <asynchronous suspension>
  * #4      CLIServer.prepare (package:aqueduct/src/cli/commands/serve.dart:190:32)
  * <asynchronous suspension>
  * #5      CLIServer.handle (package:aqueduct/src/cli/commands/serve.dart:78:11)
  * <asynchronous suspension>
  * #6      CLICommand.process (package:aqueduct/src/cli/command.dart:156:20)
  * <asynchronous suspension>
  * #7      CLICommand.process (package:aqueduct/src/cli/command.dart:132:48)
  * <asynchronous suspension>
  * #8      main (file:///Users/user/Desktop/Development/Dart/aqueduct_projects/aqueduct/aqueduct/bin/aqueduct.dart:9:27)
  * <asynchronous suspension>
  * #9      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
  * #10     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

**Comment by joeconwaystk** [comment]
Run ‘pub upgrade’, looks like your path package version is not compatible with dart 2. 

Additionally, Dart 2 support is in progress. Dev builds 64 and 65 have blocking issues for aqueduct.

**Comment by Algomoney** [comment]
Thanks for the feedback.  'pub upgrade' worked.  I'm new to Aqueduct so I figured I might as well learn the latest version even if it's not production ready.

**Comment by joeconwaystk** [comment]
👍
