### ISSUE TITLE
How can I connect aqueduct to local network socket instead of DB and return data to webapi

### ISSUE THREAD

**Issue by NTMS2017** [stablekernel/aqueduct#479]
I have a Flutter mobile app, thats connect to aqueduct web api to get data. Normally we will connect from aqueduct to db. But ı need to connect local network socket and not local network db. How can I connect aqueduct to local network socket instead of DB and return data to webapi?

**Comment by joeconwaystk** [comment]
Closing this as it looks like it was answered by https://stackoverflow.com/questions/51130494/how-to-return-response-ok-with-socket-data
