### ISSUE TITLE
Help: How to deploy and secure Aqueduct Web Api on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by NTMS2017** [stablekernel/aqueduct#488]
Hi,
I am using IntelliJ, and I just finished my Aqueduct Web API Project. I have an Ubuntu 18.04 LTS. How can I deploy and run Aqueduct web API in Ubuntu? And how can I secure my web API static files (bin and lib folder)? 

Any help, info or suggestion much appreciated.

**Comment by joeconwaystk** [comment]
https://aqueduct.io/docs/deploy/overview/
