### ISSUE TITLE
Can i use aqueduct 3.0 in production?

### ISSUE THREAD

**Issue by dviluk** [stablekernel/aqueduct#491]
Hi joe!
I recently started playing with flutter and i want to build a REST API with dart 2 . I was wondering if I could use this in production (aqueduct 3.0). 

I really liked this framework.  Looks powerful and easy to use.

**Comment by joeconwaystk** [comment]
Not yet. A beta will be published to pub.dartlang.org when Dart 2 fully supports Aqueduct 3, and vice versa.

**Comment by NTMS2017** [comment]
I install aqueduct 3.0.0-beta.1 and Dart VM version: 2.0.0-dev.68.0. So how can switch to aqueduct 2.5

**Comment by joeconwaystk** [comment]
3.0 has been deployed to beta channel on pub, and there are no further breaking changes planned before release, and dart 2 integration is complete.
