### ISSUE TITLE
 Ubuntu 18.04 auto update got this error

### ISSUE THREAD

**Issue by NTMS2017** [stablekernel/aqueduct#515]
After auto update Ubuntu 18.04 Desktop got this error

dependencies:
  #aqueduct: ^3.0.0-beta.1
  aqueduct:
    git:
      url: git@github.com:stablekernel/aqueduct.git
      ref: "3.0"

capital@capital-virtual-machine:~$ dart --version
Dart VM version: 2.0.0-dev.68.0 (Unknown timestamp) on "linux_x64"
capital@capital-virtual-machine:~$ aqueduct --version
aqueduct: command not found
capital@capital-virtual-machine:~$ pub global activate aqueduct
Package aqueduct is currently active at path "/home/capital/aqueduct/aqueduct".
Resolving dependencies... (13.9s)
+ analyzer 0.32.4
+ aqueduct 2.5.0+1 (3.0.0-beta.2 available)
+ args 1.4.4
+ async 2.0.8
+ boolean_selector 1.0.4
+ charcode 1.1.2
+ collection 1.14.11
+ convert 2.0.2
+ crypto 2.0.6
+ csslib 0.14.4+1
+ dart2_constant 1.0.1+dart2
+ front_end 0.1.4
+ glob 1.1.7
+ html 0.13.3+2
+ http 0.11.3+17
+ http_multi_server 2.0.5
+ http_parser 3.1.3
+ io 0.3.3
+ js 0.6.1+1
+ json_rpc_2 2.0.9
+ kernel 0.3.4
+ logging 0.11.3+2
+ matcher 0.12.3+1 (0.12.4 available)
+ meta 1.1.6
+ mime 0.9.6+2
+ multi_server_socket 1.0.2
+ node_preamble 1.4.4
+ package_config 1.0.5
+ package_resolver 1.0.4
+ password_hash 1.0.0 (2.0.0-beta available)
+ path 1.6.2
+ plugin 0.2.0+3
+ pool 1.3.6
+ postgres 0.9.9 (1.0.0-beta.1 available)
+ pub_cache 0.1.1 (0.2.1 available)
+ pub_semver 1.4.2
+ safe_config 1.2.2 (2.0.0-beta.1 available)
+ shelf 0.7.3+3
+ shelf_packages_handler 1.0.4
+ shelf_static 0.2.8
+ shelf_web_socket 0.2.2+3
+ source_map_stack_trace 1.1.5
+ source_maps 0.10.7
+ source_span 1.4.1
+ stack_trace 1.9.3
+ stream_channel 1.6.8
+ string_scanner 1.0.3
+ term_glyph 1.0.1
+ test 0.12.42 (1.3.0 available)
+ typed_data 1.1.6
+ utf 0.9.0+5
+ vm_service_client 0.2.6
+ watcher 0.9.7+10
+ web_socket_channel 1.0.9
+ yaml 2.1.15
Downloading logging 0.11.3+2...
Downloading yaml 2.1.15...
Downloading source_span 1.4.1...
Downloading path 1.6.2...
Downloading crypto 2.0.6...
Downloading string_scanner 1.0.3...
Downloading convert 2.0.2...
Downloading typed_data 1.1.6...
Downloading matcher 0.12.3+1...
Downloading term_glyph 1.0.1...
Downloading source_map_stack_trace 1.1.5...
Downloading meta 1.1.6...
Downloading multi_server_socket 1.0.2...
Downloading js 0.6.1+1...
Downloading stack_trace 1.9.3...
Downloading shelf_static 0.2.8...
Downloading args 1.4.4...
Downloading shelf_packages_handler 1.0.4...
Downloading package_resolver 1.0.4...
Downloading io 0.3.3...
Downloading boolean_selector 1.0.4...
Downloading source_maps 0.10.7...
Downloading shelf_web_socket 0.2.2+3...
Downloading http_parser 3.1.3...
Downloading node_preamble 1.4.4...
Downloading vm_service_client 0.2.6...
Downloading shelf 0.7.3+3...
Downloading async 2.0.8...
Downloading pool 1.3.6...
Downloading package_config 1.0.5...
Downloading stream_channel 1.6.8...
Downloading json_rpc_2 2.0.9...
Downloading web_socket_channel 1.0.9...
Downloading mime 0.9.6+2...
Downloading glob 1.1.7...
Downloading collection 1.14.11...
Downloading pub_semver 1.4.2...
Downloading analyzer 0.32.4...
Downloading kernel 0.3.4...
Downloading front_end 0.1.4...
Downloading plugin 0.2.0+3...
Downloading watcher 0.9.7+10...
Downloading html 0.13.3+2...
Downloading utf 0.9.0+5...
Downloading csslib 0.14.4+1...
Precompiling executables... (16.0s)
Failed to precompile aqueduct:aqueduct:
.pub-cache/hosted/pub.dartlang.org/aqueduct-2.5.0+1/lib/src/commands/db.dart:203:21: Error: The function expression type '(dart.core::int, dart.core::int) → dart.core::int' isn't of expected type '(dynamic, dynamic) → dart.core::int'.
Change the type of the function expression or the context in which it is used.
    sortedKeys.sort((int a, int b) => a.compareTo(b));
                    ^
.pub-cache/hosted/pub.dartlang.org/aqueduct-2.5.0+1/lib/src/http/documentable.dart:105:14: Error: The argument type '(#lib1::APIPath) → dart.core::String' can't be assigned to the parameter type '(dynamic) → dynamic'.
Try changing the type of the parameter, or casting the argument to '(dynamic) → dynamic'.
        key: (APIPath k) => k.path, value: (APIPath v) => v.asMap());
             ^
.pub-cache/hosted/pub.dartlang.org/aqueduct-2.5.0+1/lib/src/http/documentable.dart:105:44: Error: The argument type '(#lib1::APIPath) → dart.core::Map<dart.core::String, dynamic>' can't be assigned to the parameter type '(dynamic) → dynamic'.
Try changing the type of the parameter, or casting the argument to '(dynamic) → dynamic'.
        key: (APIPath k) => k.path, value: (APIPath v) => v.asMap());
                                           ^
.pub-cache/hosted/pub.dartlang.org/aqueduct-2.5.0+1/lib/src/http/documentable.dart:298:16: Error: The argument type '(#lib1::APISecurityScope) → dart.core::String' can't be assigned to the parameter type '(dynamic) → dynamic'.
Try changing the type of the parameter, or casting the argument to '(dynamic) → dynamic'.
          key: (APISecurityScope k) => k.name,
               ^
.pub-cache/hosted/pub.dartlang.org/aqueduct-2.5.0+1/lib/src/http/documentable.dart:299:18: Error: The argument type '(#lib1::APISecurityScope) → dart.core::String' can't be assigned to the parameter type '(dynamic) → dynamic'.
Try changing the type of the parameter, or casting the argument to '(dynamic) → dynamic'.
          value: (APISecurityScope v) => v.description);
                 ^
.pub-cache/hosted/pub.dartlang.org/aqueduct-2.5.0+1/lib/src/http/documentable.dart:386:14: Error: The argument type '(#lib1::APIResponse) → dart.core::String' can't be assigned to the parameter type '(dynamic) → dynamic'.
Try changing the type of the parameter, or casting the argument to '(dynamic) → dynamic'.
        key: (APIResponse k) => k.key, value: (APIResponse v) => v.asMap());
             ^
.pub-cache/hosted/pub.dartlang.org/aqueduct-2.5.0+1/lib/src/http/documentable.dart:386:47: Error: The argument type '(#lib1::APIResponse) → dart.core::Map<dart.core::String, dynamic>' can't be assigned to the parameter type '(dynamic) → dynamic'.
Try changing the type of the parameter, or casting the argument to '(dynamic) → dynamic'.
        key: (APIResponse k) => k.key, value: (APIResponse v) => v.asMap());
                                              ^
.pub-cache/hosted/pub.dartlang.org/aqueduct-2.5.0+1/lib/src/db/managed/validate.dart:141:34: Error: The function expression type '(#lib1::ValidateOperation, #lib2::ManagedAttributeDescription, dart.core::Comparable<dynamic>, dart.core::List<dart.core::String>) → dart.core::bool' isn't of expected type '(#lib1::ValidateOperation, #lib2::ManagedAttributeDescription, dynamic, dart.core::List<dart.core::String>) → dart.core::bool'.
Change the type of the function expression or the context in which it is used.
      _expressionValidations.add((ValidateOperation operation,
                                 ^
.pub-cache/hosted/pub.dartlang.org/aqueduct-2.5.0+1/lib/src/db/managed/validate.dart:156:34: Error: The function expression type '(#lib1::ValidateOperation, #lib2::ManagedAttributeDescription, dart.core::Comparable<dynamic>, dart.core::List<dart.core::String>) → dart.core::bool' isn't of expected type '(#lib1::ValidateOperation, #lib2::ManagedAttributeDescription, dynamic, dart.core::List<dart.core::String>) → dart.core::bool'.
Change the type of the function expression or the context in which it is used.
      _expressionValidations.add((ValidateOperation operation,
                                 ^
.pub-cache/hosted/pub.dartlang.org/aqueduct-2.5.0+1/lib/src/db/managed/validate.dart:171:34: Error: The function expression type '(#lib1::ValidateOperation, #lib2::ManagedAttributeDescription, dart.core::Comparable<dynamic>, dart.core::List<dart.core::String>) → dart.core::bool' isn't of expected type '(#lib1::ValidateOperation, #lib2::ManagedAttributeDescription, dynamic, dart.core::List<dart.core::String>) → dart.core::bool'.
Change the type of the function expression or the context in which it is used.
      _expressionValidations.add((ValidateOperation operation,
                                 ^

**Comment by joeconwaystk** [comment]
The last error shows that your tripledes library hasn’t been updated for dart 2

**Comment by NTMS2017** [comment]
joeconwaystk, When I update dart Dart VM version: 2.0.0-dev.69.4 then aqueduct stops working.  I install a clean another linux which is ubuntu16.04 and get similar problem not using even any plugin. The aqueduct first I install and configure in Ubuntu 18.04 was working. I dont understand why this happend. Which version linux should I have to use it? And which version Dart should I install?
