### ISSUE TITLE
Dead Code Warrning on router

### ISSUE THREAD

**Issue by NTMS2017** [stablekernel/aqueduct#517]
**I get dead code on this:**       
router.route('/n@y1zit@ros0c1pr0s/*').link(() {
       return new HeroesController();
       //..contentType = ContentType.TEXT;
     });

**Note:** this (  /n@y1zit@ros0c1pr0s  ) acting like ( /example )  and  (  /*   )  acting like (  [:id]  )

**This is controller:**

import 'package:aqueduct/aqueduct.dart';
import 'package:heroes/heroes.dart';
import 'package:heroes/util/GetPrivate.dart';
import 'package:heroes/util/SetPrivate.dart';

class HeroesController extends Controller {

  final heroes = [
    {'id': 11, 'name': 'ComapnyName'},
  ];

  @override
  Future<RequestOrResponse> handle(Request request) async {
    try {
      String _xRequestValue = "";
      String reply = "";
      String _xResult = "";
      var encryptedData;

      if (request.path.remainingPath != null) {
        _xRequestValue = request.path.remainingPath;
        print("request: $_xRequestValue");
        var decryptedData = await getPrivate(_xRequestValue);
        print("decryptedData: $decryptedData");

        var socket = await Socket.connect('127.0.0.1', 1024);
        socket.write('$decryptedData\r\n');

        await for (var data in socket) {
          reply = new String.fromCharCodes(data).trim();
          print("reply: $reply");

          encryptedData = await setPrivate(reply);
          socket.close();
          socket.destroy();
          return new Response.ok("$encryptedData")
            ..contentType = ContentType.TEXT;
        } // await socket

        socket.handleError((data) {
          print("error: $data");
          return new Response.badRequest();
        });

        return new Response.badRequest(
            body: {"CompanyName": "Temporary service is not provided"});

      }
    } catch (e) {
      print(e.toString());
      return new Response.badRequest(
          body: {"CompanyName": "Temporary service is not provided"});
    }
  }
}

**Comment by joeconwaystk** [comment]
Please only file issues related to Aqueduct, not your project.
