### ISSUE TITLE
[Feature Request] Allow use @route annotation to define sub-route in controller

### ISSUE THREAD

**Issue by lyquocnam** [stablekernel/aqueduct#531]
Currently we must define 2 times to map sub route. This feature will help easier to do.
```dart
router
  .route("/cities")
  .link(() => new CityController());

router
  .route("/cities/[:name]")
  .link(() => new CityController());
```
with `@route` annotation:

```dart
router
  .route("/cities")
  .link(() => new CityController());

//...
// Controller
  @Operation.get("id")
  @Route(":id")
  Future<Response> getById(@Bind.path('id') int id) async {
    final query = Query<City>(context)
      ..where((p) => p.id).equalTo(id);
    
    final data = await query.fetchOne();

    return Response.ok(data);
  }
```

**Comment by joeconwaystk** [comment]
You don’t need to define it twice. The route ‘/cities/[:id]’ captures both /cities and /cities/:id.

The ‘id’ in @Operation is already doing what you are intended @Route to do. 

You can delete the route for /cities, and just add a new operation method with @Operation.get() annotation. Then, you will have 2 operation methods for GET requests - one when the path variables id is present and one when it is not.

**Comment by lyquocnam** [comment]
please see the demo project, if i remove sub-route, it will 404.
```dart
  router.route('/api/provinces')
    .link(() => ProvinceController(context));

  // router.route('/api/provinces/:id')
  //   .link(() => ProvinceController(context));
```
![image](https://user-images.githubusercontent.com/8347826/43835156-0dcf4ed2-9b3b-11e8-87f9-421dd9c7e175.png)

https://github.com/lyquocnam/aqueduct-demo

**Comment by joeconwaystk** [comment]
You need the route “/api/provinces/[:id]”.

The [] mean that segment is optional. So both with and without the id match.

**Comment by lyquocnam** [comment]
it worked, sorry about that
