### ISSUE TITLE
Can aqueduct server be run on a flutter app?

### ISSUE THREAD

**Issue by srix55** [stablekernel/aqueduct#533]
I need to serve clients over wireless lan where in a flutter app can act as a lightweight webserver. Can Aqueduct run in flutter?

**Comment by joeconwaystk** [comment]
No, there are some libraries/packages that Aqueduct imports and Flutter doesn't allow. I think Aqueduct would be overkill for this use case, and the low-level `HttpServer` from `dart:io` is a better candidate.

**Comment by PierBover** [comment]
Would be great if you specified this on the website.
