### ISSUE TITLE
Using Aqueduct in China

### ISSUE THREAD

**Issue by rhymelph** [stablekernel/aqueduct#540]
I want to create a new project use "aqueduct create app" command
What should I do?Thank!!

RhymedeMacBook-Pro:shelf_app rhyme$ aqueduct create app
-- Aqueduct CLI Version: 3.0.0
*** Uncaught error
    NoSuchMethodError: The getter 'location' was called on null.
Receiver: null
Tried calling: location
  **** Stacktrace
  * #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
  * #1      _CLITemplateCreator&CLICommand&CLIAqueductGlobal.templateDirectory (package:aqueduct/src/cli/commands/create.dart:347:41)
  * #2      _CLITemplateCreator&CLICommand&CLIAqueductGlobal.getTemplateLocation (package:aqueduct/src/cli/commands/create.dart:351:12)
  * #3      CLITemplateCreator.handle (package:aqueduct/src/cli/commands/create.dart:51:27)
  * <asynchronous suspension>
  * #4      CLICommand.process (package:aqueduct/src/cli/command.dart:158:20)
  * <asynchronous suspension>
  * #5      CLICommand.process (package:aqueduct/src/cli/command.dart:134:12)
  * <asynchronous suspension>
  * #6      main (file:///Users/rhyme/.pub-cache/hosted/pub.flutter-io.cn/aqueduct-3.0.0/bin/aqueduct.dart:9:27)
  * <asynchronous suspension>
  * #7      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
  * #8      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
  ****

**Comment by joeconwaystk** [comment]
How did you install `aqueduct`?

**Comment by rhymelph** [comment]
@joeconwaystk  I used "pub global activate aqueduct" command install  aqueduct ,but I not got any error.

**Comment by joeconwaystk** [comment]
This error is saying the templates that are part of the aqueduct package can’t be found, and that is because it can’t locate the global package install in your pub cache. It’s pointing at a sub directory that looks flutter related - how did you install dart?

**Comment by rhymelph** [comment]
oh,I know what to do!Thank！

**Comment by rhymelph** [comment]
@joeconwaystk  I try to all method to Solve it.but the error having

**Comment by rhymelph** [comment]
I try to install a new dart environment

**Comment by joeconwaystk** [comment]
Has this resolved the issue?

**Comment by rhymelph** [comment]
I don't how to resolve.

**Comment by joeconwaystk** [comment]
It looks like you may have a pub configuration issue. See this issue: https://github.com/dart-lang/pub/issues/1969

**Comment by rhymelph** [comment]
It is normal when I use other 'pub' commands.
And PUB_HOSTED_URL was using.

**Comment by joeconwaystk** [comment]
The error is coming from package:pub_cache and is saying that the aqueduct directory in your pub cache can’t be found. That directory contains the templates for new projects. 

What is the purpose of a different PUB_HOSTED_URL? Can you avoid that?

**Comment by rhymelph** [comment]
My aqueduct directory in  /Users/rhyme/.pub-cache/hosted/pub.flutter-io.cn/aqueduct-3.0.1
Why saying can't be found?

**Comment by joeconwaystk** [comment]
I filed an issue with the dependent package that should explain it better: https://github.com/dart-lang/pub_cache/issues/34.  I'm changing the title of this issue to 'Using Aqueduct in China'. Once the issue gets resolved in `package:pub_cache`, I will update this issue. You can then run `pub global activate aqueduct` again and it will fix the problem.

**Comment by rhymelph** [comment]
All right, thank you

**Comment by joeconwaystk** [comment]
@rhymelph This has been merged - reactivate package with `pub global activate aqueduct` and you should be good to go. Will close when I hear back.

**Comment by youncccat** [comment]
@joeconwaystk I glance your conversation with @rhymelph quickly. This problem looks like It's been fixed. But I get the same problem when I try to exec `aqueduct create project_name`, I thought to cause this problem might is that I set the `PUB_HOSTED_URL ` env variable. However, when I remove the mirror of Pub, then I try to exec `pub global activate aqueduct` again, Resolving dependencies has a timeout (28:59.9s) :(

**Comment by rhymelph** [comment]
@joeconwaystk  you can try to set `PUB_HOSTED_URL` = https://pub.dev  and keep enable visit the `Google`

**Comment by youncccat** [comment]
@rhymelph Thx, that's works for me 🎉
