### ISSUE TITLE
Heroku deployment tutorial out of date?

### ISSUE THREAD

**Issue by gardyna** [stablekernel/aqueduct#548]
I am trying to follow [the official tutorial][1] on how to deploy apps on Heroku
I am however getting the following error:

    remote: Precompiled aqueduct:aqueduct.
    remote: Precompiled test:test.
    remote: *** Running pub build
    remote: Building with "pub build"
    remote: Dart 2 has a new build system. Learn how to migrate from pub build and
    remote: pub serve: https://webdev.dartlang.org/dart-2
    remote:  !     Push rejected, failed to compile Dart app.

I can't seem to find any hints on what I can change to fix the error. 

  [1]: https://aqueduct.io/docs/deploy/deploy_heroku/

**Comment by joeconwaystk** [comment]
Hm. The Buildpack needs to be updated. It’s trying to run pub build because a web/ directory exists. Two temporary solutions before the fix:

1. Remove the web directory from your project, including from version control. 
2. Fork the Buildpack and remove the step to run pub build.

**Comment by gardyna** [comment]
thanks for the help! A bit of a silly mistake on my part.
