### ISSUE TITLE
Appending fetch() result lists to response

### ISSUE THREAD

**Issue by tobischw** [stablekernel/aqueduct#551]
Apologizes if this is in the wrong section or unrelated to direct issues with aqueduct.

I am trying to respond with JSON after a Postgres query:

```dart
final postQuery = Query<Post>(context);
final posts = await postQuery.fetch();

return Response.ok(posts);
```

This works perfectly fine. However, if I try the following:

```dart
final postQuery = Query<Post>(context);
final posts = await postQuery.fetch();

return Response.ok({ 'items': posts });
```
I receive this error message when sending request to server:

```
Converting object to an encodable object failed: Instance of 'Post' #0      _JsonStringifier.writeObject (dart:convert/json.dart:703:7)
#1      _JsonStringifier.writeList (dart:convert/json.dart:753:7)
#2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:735:7)
#3      _JsonStringifier.writeObject (dart:convert/json.dart:693:9)
#4      _JsonStringifier.writeMap (dart:convert/json.dart:786:7)
#5      _JsonStringifier.writeJsonValue (dart:convert/json.dart:741:21)
#6      _JsonStringifier.writeObject (dart:convert/json.dart:693:9)
#7      _JsonUtf8Stringifier.stringify (dart:convert/json.dart:975:17)
#8      JsonUtf8Encoder.convert (dart:convert/json.dart:401:26)
#9      _FusedConverter.convert (dart:convert/converter.dart:81:48)
#10     Codec.encode (dart:convert/codec.dart:25:32)
...
```
I've already tried making Post a serializable which did not work. I must be missing something.

Shouldn't it be possible to simply re-use the List provided by fetch and append it as a value to a key, or am I doing something wrong?

Thanks.

**Comment by joeconwaystk** [comment]
All managed objects are serializable. Maps are not. When a map is a body object, there is no additional behavior that occurs before it is encoded. It then has to be in an encodable format according to the built in JSON codec (primitives, maps and arrays); and a Post is not. 

Change the value of your map to posts.map((p) => p.asMap())).toList().

**Comment by RahmatJatnika** [comment]
that is not running in my program sir

**Comment by tobischw** [comment]
Wow, what a great summary of your problem.


________________________________
