### ISSUE TITLE
Allow `aqueduct db generate` command to support naming migration file

### ISSUE THREAD

**Issue by seenickcode** [stablekernel/aqueduct#554]
One should be able to run something like `aqueduct db generate <migration name>` or  `aqueduct db generate --name <migration name>` which would generate `<incremented num>_<migration name>.migration.dart`.

Related file: `https://github.com/stablekernel/aqueduct/blob/f2eac278579556ac57dbac3e620248044fcce71c/aqueduct/lib/src/cli/commands/db_generate.dart`

Thoughts, @joeconwaystk ?

**Comment by joeconwaystk** [comment]
Sounds reasonable to me. The input string should automatically be lowercased.

**Comment by seenickcode** [comment]
Great. What convention would folks prefer out of those two example options
I've cited?
