### ISSUE TITLE
How to allow aqueduct server to accept https connection

### ISSUE THREAD

**Issue by NTMS2017** [stablekernel/aqueduct#561]
I have install Aqueduct CLI version 3.0.1 on Ubuntu 18.04. I also install openssl 1.1.1-pre8. I run aqueduct serve ssl-key-path key.pem ssl-cert-path cert.pem and started to aqueduct server. But still accepts the http connection. 

How to allow aqueduct server to accept https connection?

**Comment by joeconwaystk** [comment]
Was this resolved via the Slack conversation?

**Comment by NTMS2017** [comment]
Yes it was, Thanks.
