### ISSUE TITLE
NoSQL support with Objectdb optional beta support! [enhancement]

### ISSUE THREAD

**Issue by LOG-TAG** [stablekernel/aqueduct#577]
It will be great if we get option get many other DB  types in beta version (at least to promote 100% Dart written DBs)
**[ObjectDB](https://pub.dartlang.org/packages/objectdb)** Persistent embedded document-oriented NoSQL database for Dart and Flutter.   So please consider as a future enhancement!

**Comment by elliott-maguire** [comment]
Why was this closed?

**Comment by AL1L** [comment]
Agreeing with @elliott-maguire, this should be reopened @LOG-TAG

**Comment by joeconwaystk** [comment]
I'm not sure why it was closed, but also can't you just import the objectdb package into your app?
