### ISSUE TITLE
Some document errors

### ISSUE THREAD

**Issue by jodinathan** [stablekernel/aqueduct#579]
I found some simple errors in documentation and the editing link is throwing 404.

URL: https://aqueduct.io/docs/http/resource_controller/
"For example, the following binds the header named 'X-API-Key' to the argument apiKey"
But the example binds to a path: 
```
Future<Response> getCityByName(@Bind.path('x-api-key') String apiKey) async {
}
```

URL: https://aqueduct.io/docs/http/controller/
```
final controllerA = Controller();
controller.link(() => Controller());
```
I think that controller.link should be controllerA.link

**Comment by joeconwaystk** [comment]
@anachlas can you confirm edit link now works? Looks good to me but can’t dig in

**Comment by anachlas** [comment]
Edit link now works

**Comment by anachlas** [comment]
But it makes the edits in the docs/source branch, so changes will only be reflected in the actual docs after a deploy.
