### ISSUE TITLE
Add docs for @Table

### ISSUE THREAD

**Issue by lieblb** [stablekernel/aqueduct#583]
There's no docs on `@Table`. In `Table`'s source code, the example in the comments gives `@Table(unique: const [#name, #email]);`, but it should really read `@Table(uniquePropertySet: [#name, #email])` or `@Table.unique([#name, #email])`.

**Comment by joeconwaystk** [comment]
:+1: Thanks for finding - you mean in addition to the API reference documentation being incorrect, there is also no documentation on aqueduct.io/docs/?

**Comment by lieblb** [comment]
Exactly.

**Comment by joeconwaystk** [comment]
- [x] aqueduct.io
- [ ] API reference
