### ISSUE TITLE
Wrong links in "Core Concept" part of the documentation

### ISSUE THREAD

**Issue by kalmykovanton** [stablekernel/aqueduct#610]
Hi, guys! Thanks for your work on Aqueduct project! I'm just noticed that links under "Queries and Data Models" and "Authorization" topics in "Core Concept" part of the documentation (https://aqueduct.io/docs/core_concepts) mixed up in places.

**Comment by joeconwaystk** [comment]
Thanks, you are right. It has been fixed on the source branch.
