### ISSUE TITLE
using db_and_auth template, can not register user - 401 connection refused

### ISSUE THREAD

**Issue by bartonhammond** [stablekernel/aqueduct#613]
**steps**:

1. `aqueduct create -t db_and_auth db_and_auth`
2. create db 'dart_test' with 'dart':'dart' userid:password
3. `aqueduct db generate`
4.  `aqueduct db upgrade --connect postgres://dart:dart@localhost:5432/dart_test`
5.  `aqueduct auth add-client --id com.local.test --secret mysecret  --connect postgres://dart:dart@localhost:5432/dart_test`
6.  `curl -X POST -v http://localhost:8888/register -H 'Content-Type: application/json' -d '{"username":"bob", "password":"password"}'`

**curl log**
```
curl -X POST -v http://localhost:8888/register -H 'Content-Type: application/json' -d '{"username":"bob", "password":"password"}'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8888 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8888 (#0)
> POST /register HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 41
> 
* upload completely sent off: 41 out of 41 bytes
< HTTP/1.1 401 Unauthorized
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< content-length: 0
< server: aqueduct/1
< 
* Connection #0 to host localhost left intact
```

**Result**: 

- user is not created
- _authclient is created

**Log**: 
```
[INFO] aqueduct: Server aqueduct/1 started.  
[INFO] aqueduct: Server aqueduct/2 started.  
[INFO] aqueduct: Server aqueduct/3 started.  
[INFO] aqueduct: Server aqueduct/4 started.  
Application started on port: 8888.
Use Ctrl-C (SIGINT) to stop running the application.
[INFO] aqueduct: POST /register 7ms 401  
```

**Attempt to fix**
change `channel.dart`:
```
    /* Create an account */
    router
        .route("/register")
        //    .link(() => Authorizer.basic(authServer))   ////////////comment out this line
        .link(() => RegisterController(context, authServer));
```
**Result** User gets created

Then tried `curl -v POST http://localhost:8888/auth/token -H 'Authorization: Basic Y29tLmhlcm9lcy50dXRvcmlhbDo=' -H 'Content-Type: application/x-www-formbob&password=password&grant_type=password'`

**Result**
```
curl -v POST http://localhost:8888/auth/token -H 'Authorization: Basic Y29tLmhlcm9lcy50dXRvcmlhbDo=' -H 'Content-Type: application/x-www-form-urlencoded' -d 'username=bob&password=password&grant_type=password'
* Rebuilt URL to: POST/
* Could not resolve host: POST
* Closing connection 0
curl: (6) Could not resolve host: POST
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8888 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8888 (#1)
> POST /auth/token HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Basic Y29tLmhlcm9lcy50dXRvcmlhbDo=
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 50
> 
* upload completely sent off: 50 out of 50 bytes
< HTTP/1.1 400 Bad Request
< content-type: application/json; charset=utf-8
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< content-length: 26
< server: aqueduct/1
< 
* Connection #1 to host localhost left intact
```

**Comment by joeconwaystk** [comment]
You need to include the basic Authorization header containing your client id and secret in the route `/register` in the same way you did for `/auth/token`.

**Comment by bartonhammond** [comment]
@joeconwaystk Thanks for reply.  

You said 

> in the same way you did for `/auth/token`

but I don't see that I referenced `client id` and `secret` anywhere except when running `aqueduct auth add-client --id com.local.test --secret mysecret --connect postgres://dart:dart@localhost:5432/dart_test`  

I'm following the instructions here: [https://aqueduct.io/docs/tut/oauth2/](https://aqueduct.io/docs/tut/oauth2/) and the provided curl command does not mention anything about `client id` and `secret` when POST to `/register`. 

I'd gladly update the docs if I understood what the curl command is supposed to look like.

**Comment by joeconwaystk** [comment]
Gotcha, I see how that is confusing. The tutorial isn't building the same application generated by the template. The tutorial is a simplified version of the template. There is an outstanding issue (#559) for better communicating the behavior of the templates. I'd be interested in suggestions for where this documentation should be (in the template itself? in a separate guide on aqueduct.io?).

The linked `Authorizer.basic()` is the component that requires a basic authorization header. The /register endpoint in the template creates a new user and grants & returns an authorized token for that new user.

**Comment by bartonhammond** [comment]
@joeconwaystk I think I am understanding better now.  Once I get this all working, I'll gladly create a PR to help w/ documentation, where ever the right docs are.

I understand **now** that I have to take the `client-id` and `secret` and Base64Encode them.  I see that in the docs where the Dart code is presented:

> // Note the trailing colon (:) after the clientID.
// A client identifier secret would follow this, but there is no secret, so it is the empty string.
final clientCredentials = Base64Encoder().convert("$clientID:".codeUnits);


The `Y29tLmhlcm9lcy50dXRvcmlhbDo` value used in the subsequent curl command `curl -X POST http://localhost:8888/auth/token -H 'Authorization: Basic Y29tLmhlcm9lcy50dXRvcmlhbDo=' -H 'Content-Type: application/x-www-form-urlencoded' -d 'username=bob&password=password&grant_type=password'`is from BaseEncoder on `com.heroes.tutorial:`.  The `:` is there to separate the `client-id` from the `secret` but since we don't have a `secret`, in this example, it's blank.  

I see that I can take `com.heroes.tutorial:` and use https://www.base64encode.org/ to encode it to `Y29tLmhlcm9lcy50dXRvcmlhbDo=` which is the value used in the tutorial.

With the template `db_and_auth`, the `README.md` said to perform this: `aqueduct auth add-client --id com.local.test \
    --secret mysecret \
    --connect postgres://user:password@localhost:5432/db_and_auth`.  

To get the Base64Encode value required for the `/register` path, I need to take `com.local.test:mysecret` and Base64Encode it at https://www.base64encode.org/ which gives me `Y29tLmxvY2FsLnRlc3Q6bXlzZWNyZXQ=`

Now I update the curl to this: `curl -X POST http://localhost:8888/register -H 'Authorization: Basic Y29tLmxvY2FsLnRlc3Q6bXlzZWNyZXQ=' -H 'Content-Type: application/x-www-form-urlencoded' -d 'username=barton&password=password&grant_type=password' -v` 

This fails (I am on Mac 10.14.2)
```
curl -X POST http://localhost:8888/register -H 'Authorization: Basic Y29tLmxvY2FsLnRlc3Q6bXlzZWNyZXQ=' -H 'Content-Type: application/x-www-form-urlencoded' -d 'username=barton&password=password&grant_type=password' -v
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8888 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8888 (#0)
> POST /register HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Basic Y29tLmxvY2FsLnRlc3Q6bXlzZWNyZXQ=
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 53
> 
* upload completely sent off: 53 out of 53 bytes
< HTTP/1.1 415 Unsupported Media Type
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< content-length: 0
< server: aqueduct/2
< 
* Connection #0 to host localhost left intact
```

**Comment by joeconwaystk** [comment]
The register endpoint takes JSON data (you also don't need to include the grant_type). The reason /auth/token takes form data is because the spec requires it, but everything else in Aqueduct defaults to JSON. 

You are correct about everything else. And perhaps the README.md for the projects generated by the template is the best place for this info.

**Comment by bartonhammond** [comment]
Ok, I updated my curl: `curl -X POST http://localhost:8888/register -H 'Authorization: Basic Y29tLmxvY2FsLnRlc3Q6bXlzZWNyZXQ=' -H 'Content-Type: application/json' -d '{"username":"barton", "password": "password"' -v`

But I still get error:
```
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8888 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8888 (#0)
> POST /register HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Basic Y29tLmxvY2FsLnRlc3Q6bXlzZWNyZXQ=
> Content-Type: application/json
> Content-Length: 44
> 
* upload completely sent off: 44 out of 44 bytes
< HTTP/1.1 400 Bad Request
< content-type: application/json; charset=utf-8
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< content-length: 47
< server: aqueduct/1
< 
* Connection #0 to host localhost left intact
{"error":"request entity could not be decoded"}```

The **Log** from Aqueduct:
```
[db_and_auth]$ aqueduct serve -n1
-- Aqueduct CLI Version: 3.1.0+1
-- Aqueduct project version: 3.1.0+1
-- Preparing...
-- Starting application 'db_and_auth/db_and_auth'
    Channel: DbAndAuthChannel
    Config: /Users/bartonhammond/projects/db_and_auth/config.yaml
    Port: 8888
[INFO] aqueduct: Server aqueduct/1 started.
[INFO] aqueduct: PostgreSQL connecting, dart@localhost:5432/dart_test.
[INFO] aqueduct: POST /register 137ms 400
```
Sorry, this is very confusing.

**Comment by joeconwaystk** [comment]
Your JSON is malformed. Also see the readme in this repo for a link to the slack channel

**Comment by bartonhammond** [comment]
I also added this `echo '--ipv4' >> ~/.curlrc` so I don't get connection refused.

Updated the curl: 'curl -X POST http://localhost:8888/register -H 'Authorization: Basic Y29tLmxvY2FsLnRlc3Q6bXlzZWNyZXQ=' -H 'Content-Type: application/json' -d '{"username":"barton", "password": "password"}' -v'

And got SUCCESS:

```
./user.sh 
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8888 (#0)
> POST /register HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Basic Y29tLmxvY2FsLnRlc3Q6bXlzZWNyZXQ=
> Content-Type: application/json
> Content-Length: 45
> 
* upload completely sent off: 45 out of 45 bytes
< HTTP/1.1 200 OK
< cache-control: no-store
< content-length: 188
< pragma: no-cache
< x-frame-options: SAMEORIGIN
< content-type: application/json; charset=utf-8
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< server: aqueduct/1
< 
* Connection #0 to host localhost left intact
{"id":2,"username":"barton","authorization":{"access_token":"7BU1eAFmsgvDyOEl4fbHLD0Mx6YIKodW","token_type":"bearer","expires_in":86399,"refresh_token":"gYNczFzWSMEFY0T2cZjUvqUON6EkT5cW"}}[db_and_auth]$ 
```

**Comment by bartonhammond** [comment]
I can now successfully hit these endpoints: `/register`, `/me`, `/users/[:id]` but I fail on `auth/token`.  

My curl: `curl -X POST http://localhost:8888/auth/token -H 'Authorization: Basic Y29tLmxvY2FsLnRlc3Q6bXlzZWNyZXQ=' -H 'Content-Type: application/x-www-form-urlencoded' -d 'username=marilyn&password=password&grant_type=password' -v`  

The result:  {"error":"invalid_grant"}
```
./getAuthToken.sh 
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8888 (#0)
> POST /auth/token HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Basic Y29tLmxvY2FsLnRlc3Q6bXlzZWNyZXQ=
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 54
> 
* upload completely sent off: 54 out of 54 bytes
< HTTP/1.1 400 Bad Request
< content-type: application/json; charset=utf-8
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< content-length: 25
< server: aqueduct/1
< 
* Connection #0 to host localhost left intact
{"error":"invalid_grant"}
```

**Comment by bartonhammond** [comment]
Got the `/auth/token` working, I needed to make sure the user was existing

`curl -X POST http://localhost:8888/auth/token -H 'Authorization: Basic Y29tLmxvY2FsLnRlc3Q6bXlzZWNyZXQ=' -H 'Content-Type: application/x-www-form-urlencoded' -d 'username=barton&password=password&grant_type=password' -v`

result: 

Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8888 (#0)
> POST /auth/token HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Basic Y29tLmxvY2FsLnRlc3Q6bXlzZWNyZXQ=
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 53
> 
* upload completely sent off: 53 out of 53 bytes
< HTTP/1.1 200 OK
< cache-control: no-store
< content-length: 143
< pragma: no-cache
< x-frame-options: SAMEORIGIN
< content-type: application/json; charset=utf-8
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< server: aqueduct/1
< 
* Connection #0 to host localhost left intact
{"access_token":"YQdzAEco5nx51XoAd1NP6TbyM0wpGcpB","token_type":"bearer","expires_in":86399,"refresh_token":"vYeekLgaMbUbGysNWqHXtGs82MTdhgWf"}

**Comment by mrleeT91** [comment]
im a newbie, did it have an example about scope in this tutorial ? ty
