### ISSUE TITLE
Docker instructions don't work

### ISSUE THREAD

**Issue by lukepighetti** [stablekernel/aqueduct#615]
Given

```
FROM google/dart

WORKDIR /app
ADD pubspec.* /app/
RUN pub get --no-precompile
ADD . /app/
RUN pub get --offline --no-precompile

WORKDIR /app
EXPOSE 80

ENTRYPOINT ["pub", "run", "aqueduct:aqueduct", "serve", "--port", "80"]
```

Build with `docker build . -t hn-aqueduct:v2`

Run with `docker run hn-aqueduct:v2 -d -p 8888:80`

Error

```
-- Aqueduct CLI Version: 3.1.0+1
*** No pubspec.lock file. Run `pub get`.
```

Run with `docker run hn-aqueduct:v2`, runs but cannot connect (expected)

Run with `docker run hn-aqueduct:v2 -p 8888:80`

Error
```
-- Aqueduct CLI Version: 3.1.0+1
-- Aqueduct project version: 3.1.0+1
-- Preparing...
*** Application failed to start.
*** Uncaught error
    FormatException: Invalid radix-10 number
8888:80
  **** Stacktrace
  * #0      int._throwFormatException (dart:core/runtime/libintegers_patch.dart:130:5)
  * #1      int._parse (dart:core/runtime/libintegers_patch.dart:104:14)
  * #2      int.parse (dart:core/runtime/libintegers_patch.dart:61:12)
```

**Comment by joeconwaystk** [comment]
That looks like `-p 8888:80` is being forwarded to the command line arguments of the aqueduct executable and the application is trying to parse this string as an integer port?

**Comment by lukepighetti** [comment]
That's what it seems like, and I have no idea how that is possible.

**Comment by joeconwaystk** [comment]
The location in the docker command matters. Try `docker run -p 8888:80 hn-aqueduct:v2`?

**Comment by lukepighetti** [comment]
Don't have bandwidth to give it a shot but I am 99% sure that is the issue. I will close. Thanks!
