### ISSUE TITLE
Sample code does not work as described for request body bindings

### ISSUE THREAD

**Issue by chstrong** [stablekernel/aqueduct#624]
https://aqueduct.io/docs/http/resource_controller/#http-request-body-bindings

Answer I got back from @zoechi: Dart doesn't do type coersion.

This example doesn't work anymore. 
`class City extends Serializable {
  int id;
  String name;

  @override
  void readFromMap(Map<String, dynamic> map) {
    id = map['id'];
    name = map['name'];
  }

  @override
  Map<String, dynamic> asMap() {
    return {
      'id': id,
      'name': name
    }
  }
}`

I guess you could change it to this. And ";" is missing in the return statement for asMap().
`class City extends Serializable {
  int id;
  String name;

  @override
  void readFromMap(Map<String, dynamic> map) {
    id = map['id'] as int; // this had to be adjusted
    name = map['name'] as String; // this had to be adjusted
  }

  @override
  Map<String, dynamic> asMap() {
    return {
      'id': id,
      'name': name
    }; // this was missing
  }
}`

And btw. Aqueduct is great!!!

**Comment by joeconwaystk** [comment]
Thanks - this is documentation error. You should probably type-check the values when you implement Serializable (ManagedObject does this automatically). You can't enforce that ['id'] is an int, for example, because the input is external.

**Comment by chstrong** [comment]
Hi Joe, ok understood. I'm using MySQL. Hence not using ManagedObject. Following manual type assignment worked for me which is sufficient for the moment:

`@override
void readFromMap(Map<String, dynamic> map) {
id = map['id'] as int; // this had to be adjusted
name = map['name'] as String; // this had to be adjusted
}`

Here a complete example:

`  @override
  void readFromMap(Map<String, dynamic> map) {
    id = map['id'] as int;
    name = map['name'] as String;
    startdate = DateTime.parse(map["startdate"].toString());
    owner = map["owner"] as String;
    type = map["type"] as String;
    is_valid = map["is_valid"] as int;
    created_by = map["created_by"] as String;
    update_date = DateTime.parse(map["update_date"].toString());
    campaign_identifier = map["campaign_identifier"] as int;
    updated_by = map["updated_by"] as String;
  }`

Not that familiar with dart yet, but starting to find my ways. If there is a more efficient way, let me know. Otherwise I'll might look into your source  of ManagedObject later.

**Comment by joeconwaystk** [comment]
This OK to close?

**Comment by chstrong** [comment]
Yes, fine with me.
