### ISSUE TITLE
how can I make a stored procedure via aqueduct?

### ISSUE THREAD

**Issue by rullyalves** [stablekernel/aqueduct#626]
Is there any way to call a stored procedure in aqueduct ?

**Comment by joeconwaystk** [comment]
Yes, you can execute arbitrary SQL with a managed context or a database connection that you instantiate yourself. For the latter, see `package:postgres`. For the former:

```dart
ManagedContext ctx = ...;
await ctx.persistentStore.execute("SELECT now()");
```
