### ISSUE TITLE
QueryExpression.equalTo() doesn't match backslashes as literals

### ISSUE THREAD

**Issue by pschiffmann** [stablekernel/aqueduct#630]
The handling of backslashes in string properties is inconsistent between insert and fetch operations. For inserts, backslashes are treated literally, but in fetch, backslashes are treated as escape sequences.

The following test case fails, which was very unexpected for me. (The test case uses the [table definition from your rest_postgres example](https://github.com/stablekernel/aqueduct_examples/blob/master/rest_postgres/lib/model/model.dart)).
```dart
test('can find object with backslash-escaped value', () async {
  final name = r'my\value';
  await Query.insertObject(app.context, Model()..name = name);
  final model = await (Query<Model>(app.context)
        ..where((m) => m.name).equalTo(name))
      .fetchOne();
  expect(model, isNotNull);
});
```

I assume the reason for this behaviour is that Postgres recognizes these escapes internally. Section 4.1.2.2. of [chapter 11](https://www.postgresql.org/docs/11/sql-syntax-lexical.html) of the Postgres documentation states:
> Any other character following a backslash is taken literally.

Which means that this test case fails as well:
```dart
test('backslashes are matched as literals', () async {
  await Query.insertObject(app.context, Model()..name = 'hello world');
  final model = await (Query<Model>(app.context)
        ..where((m) => m.name).equalTo(r'h\e\l\l\o\ \w\or\l\d'))
      .fetchOne();
  expect(model, isNull);
});
```

I found this behaviour confusing and would suggest to change it so that string values are always matched literally.
If the current behaviour is actually desired, I would like to see it documented explicitly, for example in the `.equalTo()` docs.

**Comment by joeconwaystk** [comment]
Yes, this is confusing and after reading the PostgreSQL docs I am just as confused. Entering these commands directly into psql prompt gives the same behavior as you've shown here. That is, the following does not select the inserted row:

```
INSERT INTO _Model (name,createdAt) VALUES ('my\value', '2019-02-13 13:29:40.825907Z');
SELECT id,name,createdAt FROM _Model WHERE _Model.name LIKE 'my\value';
```

If the backslash is escaped (`my\\value`), then the row is found. 

Tbh, I'm not sure what Aqueduct (really, the underlying postgres driver) should do here. There is a slippery slope on pre-processing queries before they are sent to the database. I'd be interested to find out more about why the two above queries behave like this before making any changes.

**Comment by pschiffmann** [comment]
Sorry, I think I pointed you in the wrong direction the other day. Today, I looked up what the `LIKE` operator actually does. Look what I found in the [documentation](https://www.postgresql.org/docs/11/functions-matching.html#FUNCTIONS-LIKE):

> The default escape character is the backslash [...]. **To match the escape character itself, write two escape characters.**

Is there a reason why you use `LIKE` to compare strings, and not `=`? (This is not sound advice, just an honest question – I've only started working with Aqueduct and Postgres two weeks ago.)

Obviously, `%` and `_` are affected too:

```dart
test('strings are only found if they match literally', () async {
  await Query.insertObject(app.context, Model()..name ='pschiffmann');
  final model = await (Query<Model>(app.context)
        ..where((m) => m.name).equalTo('%'))
      .fetchOne();
  expect(model, isNull);
});
```
