### ISSUE TITLE
How to seed data from dynamic data

### ISSUE THREAD

**Issue by glinesbdev** [stablekernel/aqueduct#633]
## Issue
I'm getting an error when trying to use data from a class in my project to use in seed data.

## Error from the `db upgrade` CLI command:
The getter 'seedData' isn't defined for the class 'M65efdc948fc9764b8b1256901b498559'.

Try correcting the name to the name of an existing getter, or defining a getter or field named 'seedData'

## Current Situation
I have not been able to find any solutions for this. This is the approach that I've landed on but I've also tried creating the `seedData` inside the `Migration2` class with the same error.

Here is a migration file that I'm trying to run via the `aquduct db upgrade` cli command:

```dart import 'dart:async';

import 'package:aqueduct/aqueduct.dart';
import 'package:event_customer_manager/helpers/database/seeder.dart';

final Seeder seeder = Seeder();
final Map<String, dynamic> seedData = seeder.createUserData();

class Migration2 extends Migration {
  @override
  Future upgrade() async {
    database.createTable(SchemaTable("_User", [
      SchemaColumn("id", ManagedPropertyType.bigInteger,isPrimaryKey: true,autoincrement: true,isIndexed: false,isNullable: false,isUnique: false),SchemaColumn("email", ManagedPropertyType.string,isPrimaryKey: false,autoincrement: false,isIndexed: true,isNullable: false,isUnique: false),SchemaColumn("password", ManagedPropertyType.string,isPrimaryKey: false,autoincrement: false,isIndexed: false,isNullable: false,isUnique: false),SchemaColumn("passwordConfirmation", ManagedPropertyType.string,isPrimaryKey: false,autoincrement: false,isIndexed: false,isNullable: true,isUnique: false),SchemaColumn("token", ManagedPropertyType.string,isPrimaryKey: false,autoincrement: false,isIndexed: false,isNullable: false,isUnique: true),SchemaColumn("createdAt", ManagedPropertyType.datetime,isPrimaryKey: false,autoincrement: false,isIndexed: false,isNullable: false,isUnique: false),SchemaColumn("updatedAt", ManagedPropertyType.datetime,isPrimaryKey: false,autoincrement: false,isIndexed: false,isNullable: false,isUnique: false)]));
  }

  @override
  Future downgrade() async {}

  @override
  Future seed() async {
    await store.executeQuery(
      'INSERT INTO _users (email, password, token, createdat, updatedat)',
      seedData,
      Duration(seconds: 30).inSeconds
    );
  }
}
```

I have a custom class called `Seeder` that I'm importing from my project to seed the `User` class with. That class is as follows:

```dart
import 'package:event_customer_manager/channel.dart';
import 'package:jaguar_jwt/jaguar_jwt.dart';
import 'package:password/password.dart';

class Seeder {
  Map<String, dynamic> createUserData() {
    final String key = EventCustomerManagerChannel.tokenKey;
    const String email = 'test@email.com';
    final jwt = JwtClaim(
      audience: ['localhost'],
      expiry: DateTime.now().add(Duration(hours: 8)),
      issuedAt: DateTime.now(),
      issuer: EventCustomerManagerChannel.appName,
      maxAge: Duration(hours: 8),
      otherClaims: {
        'email': email,
      },
      subject: 'authentication',
    );

    final String password = Password.hash('super1', PBKDF2());
    final String token = issueJwtHS256(jwt, key);
    final DateTime updatedAt = DateTime.now();
    final DateTime createdAt = updatedAt;

    return {
      'email': email,
      'password': password,
      'passwordConfirmation': null,
      'token': token,
      'createdAt': createdAt,
      'updatedAt': updatedAt
    };
  }
}
```

Including the User model code for completeness:

```dart
import 'package:jaguar_jwt/jaguar_jwt.dart';
import 'package:password/password.dart';

import '../channel.dart';
import '../event_customer_manager.dart';

class User extends ManagedObject<_User> implements _User {
  @override
  void willInsert() {
    final String key = EventCustomerManagerChannel.tokenKey;
    final jwt = JwtClaim(
      audience: ['localhost'],
      expiry: DateTime.now().add(Duration(hours: 8)),
      issuedAt: DateTime.now(),
      issuer: EventCustomerManagerChannel.appName,
      maxAge: Duration(hours: 8),
      otherClaims: {
        'email': email,
      },
      subject: 'authentication',
    );

    password = Password.hash(password, PBKDF2());
    passwordConfirmation = '';
    token = issueJwtHS256(jwt, key);
    createdAt = updatedAt = DateTime.now();
  }

  @override
  void willUpdate() {
    updatedAt = DateTime.now();
  }
}

class _User {
  @primaryKey
  int id;

  @Column(indexed: true)
  String email;

  @Column()
  String password;

  @Column(nullable: true)
  String passwordConfirmation;

  @Column(unique: true)
  String token;

  @Column(omitByDefault: true)
  DateTime createdAt;

  @Column(omitByDefault: true)
  DateTime updatedAt;
}
```

**Comment by joeconwaystk** [comment]
There are some intentional restrictions on database migrations to make sure they are immutable and reproducible. Only the contents of the Migration class itself are used in the migration. You can move values and behaviors into properties and instance methods of the Migration, however, any imports, global variables, or function definitions are discarded. 

A suggestion for data like this is to run a one-off Dart script that imports your project, your JWT library, and your Seeder class. Create a `PostgreSQLPersistentStore` the same way you would in your application and execute queries in this script. 

```dart
import 'package:aqueduct/aqueduct.dart';
import 'package:event_customer_manager/event_customer_manager.dart';

Future main() async {
  final Seeder seeder = Seeder();
  // You could optionally use the User type here
  final Map<String, dynamic> seedData = seeder.createUserData();
  final store = PostgreSQLPersistentStore(...);
 
  await store.executeQuery(
      'INSERT INTO _users (email, password, token, createdat, updatedat)',
      seedData,
      Duration(seconds: 30).inSeconds
    );
}
```

Some other things that may just be useful info:
1. The classname you see `M65...` is the md5 hash of your migration class' contents. Migrations are combined into a single script file by `aqueduct db upgrade` and this prevents type name collisions.
2. Aqueduct uses `package:password_hash` for PBKDF2 generation which is tested against the PBKDF2 test vectors identified by specification, I'd default to using that.

**Comment by glinesbdev** [comment]
This was amazingly helpful to know why it wasn't working in the first place so I thank you for that.  Also, I'd like to apologize in advance for the dense-ness of this, however, after taking your advice, I'm running into another issue with a pretty much copy of the code that you suggested with minor changes:

```dart
import 'package:aqueduct/aqueduct.dart';
import 'package:event_customer_manager/event_customer_manager.dart';

void main() async {
  final Seed seed = Seed();

  final dataModel = ManagedDataModel.fromCurrentMirrorSystem();

  final PostgreSQLPersistentStore store =
      PostgreSQLPersistentStore.fromConnectionInfo('bradyn', null, 'localhost',
          5432, '_event_customer_manager_development');

  ManagedContext(dataModel, store);

  await store.executeQuery('INSERT INTO users (email, token, createdat, updatedat)',
      seed.createUserData("test@email.com").asMap(), Duration(seconds: 30).inSeconds);
}

class Seed {
  User createUserData(String email) {
    final User user = User();

    user.email = email;
    user.token = 'super.fake.token';
    user.createdAt = user.updatedAt;
    user.updatedAt = DateTime.now();

    return user;
  }
}
```
Here, I'm using a `ManagedObject<User>` calling `.asMap()` but it gives the same results if I use a plain `Map<String, dynamic>` as well.

After running the script, I get this error:

```bash
$ pub run ./scripts/database/seed.dart OR dart ./scripts/database/seed.dart

Unhandled exception:
PostgreSQLSeverity.error 42601: syntax error at end of input
#0      _PostgreSQLConnection&Object&_PostgreSQLExecutionContextMixin._enqueue (package:postgres/src/connection.dart:402:24)
<asynchronous suspension>
#1      _PostgreSQLConnection&Object&_PostgreSQLExecutionContextMixin.query (package:postgres/src/connection.dart:318:12)
<asynchronous suspension>
#2      PostgreSQLPersistentStore.executeQuery (package:aqueduct/src/db/postgresql/postgresql_persistent_store.dart:291:38)
<asynchronous suspension>
#3      main (file:///Users/bradyn/Projects/Aqueduct/event_customer_manager/scripts/database/seed.dart:11:15)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

In the above stack trace, I do notice that some of the errors are coming from the dart `postgres` package. But I did notice this as well:

`#2  PostgreSQLPersistentStore.executeQuery (package:aqueduct/src/db/postgresql/postgresql_persistent_store.dart:291:38)`

I put a `print` statement in the `aqueduct` file that it shows in the stack trace to make sure that it's getting the correct information from the script so I'll share that here for completeness:

```bash
DATABASE INFORMATION:
FORMAT STRING: INSERT INTO users (email, token, createdat, updatedat)
VALUES: {email: test@email.com, token: super.fake.token, createdAt: 2019-02-24T21:34:55.473702, updatedAt: 2019-02-24T21:34:55.473702}
TIMEOUT: 30
```

I also did some research and found a [StackOverflow question](https://stackoverflow.com/questions/52174665/bad-state-postgresqlseverity-error-specified-parameter-types-do-not-match-col) that you answered about updating Postgres to a more compatible version. The version that I have through `brew` is `postgresql 11.1_1`

I did also find this [StackOverflow thread](https://stackoverflow.com/questions/13119786/syntax-error-at-end-of-input-in-postgresql) about Postgres and using dynamic values in a string but maybe it can help. I was unable to find the string that Aqueduct gives to Postgres during this call from the mentioned file:
```dart
dbConnection.query(formatString,  substitutionValues: values, timeoutInSeconds: timeoutInSeconds);
```

Since it does mention the `postgres` package in the stack trace, I'm not sure if this is an error on the `postgres` side or `Aqueduct` side. Any insight will be very helpful.

Also, to clear up any confusion about the user data, I removed the `password` column in the `User` schema class.

**Comment by joeconwaystk** [comment]
I think this is just invalid SQL, it is missing `VALUES` keyword and the specification of those values. Inserting a single user would be `INSERT INTO _User (email, token, createdat, updatedat) VALUES ('a@a.com', '...', '2000-01-01...', '2001-01-01')`.

**Comment by glinesbdev** [comment]
Ah, I was assuming that it did mapped that data within a `VALUES ()` string within Aqueduct. I'll try that and make sure all of the bugs are ironed out 👍

**Comment by joeconwaystk** [comment]
👍 The ORM does, but the underlying persistent store is effectively the raw connection itself (with some auto-connectivity behavior) and its methods are documented here: https://pub.dartlang.org/documentation/postgres/latest/postgres/PostgreSQLExecutionContext-class.html
