### ISSUE TITLE
Consider removing part and part of

### ISSUE THREAD

**Issue by adaojunior** [stablekernel/aqueduct#64]
using `part` isn't considered good practice
several of the Dart team members would rather remove it from the language

**Comment by joeconwaystk** [comment]
Is there a better approach? I don't care for it either, but it currently beats importing a bunch of files in each part of the library. Also, my understanding of that practice is that it can have a negative impact when compiled to JS, but that won't matter here. Interested in other possibilities though

**Comment by adaojunior** [comment]
It is mostly a style that the dart team and the community are using.
I'll give you an example: [dart-lang/shelf](https://github.com/dart-lang/shelf)
They are no longer using `library`, `part` and `part of`. That's also true for all the other dart-team and google packages.
Anyway, it is just a suggestion, you can think about it and decide which approach you feel most confortable using.

**Comment by adaojunior** [comment]
Also, I dont think it has a negative impact when compiled to JS. Dart uses tree shaking and it removes unused code.
