### ISSUE TITLE
Aqueduct pagination example

### ISSUE THREAD

**Issue by rullyalves** [stablekernel/aqueduct#642]
Is there a clearer example of how paging works in the Aqueduct? I looked in the documentation, but found the current example a bit confusing.

**Comment by joeconwaystk** [comment]
What documentation did you read and what are you looking to understand that it didn’t have?

**Comment by rullyalves** [comment]
Thanks for the quick response, there the content of these links:

http://aqueduct.io/docs/http/resource_controller/

http://aqueduct.io/docs/db/advanced_queries/

I managed to page normally using the ManagedObjectController, but it was not very clear how pagination should be implemented using the ResourceController.

**Comment by joeconwaystk** [comment]
Add query parameters to your operation method and feed those as inputs to `Query.pageBy`?

**Comment by rullyalves** [comment]
My question is how to implement basic pagination in this part of documentation 
http://aqueduct.io/docs/db/advanced_queries/#paging-fetched-result-sets
specifically in this part of the code, I could not understand how I would do to page using a ResourceController :

var firstQuery = Query<Post>(context)
  ..pageBy((p) => p.dateCreated, QuerySortOrder.descending)
  ..fetchLimit = 10;

var firstQueryResults = await firstQuery.fetch();

var oldestPostWeGot = firstQueryResults.last.dateCreated;
var nextQuery = Query<Post>(context)
  ..pageBy((p) => p.dateCreated, QuerySortOrder.descending, boundingValue: oldestPostWeGot)
  ..fetchLimit = 10;

it was not very clear to me how this should be implemented in a ResourceController, should I pass parameters like count, pageBy and others via @Bind.query ()?
how should I implement something similar in an endpoint like this?

 @ Operation.get ("id")
  Future <Response> getCategory (@ Bind.path ("id") int id) async {
    try {
      end categoryQuery = Query <Category> (context)
        ..where ((Category category) => category.id) .equalTo (id);
      final rs = await categoryQuery.fetchOne ();
      if (rs == null) {
        return Response.notFound ();
      }
      return Response.ok (rs);
    } catch (e) {
      throw Response.badRequest ();
    }
  }

**Comment by joeconwaystk** [comment]
Yes, you should pass parameters like `count` via query parameters. The parameters you expose in your API are dependent on your application; for example, its unlikely you'd expose a `pageBy` query parameter for most endpoints, instead having a set number of fields you could page by. I'm closing this issue - please join us in [Slack](http://slackaqueductsignup.herokuapp.com/) for questions about your specific application.
