### ISSUE TITLE
Documentation wrong for modeling data databaseType

### ISSUE THREAD

**Issue by Shebsa** [stablekernel/aqueduct#646]
Hey, I found a problem in the documentation for modeling data in this page http://aqueduct.io/docs/db/modeling_data/

The example for databaseType says
```dart
@Column(databaseType: ManagedType.bigInteger)
int bigNumber;
```
But should be 
```dart
@Column(databaseType: ManagedPropertyType.bigInteger)
int bigNumber;
```

**Comment by joeconwaystk** [comment]
These should be equivalent `ManagedType.bigInteger` is defined as a reference to `ManagedPropertyType.bigInteger`. `ManagedType` was introduced to extend the behavior database types, but for backwards compat, ManagedPropertyType was kept. Is this creating a problem?

**Comment by Shebsa** [comment]
If I try doing `databaseType: ManagedType.bigInteger` I get the error 
```
Arguments of a constant creation must be constant expressions.dart(const_with_non_constant_argument)
```

**Comment by joeconwaystk** [comment]
Yup - that'd create a problem :) Thanks. If you have an opportunity to do so, this can be fixed by a PR to `docs/source` branch. Otherwise, it'll get picked up as it can.

**Comment by Shebsa** [comment]
Done!

**Comment by joeconwaystk** [comment]
Thanks!
