### ISSUE TITLE
Can you add support for mongodb?

### ISSUE THREAD

**Issue by Sm03leBr00t** [stablekernel/aqueduct#649]
Hello guys :),
could you add support for **mongodb** too? I always use it but I am looking forward to migrate to **aqueduct** :). Would be great!!! 

Discussions opened :+1:

**Comment by joeconwaystk** [comment]
You can import the [MongoDB driver](https://pub.dartlang.org/packages/mongo_dart) and use it like you could in any other Dart project. Are you looking for a specific integration with Aqueduct and MongoDB?

**Comment by Sm03leBr00t** [comment]
Yeah so I don't know how to do the first one :D. I would like a option in the cli which allows me to select mongodb or postgres or ... (mostly the first two) :). Could someone like help making the manual process more easy? Like a tutorial or writeup or like a option which driver to use? I am kinda lost on this one ...

**Comment by joeconwaystk** [comment]
Sure. It's not either/or when choosing a database, many applications read from multiple databases and integrate with many other services. The instructions on the page I linked to are just code you can add to any Aqueduct project - or any Dart project - to start using MongoDB. You won't be able to use the ORM (`Query`, `ManagedObject`, etc.) when using MongoDB, but an ORM isn't all that valuable for a document database.

**Comment by Sm03leBr00t** [comment]
ok so just add `mongo_dart` and then write everything as usual? Is there anything other to keep an eye on ? :) and thanks for this fast support on this one m8te ;)

**Comment by joeconwaystk** [comment]
Yessir. I'd try and reuse connections by using some sort of connection pool and injecting your database connection as a service (http://aqueduct.io/docs/application/channel/), but that's just for performance.

**Comment by Sm03leBr00t** [comment]
awesome !!! Thank you @joeconwaystk . Is there like a discord or IRC for more chatting instead of Issues on this project?

**Comment by joeconwaystk** [comment]
Yes: http://slackaqueductsignup.herokuapp.com/
