### ISSUE TITLE
How to disable running path using aqueduct serve?

### ISSUE THREAD

**Issue by NTMS2017** [stablekernel/aqueduct#653]
When I run aqueduct serve it shows port and file path. How to disable running path using aqueduct serve?

**Comment by joeconwaystk** [comment]
I'm not sure what this question means?

**Comment by NTMS2017** [comment]
here it is. When I run my aqueduct it shows below in terminal. In config section it shows my config.yaml path as **Config: /home/niyazi/.urcs/ntms/ntmsapi/config.yaml**

my problem is the whoever controls the machine can see the config and the aqueduct dart file simple following the path. And my question is how to disable that config part is not visible on terminal. Thank you very much.

```
-- Aqueduct CLI Version: 3.2.0+1
-- Aqueduct project version: 3.1.0+1
-- Preparing...
-- Starting application 'ntmsapi/ntmsapi'
    Channel: NtmsApiChannel
    Config: /home/niyazi/.urcs/ntms/ntmsapi/config.yaml
    Port: 8888
[INFO] aqueduct: Server aqueduct/1 started.  
[INFO] aqueduct: Server aqueduct/2 started. 
```

**Comment by joeconwaystk** [comment]
There is not a way to hide this information and no plan to add that capability right now.

**Comment by NTMS2017** [comment]
any idea, why it must be show the config path?

**Comment by joeconwaystk** [comment]
To indicate which configuration file is being used. Is there a reason you need this hidden? You can use the bin/main.dart script if you don't want any info printed.

**Comment by NTMS2017** [comment]
Thanks. Yes, I dont need to show the path dor security reason.
How can I use "bin/main.dart script"? Any example?

**Comment by joeconwaystk** [comment]
From your terminal: `dart bin/main.dart`.

**Comment by NTMS2017** [comment]
thanks
