### ISSUE TITLE
Constructing query params in URL

### ISSUE THREAD

**Issue by seanmavley** [stablekernel/aqueduct#654]
I currently have this in my Application channel entry point

`    router.route('/icd/[:id]').link(() => ICDController(context));
`

In my controller, I want to grab a query param, namely, `limit` like so

`Future<Response> getAll(@Bind.query('limit') int limit, @Bind.query('page') int page) async { ... }`

Now, I want my url to be like this

`example.com/icd?limit=5&page=2`

How do I go about it?

**Comment by joeconwaystk** [comment]
This should work - the router doesn't care about query parameters. What are you experiencing?

**Comment by seanmavley** [comment]
@joeconwaystk Without the `?limit=5` (or the `&page=2` for that matter), I get the error:

`"error": "missing required Query Parameter 'limit'"`

**Comment by seanmavley** [comment]
I got it now:

> [By wrapping an argument in curly brackets](https://stackoverflow.com/a/55652885/1757321)

**Comment by bluemix** [comment]
I hope you can provide an example of how it is done int the `Router` and how it is parsed with `Binding`
@seanmavley

**Comment by bluemix** [comment]
OK, it is solved.
If my path is `/webhook?hub.challenge=CHALLENGE&hub.mode=MODE`,
the router will be:
```dart
router
    .route('/webhook')
    .link(() => HooksController());
```
 and `Bind`ing will be like this:
```dart
  @Operation.get()
  Future<Response> hooksGet(
    @Bind.query('hub.challenge') String challenge,
    @Bind.query('hub.mode') String mode,
  ) async {
...
```
