### ISSUE TITLE
OpenAPI generation broken at Enum

### ISSUE THREAD

**Issue by ewoudje** [stablekernel/aqueduct#655]
There is something wrong in my code when i do `aqueduct document` it fails with this:
```
-- Aqueduct CLI Version: 3.2.0+1
-- Aqueduct project version: 3.2.0+1
*** Uncaught error
    Bad state: Invalid argument(s): Illegal argument in isolate message : (object is a regular Dart Instance)
  **** Stacktrace
  * #0      _SendPortImpl._sendInternal (dart:isolate/runtime/libisolate_patch.dart:218:70)
  * #1      _SendPortImpl.send (dart:isolate/runtime/libisolate_patch.dart:202:5)
  * #2      main (<data:application/dart>:13:12)
  * <asynchronous suspension>
  * #3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:296:32)
  * #4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
  ****
```
But `aqueduct serve` does work and i tried a sample project and there `aqueduct document` does work. https://github.com/ewoudje/rulers_of_states/tree/master/server

**Comment by ewoudje** [comment]
I've found the source from the error it was an enum in a ManagedObject. Is this expected behavior? I thought it was allowed for an enum?

**Comment by joeconwaystk** [comment]
Yes, there is a bug with enums. It will be fixed in 3.2.1

**Comment by pretorean** [comment]
I also got with the same error. Good thing you fixed it. Waiting for release.

**Comment by joeconwaystk** [comment]
3.2.1 release is now available on pub.
