### ISSUE TITLE
Compile to AOT

### ISSUE THREAD

**Issue by virgiawan** [stablekernel/aqueduct#659]
Hi all, 
Did aqueduct support compile to AOT ?
Do you have plan to have it for the next release ?

Thanks.

**Comment by joeconwaystk** [comment]
This is not supported by the Dart VM outside of Flutter.

**Comment by aaveidt** [comment]
@joeconwaystk https://dart.dev/tools/dart2aot

**Comment by joeconwaystk** [comment]
@aaveidt https://github.com/stablekernel/aqueduct/issues/669
