### ISSUE TITLE
Response ok value problem

### ISSUE THREAD

**Issue by JAICHANGPARK** [stablekernel/aqueduct#671]
Hi all 
I had some problem about Response value

my internal return value was 
> {"user":[{"Name":1,"email":"12344"},{"Name":2,"email":"12346"}]}

![image](https://user-images.githubusercontent.com/19484515/57567710-5c6a0580-7418-11e9-99a6-376cffaa44c0.png)

But Browser, ARC, postman return value was 
>"{\"user\":[{\"Name\":1,\"email\":\"12344\"},{\"Name\":2,\"email\":\"12346\"}]}"

![image](https://user-images.githubusercontent.com/19484515/57567704-4bb98f80-7418-11e9-9373-4455b6a05199.png)

![image](https://user-images.githubusercontent.com/19484515/57567716-6986f480-7418-11e9-8bbf-1c72eb299371.png)

How to Fix this Problem?? 

This is my REST Get Code 

```
 @override
  FutureOr<RequestOrResponse> handle(Request request) async {
    final conn = await MySqlConnection.connect(ConnectionSettings(
  ));
  print(conn);
  var result = [];
  var results = await conn.query("select * from table where delete = 0");
  for (var row in results) {
    result.add({'Name' : row[0], 'email' : row[1]}
      );
  }
    await conn.close();
     var therapist = {};
    therapist["user"] = result;
    String returnValue = json.encode(therapist); 

    print(returnValue);   
    return Response.ok(returnValue, headers: {
    });
```

**Comment by joeconwaystk** [comment]
The framework handles encoding body objects into the selected content-type - in your case, you are double-encoding the body. i.e., `return Response.ok(therapist)`. See this documentation: https://aqueduct.io/docs/http/request_and_response/
