### ISSUE TITLE
Variable naming in advanced query docs confusing

### ISSUE THREAD

**Issue by suragch** [stablekernel/aqueduct#682]
I found the variable names in parts of the [Advanced Query docs](https://github.com/stablekernel/aqueduct/blob/docs/source/source/docs/db/advanced_queries.md) confusing.

```
final q = Query<Child>(context)
  ..where((p) => p.parent.age).greaterThan(30)
  ..join(object: (p) => e.parent);

final childrenWithParentsOver30 = await q.fetch();
```

In this one `p` makes me think Parent, but isn't it referring to the Child? And what is `e`? Although wordy, it might be easier to understand if fuller variable names like `parent` or `child` were used when there are multiple object types.

```
var averageSalary = await query.reduce.sum((u) => u.salary);
var averageSalaryOfPeopleNamedBob = await query.reduce.sum((u) => u.salary);
```

I'm probably misunderstanding `reduce` but shouldn't the `sum` return the sum, and not the average?

**Comment by joeconwaystk** [comment]
Yes, these are errors. Should be `..where((child) => child.parent.age).greaterThan(30)` and `join(object: (child) => child.parent)`. And yes, `average` instead of `sum` - they are both instance methods of `reduce`.

**Comment by joeconwaystk** [comment]
Closing because I believe this has been resolved in docs/source branch
