### ISSUE TITLE
aqueduct db upgrade --connect postgres://dart:dart@localhost:5432/app

### ISSUE THREAD

**Issue by eduardotd** [stablekernel/aqueduct#691]
Good Night!
The commands

aqueduct db generate
aqueduct db upgrade --connect postgres://dart:dart@localhost:5432/app

in a brand new project created with -t db_and_auth
gives this message:

*** There was an issue. Reason: Specified parameter types do not match column parameter types in query SELECT to_regclass(@tableName:text). Table: null Column: null

Any ideas?

Thanks in advance

**Comment by joeconwaystk** [comment]
Are you running at least version 9.6 of PostgreSQL?

**Comment by eduardotd** [comment]
aqueduct 3.2.1
Dart VM version: 2.3.1 (Tue May 21 19:28:38 2019 +0200) on "linux_x64"

**Comment by eduardotd** [comment]
sorry, postgresl (9.5.17)
I will try on 9.6

**Comment by eduardotd** [comment]
Works perfectly on postgresql 10.0
Tks
