### ISSUE TITLE
Do we need Webserver Like Apache/ Nginx in front of Dart aqueduct server ?

### ISSUE THREAD

**Issue by GauravPatni** [stablekernel/aqueduct#698]
Dear aqueduct Team,

after doing Flutter for mobile apps now I want to do backend application ( REST API ) using Dart.

aqueduct looks great but I am not sure whether "aqueduct" alone is sufficient for production deployment? whether it will handle concurrent connections & has good load balancing? Or do we need a proven web server like Apache / Nginx before Dart server?

Thanks for creating aqueduct !
Gaurav

**Comment by joeconwaystk** [comment]
Aqueduct is an application server. It handles concurrent connections and uses a round-robin method to split request processing among CPU threads. You can expose Aqueduct directly to internet traffic, but it is preferable to use a managed load balancer (e.g. https://cloud.google.com/load-balancing/).
