### ISSUE TITLE
There seems to be a typo in the tutorial

### ISSUE THREAD

**Issue by disburden** [stablekernel/aqueduct#715]
In this article [](https://aqueduct.io/docs/db/advanced_queries/)
Chatper "Including Relationships in a Fetch (aka, Joins)"

```
class User extends ManagedObject<_User> implements _User {}
class _User {
  @primaryKey
  int id;

  String name;
  ManagedSet<Task> tasks;  
}

class Task extends ManagedObject<_Task> implements _Task {}
class _Task {
  @primaryKey
  int id;

  @Column(#tasks)
  User user;

  String contents;
}
```

Is it correct to replace @Cloumn with @Relate?

**Comment by joeconwaystk** [comment]
Yes, it should be `@Relate(#tasks)`. If you are able to, please send a PR to `docs/source` branch in this repo that contains the source markdown for the documentation.

**Comment by disburden** [comment]
Ok, I have submitted a PR,#716
