### ISSUE TITLE
Custom AuthController 

### ISSUE THREAD

**Issue by carmas123** [stablekernel/aqueduct#718]
Hi, what is the best way to extend "AuthController" class?
I try to extend this class and use my custom controller but the "authHeader" property is always null.

**Comment by joeconwaystk** [comment]
This class isn't intended to be subclassed, what is the behavior you are looking to add or change?

**Comment by carmas123** [comment]
I want to change the error messages in response.

**Comment by joeconwaystk** [comment]
The error messages are determined by the OAuth 2.0 specification (https://tools.ietf.org/html/rfc6749#section-5.2). What specifically do you want to change about the error messages and in response to what type of errors?

**Comment by carmas123** [comment]
Ok if this is a standard I handle the messages into the app and not in server.
Thank you so much.

I close this and open another issues for authentication process.
