### ISSUE TITLE
dart can not recognize aqueduct package

### ISSUE THREAD

**Issue by wurikiji** [stablekernel/aqueduct#722]
![image](https://user-images.githubusercontent.com/5652744/62871913-53f6d300-bd57-11e9-97f9-b4e0f26c8830.png)

As you can see, the dart can not recognize `aqueduct` package. 
Everything works fine but it's unable to use autocomplete due to the problem. 
I am using vscode 1.37.0 and dart in a stable channel. 

Does anyone have same issue?

**Comment by wurikiji** [comment]
I also tested on the `webstorm` but it is still same.

**Comment by wurikiji** [comment]
solved.

**Comment by MyracleDesign** [comment]
@wurikiji Could you give a small hint how you solved it, just in case someone finds this issue.

**Comment by wurikiji** [comment]
@MyracleDesign  It was not an issue of `aqueduct`. I incidentally created the aqueduct project inside the other dart project. So the package dependencies were analyzed by the parent project.
