### ISSUE TITLE
Bump analyzer version 

### ISSUE THREAD

**Issue by daniel-v** [stablekernel/aqueduct#733]
Currenty latest release has a dependency on `analyzer: '<0.36.0'`. This is quite an old one, released on `Mar 21, 2019`. Some packages that rely on code generation (such as Hive) are incompatible with this release. Would be nice if you could expand the upper bounds of the analyzer dependency to the latest version you support.

Workaround:

```yaml
dependency_overrides:
  analyzer: '>=0.36.0'
```

**Comment by cedx** [comment]
Same issue here: I can't upgrade numerous dependencies because of the `analyzer` constraint.

**Comment by vraptor75011** [comment]
Same issue with this package : [https://pub.dev/packages/validations]
