### ISSUE TITLE
There was an issue. Reason: syntax error at end of input. Table: null Column: null. How can I fix it?

### ISSUE THREAD

**Issue by lucasellery** [stablekernel/aqueduct#746]
aqueduct db upgrade --connect postgres://read:read@localhost:5432/reads
-- Aqueduct CLI Version: 3.2.1
-- Aqueduct project version: 3.2.1
-- Updating to version 1 on new database...
    PostgreSQL connecting, read@localhost:5432/reads.
    Initializating database...
        CREATE TABLE _aqueduct_version_pgsql (versionNumber INT NOT NULL UNIQUE,dateOfUpgrade TIMESTAMP NOT NULL)
    Applying migration version 1...
        CREATE TABLE _Read (id BIGSERIAL PRIMARY KEY,title TEXT NOT NULL UNIQUE,author TEXT NOT NULL,year INT NOT NULL)
    Seeding data from migration version 1...
*** There was an issue. Reason: syntax error at end of input. Table: null Column: null

**Comment by joeconwaystk** [comment]
It looks like there is a bad query being made in your `seed` function for your first migration.

**Comment by judeosbert** [comment]
I am also facing a similar issue in my project 
```
-- Aqueduct CLI Version: 3.3.0+1
-- Aqueduct project version: 3.3.0+1
-- Updating to version 11 from version 10...
    Replaying versions: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10...
    PostgreSQL connecting, dart_app@localhost:8878/postgres.
    Applying migration version 11...
    	CREATE TABLE ApproverStatus (id BIGSERIAL PRIMARY KEY,createdOn TIMESTAMP NOT NULL,statusChangeOn TIMESTAMP NOT NULL,isApproved BOOLEAN NOT NULL DEFAULT false,managerEmail TEXT NOT NULL)
    	CREATE TABLE LeaveRequest (id BIGSERIAL PRIMARY KEY,createdOn TIMESTAMP NOT NULL,leaveDateStart TIMESTAMP NOT NULL,leaveDateEnd TIMESTAMP NOT NULL,leaveType TEXT NOT NULL,status TEXT NOT NULL,description TEXT NOT NULL,workingDaysInPeriod INT NOT NULL)
    	ALTER TABLE ApproverStatus ADD COLUMN leaveRequest_id BIGINT NULL
    	CREATE INDEX ApproverStatus_leaveRequest_id_idx ON ApproverStatus (leaveRequest_id)
    	ALTER TABLE ONLY ApproverStatus ADD FOREIGN KEY (leaveRequest_id) REFERENCES LeaveRequest (id) ON DELETE SET NULL
    	ALTER TABLE LeaveRequest ADD COLUMN user_id TEXT NULL
    	CREATE INDEX LeaveRequest_user_id_idx ON LeaveRequest (user_id)
    	ALTER TABLE ONLY LeaveRequest ADD FOREIGN KEY (user_id) REFERENCES OfficeUser (id) ON DELETE SET NULL
    	ALTER TABLE OfficeUser ADD COLUMN messagingToken TEXT NOT NULL DEFAULT
*** There was an issue. Reason: syntax error at end of input. Table: null Column: null
```
I checked the seed functions in my previous migration files. All are empty. Please help me with this. Thanks.
