### ISSUE TITLE
documentation tutorial OAuth2 suggestions

### ISSUE THREAD

**Issue by hasenbalg** [stablekernel/aqueduct#749]
The first line in [https://aqueduct.io/docs/tut/oauth2/](https://aqueduct.io/docs/tut/oauth2/) under 

> Setting up OAuth 2.0: Authenticating Users

has a double 'can'.

Further down where the OAuth request is demonstrated the word *look* is missing in

> In Dart code, this would like this:

I had to make a few changes to the example of the dart OAuth request to make it work:
```
import 'dart:async';
import 'dart:convert';

import 'package:http/http.dart'
    as http; // Must include http:any package in your pubspec.yaml

Future<void> main() async {
  const clientID = "org.hasenbalg.zeiterfassung";
  const body = "username=bob&password=password&grant_type=password";

// Note the trailing colon (:) after the clientID.
// A client identifier secret would follow this, but there is no secret, so it is the empty string.
  final String clientCredentials =
      const Base64Encoder().convert("$clientID:".codeUnits);

  final http.Response response =
      await http.post("http://localhost:8888/auth/token",
          headers: {
            "Content-Type": "application/x-www-form-urlencoded",
            "Authorization": "Basic $clientCredentials"
          },
          body: body);
  print(response.body);
}
```

**Comment by joeconwaystk** [comment]
For these types of edits, can you submit a pull request the `docs/source` branch? All of the documentation is in markdown, and the names of the URLs you found the doc on are the names of the folders in the repo.
