### ISSUE TITLE
Are there any performance tests: Aqueduct vs Nginx/PHP vs Node.js?

### ISSUE THREAD

**Issue by ProgrammingLife** [stablekernel/aqueduct#751]
Are there any performance tests: Aqueduct vs Nginx/PHP vs Node.js? How faster Aqueduct than others or which one is slower? 
Maybe Aqueduct + dart2native improves performance?

**Comment by joeconwaystk** [comment]
Someone submitted an image Techempower Benchmarks and it was about the same as some other popular frameworks (but not the same as Nginx, H20, etc.) It was faster for some tests and slower for others. I haven't looked in the last 6 months. dart2native will most certainly improve startup time, but it'll likely be the same at runtime. We will see once #669 is available.
