### ISSUE TITLE
supper mysql

### ISSUE THREAD

**Issue by godot0413301** [stablekernel/aqueduct#752]
In china，a lot of people use mysql5.7。so I wish aqueduct supper mysql

**Comment by godot0413301** [comment]
I use mybatis-plus to supper mysql in springboot with java，so you can have a look at https://mybatis.plus/

**Comment by joeconwaystk** [comment]
There aren't any plans to support MySQL. Aqueduct's ORM isn't great for retroactively applying to an existing database schema, either.
