### ISSUE TITLE
NoSuchMethodError: The method '[]' was called on null.

### ISSUE THREAD

**Issue by zeucxb** [stablekernel/aqueduct#759]
I'm getting:

```
NoSuchMethodError (NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("name"))
```

When add `{@Bind.query('name') String name}` on:

```dart
@Operation.get()
Future<Response> getAllHeroes({@Bind.query('name') String name}) async {
```

**Comment by joeconwaystk** [comment]
When does this error occur?

**Comment by zeucxb** [comment]
The problem was the `content-type`:

`--header 'Content-Type: application/x-www-form-urlencoded'`

**Comment by zeucxb** [comment]
It's strange, like when I request `/heroes` (it works), but `/heroes/` returns `400`.

```json
{
    "error": "invalid value for 'id'"
}
```

Is this right? It's the default behavior?

**Comment by joeconwaystk** [comment]
Yes, this is the default behavior. Because of the trailing slash in `/heroes/`, the router will append `index.html`. When your controller picks this up, it is trying to parse an integer id from `index.html`.

**Comment by tusharsadhwani** [comment]
@joeconwaystk what if i wanted to override this behaviour, for my URLs to work with trailing slashes as well? what's the easiest way to do that?
