### ISSUE TITLE
QueryPredicate with like

### ISSUE THREAD

**Issue by thiagoluis88** [stablekernel/aqueduct#765]
Hello,

I'm doing a select with like operator like this:
`final query = Query<UserEntity>(context);

    query.predicate = QueryPredicate("lower(email) like '%@name1%' OR lower(name) like '%@name2%'", {
      "name1": text.toLowerCase(),
      "name2": text.toLowerCase()
    });`

But I received this error:
`aqueduct: PostgreSQLSeverity.error 08P01: bind message supplies 2 parameters, but prepared statement "000000000001" requires 0`

If I remove the single quotes of  '%@name1%'  this error desapear, but another error comes:
`ERROR:  syntax error at or near "%`

How can I do QueryPredicate with like?

**Comment by Reductions** [comment]
The problem here is that text is String that means it the final query will look like (assuming you have {"name1": "Slavi", "name1": "Boyanov"}):

```
"lower(email) like '%'Slavi'%' OR lower(name) like '%'Boyanov'%'
```

I would recommend you make a function that gets the text as an argument converts it to lower case and appends and appends '%':

```dart
String textToMatch(String test) {
  return '%${text.toLowerCase()}%';
```

**Comment by thiagoluis88** [comment]
Hello again.
The method textToMatch() worked like a charm.
Now the logic is like this:

`query.predicate = QueryPredicate("lower(email) like @email OR lower(name) like @name", {
      "email": textToMatch(text),
      "name": textToMatch(text)
    });`

It would be nice if could have an explanation of how to use like operator with QueryPredicate as you answered me.

Thanks
