### ISSUE TITLE
Aqueduct need admin ui like Django！！！

### ISSUE THREAD

**Issue by toop** [stablekernel/aqueduct#766]
Aqueduct need admin ui like Django admin！！！

**Comment by Reductions** [comment]
As the description of the project states:
```
Aqueduct is an extensible HTTP framework for building REST APIs on top of the Dart VM.
```
It is not for building UIs but for APIs. That could also be deduce by the fact that aqueduct does not include any kind of html tempting engine. You can think of Aqueduct more as `Flask` then `Django` speaking in python terms.

**Comment by joeconwaystk** [comment]
This would be appropriate in another package, but not the framework itself. Some of the tools that would be in this UI are already available in the CLI. For example, `aqueduct auth add-client` would also make sense in a UI.

Are there specific capabilities you think are important to Aqueduct that need to be in the CLI? Also, it'd be an interesting project to create a UI that calls those CLI functions somehow.

**Comment by kalmigs** [comment]
Hi @joeconwaystk , does aqueduct have admin page template like django?
