### ISSUE TITLE
aqueduct create fails

### ISSUE THREAD

**Issue by kismet-cai** [stablekernel/aqueduct#768]
Creating a new project based on template `aqueduct create` fails. with `Bad state: No element`. Looks like the aqueduct package isn't found even though pub cache directory is in path and aqueduct has been activated globally.

   Bad state: No element
  **** Stacktrace
  * #0      ListMixin.firstWhere (dart:collection/list.dart:150:5)
  * #1      CLIAqueductGlobal.aqueductPackageRef (package:aqueduct/src/cli/commands/create.dart:342:10)
  * #2      CLIAqueductGlobal.templateDirectory (package:aqueduct/src/cli/commands/create.dart:347:12)
  * #3      CLIAqueductGlobal.getTemplateLocation (package:aqueduct/src/cli/commands/create.dart:351:12)
  * #4      CLITemplateCreator.handle (package:aqueduct/src/cli/commands/create.dart:51:27)
  * #5      CLICommand.process (package:aqueduct/src/cli/command.dart:158:20)
  * <asynchronous suspension>
  * #6      CLICommand.process (package:aqueduct/src/cli/command.dart:134:12)
  * #7      main (file:///C:/Users/kismet-cai/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/aqueduct-3.2.1/bin/aqueduct.dart:9:27)
  * #8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
  * #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
  ****

**Comment by kismet-cai** [comment]
It appears as though my APPDATA environment variable (Windows Powershell: `ls env`) was set to `C:\Users\<USER>\AppData\Roaming` PubCache is expecting `C:\Users\<USER>\AppData\`. I think a clearer error message would help here.

**Comment by joeconwaystk** [comment]
Hm. This is coming from package:pub_cache. I encountered a similar issue a year or so ago that was easily fixed: https://github.com/google/pub_cache/issues/34. My guess is that there is a hard coded value instead of using the current env value of where your pub cache should be.

**Comment by DavyGuedes** [comment]
Hi @kismet-cai, 
How did you solve this issue? 
Thanks in advance!

**Comment by kismet-cai** [comment]
I recall that I had to edit the `PUB_CACHE` environment variable to point to the correct location.
