### ISSUE TITLE
listen 2 ports

### ISSUE THREAD

**Issue by sinegovsky-ivan** [stablekernel/aqueduct#772]
Hello!
In my project i have to separate business handlers and services handlers (metrics, healthcheck, etc). Business handlers must be available for all internet, services only for internal network.

My idea is run business handlers at one port, and services handlers at another port.

How i can achieve this?

**Comment by Reductions** [comment]
I would recommend ding this with an external service (nginx for example).

The other way of doing this would  be to create 2 channels for the 2 different things (I would not recommend doing this). This will mean that you have to start them in your `bin/main.dart` file like that:
```dart
void main(){
    final internalApp = Application<MetricsChannel>()
      ..options.port = anotherPort;

    final internal =
        internalApp.start(numberOfInstances: someOtherNumberThatWorksForYou);

    final externalApp = Application<BusinessChannel>()..options.port = onePort;

    final external =
        externalApp.start(numberOfInstances: someNumberThatWorksForYou);

    await internal;
    await external;

    print("Applications started.");
    print("Use Ctrl-C (SIGINT) to stop running the application.");
}
```

P.S.: If you want to ask question better do it in the slack channel as github issues are meant to be used as a way to report bugs or do feature request and discussions.

**Comment by sinegovsky-ivan** [comment]
@Reductions thank you! I didn't know about slack :(
