### ISSUE TITLE
CORS: pre-flight response is always returning 403

### ISSUE THREAD

**Issue by jquintana53** [stablekernel/aqueduct#778]
**Aqueduct version: 3.2.1**
After reading the documentation several times I believe aqueduct will handle the pre-flight request without further configuration as per the doc:

https://aqueduct.io/docs/application/configure/#configuring-cors-headers
> All controllers have built-in behavior for handling CORS requests from a browser.

However, I have explicitly relaxed the settings to allow everything and still am getting 403. Post requests work just fine is just the pre-flight that's failing.
Can anybody help me figure this out?

This is my app config:

```
class MyAppChannel extends ApplicationChannel {

  /// This method is invoked prior to [entryPoint] being accessed.
  @override
  Future prepare() async {
    CORSPolicy.defaultPolicy
      ..allowedMethods = ["POST", "OPTIONS"]
      ..allowedOrigins = ["*"];
      // .....
   }

  /// This method is invoked after [prepare].
  @override
  Controller get entryPoint {
      final router = Router();
      router.route("/login").link(() => LoginController());
      // .....
  }
// ....
}

// Login Controller
class LoginController extends ResourceController {
  LoginController();

  @Operation.post()
  Future<Response> login(@Bind.body() Credentials credentials) async {
       // some logic
  }
}
```

**Browser pre-flight request headers:**

OPTIONS /login HTTP/1.1
```
Host: localhost:8888
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: http://localhost:49311
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Access-Control-Request-Headers: authorization,content-type
Accept: */*
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors
Referer: http://localhost:49311/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```

**Response details:**
```
Request URL: http://localhost:8888/login
Request Method: OPTIONS
Status Code: 403 Forbidden
Remote Address: 127.0.0.1:8888
Referrer Policy: no-referrer-when-downgrade
```

**Response headers:**
```
content-length: 0
server: aqueduct/4
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
```

**Comment by jquintana53** [comment]
After further troubleshooting I found the error was on my end.

The culprit was 
`Access-Control-Request-Headers: authorization,content-type`

Some headers like Content-Type is allowed by default, however, the Authorization header has to be manually added:

`CORSPolicy.defaultPolicy.allowedRequestHeaders.add('Authorization');`

Kudos to the author of this framework, is really a pleasure to use it.

**Comment by jquintana53** [comment]
Maybe this needs to be corrected as the header names should be case-insensitives as per the specifications: https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

**Comment by joeconwaystk** [comment]
Yes, it'd be good to add an auto-lowercasing capability to the CORS headers list. The headers from an incoming request are always lowercased, so it is safer/faster to compare it to a guaranteed lowercased list. 

To solve, the following change to the framework is required: 

1. A `LowercasingList` is created; it lowercases every element it contains on element insertion (there is a `LowercasingMap` as a reference already in the framework). 
2. The initial value for the CORSPolicy headers is an instance of a `LowercasingList`.
3. The setter for CORSPolicy headers is overridden to wrap a non-`LowercasingList` as a `LowercasingList`.
4. Tests are written to assert that inputting headers with uppercase characters does not impact the result of checking for matches.
