### ISSUE TITLE
XMLHttpRequest error. 

### ISSUE THREAD

**Issue by majdkz97** [stablekernel/aqueduct#779]
when i request "GET" from flutter Web it's Work.
but when i request "Post"
he give this in Server:

> 

[INFO] aqueduct: OPTIONS /service_types 0ms 403 {user-agent : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36\nconnection : keep-alive\nsec-fetch-dest : empty\naccept-encoding : gzip, deflate, br\nsec-fetch-site : same-site\nreferer : http://localhost:53859/\naccept : */*\nsec-fetch-mode : cors\naccept-language : en-US,en;q=0.9\norigin : http://localhost:53859\nhost : localhost:8888\naccess-control-request-headers : authorization,bearer,content-type\naccess-control-request-method : POST\n}   

> 

and throw exception on flutter_web: XMLHttpRequest error.

**Comment by majdkz97** [comment]
i've tried to add this:

    CORSPolicy.defaultPolicy
      ..allowedMethods = ["POST", "GET","PUT","DELETE"]
      ..allowedOrigins = ["*"];

and still not working

**Comment by noordawod** [comment]
Maybe you need to add `OPTIONS`?

**Comment by majdkz97** [comment]
i added it and still not working

**Comment by majdkz97** [comment]
It's Work After add any additional used header to Allowed Requested header:

   CORSPolicy.defaultPolicy
      ..allowedMethods = ["POST", "GET","PUT","DELETE","OPTIONS"]
      ..allowedOrigins = ["*"]..allowedRequestHeaders.add('bearer');

In my Case i used "bearer" so i have to add it.
and header should be lower case, they don't work upper case.
