### ISSUE TITLE
Route Path matching

### ISSUE THREAD

**Issue by LaurentiuSimionescu** [stablekernel/aqueduct#783]
How can I assign a controller for ?
`router.route("/users/[:id]");`

And another controller for:
`router.route("/users/me");`

**Comment by joeconwaystk** [comment]
Keep `router.route("/users/[:id]")`. Bind a path variable as a string and then check if it is the string 'me' or an integer id:

```
@Operation.get('id')
Future<Response> getUserById(@Bind.path('id') String id) async {
  if (id == "me") {
     ...
  } else {
    idNumber = int.parse(id);
  }
}
```

**Comment by LaurentiuSimionescu** [comment]
This only works if i do a request like this:
`/users/123`
If i do a request like this:
`/users/me`
It doesn't work

**Comment by LaurentiuSimionescu** [comment]
I was using a QueryController, it is working with a ResourceController.

**Comment by LaurentiuSimionescu** [comment]
The order matters:

router
    .route("/users/[:id]")
    .linkFunction((request) => JsonApi.badRequest("id"));
router
    .route("/users/me")
    .linkFunction((request) => JsonApi.badRequest("me"));

This will print all the time "id"



router
    .route("/users/me")
    .linkFunction((request) => JsonApi.badRequest("me"));
router
    .route("/users/[:id]")
    .linkFunction((request) => JsonApi.badRequest("id"));

This will print "me" also.
