### ISSUE TITLE
unable to connect to postgres server to conduct database table upgrade

### ISSUE THREAD

**Issue by drexel-ue** [stablekernel/aqueduct#784]
This very same command has worked in the past, im not really sure what could have changed.

Command:
`aqueduct db upgrade --connect postgres://user_name:password@public_ip:port/database_name`

Server currently accepts `0.0.0.0/0` as a whitelisted ip so it should accept all connections as SSL is not currently setup. port should be open on 5432

**Comment by Lord-Shibe** [comment]
did you find a solution for this?

**Comment by daniel-v** [comment]
Running into the same issue. 

Interesting part of this issue is that running aqueduct's `bin/aqueduct.dart` directly the arguments matching that of the installed global package's work just fine. The running via install global package doesn't work, running directly does.

**Comment by daniel-v** [comment]
Found why that was happning and found a solution too. (cc @drexel-ue just so that you get a ping about this)

As it turns out, I activated aqueduct with SDK version 2.5.2 a while ago. In the meantime I upgraded to 2.7.1 and there seem to have been changes in the compiled script for aqueduct.

So the solution was:

```bash
pub global deactivate aqueduct # this will remove old snapshot 
pub global activate aqueduct # recompile aqueduct snapshot with current SDK
```

Enjoy! If this fixes it for drexel, I guess issue can be closed.

**Comment by drexel-ue** [comment]
@daniel-v thanks for the ping. i'll give this a shot now and yeah, see if it can be closed!

**Comment by drexel-ue** [comment]
Things seem to be working!

So steps followed:

1. `pub global deactivate aqueduct`
2. `brew upgrade dart`
3. `pub global activate aqueduct`
4. make small model change. (add new nullable `int` column)
5. `aqueduct db generate`
6. `aqueduct db upgrade --connect postgres://pg_user_usernamer:pg_user_password@public_facing_ip:port/database_name`

Looks like keeping things up to date is kinda important 😅
