### ISSUE TITLE
Validate Route Differently based on Http Method

### ISSUE THREAD

**Issue by LaurentiuSimionescu** [stablekernel/aqueduct#786]
I have this code:

router
        .route("/users/[:id]")
        .link(() => HeadersValidator(authServer, tokenType: TokenType.bearer))
        .link(() => UsersValidator(authServer))
        .link(() => UsersController(context, authServer));

How can i validate headers and/or body differently Post, Patch, Put, Get in a nice way ?

**Comment by joeconwaystk** [comment]
This is a question better served in the Slack channel: http://slackaqueductsignup.herokuapp.com/
