### ISSUE TITLE
db generate throws error "Class xxx doesn't declare a primary key property or declares more than one primary key"

### ISSUE THREAD

**Issue by SudhindraAnegondhi** [stablekernel/aqueduct#787]
On `aqueduct db generate`, aqueduct generate throws this error:
`*** Class 'Customer' doesn't declare a primary key property or declares more than one primary key. All 'ManagedObject' subclasses must have a primary key. Usually, this means you want to add '@primaryKey int id;' to Customer, but if you want more control over the type of primary key, declare the property as one of String, DateTime, bool, int, double, Document and add '@Column(primaryKey: true)' above it.`

But the Customer model _**does**_  have a declaration for the primary key (and only once).

This is the model file:

`import 'package:spinback/spinback.dart';
import './account.dart';
import './achAccount.dart';
import './credtCard.dart';
import './portfolio.dart';

class Customer extends ManagedObject< Customer > implements _Customer {
  @override
  void willInsert() {
    createdAt = DateTime.now().toUtc();
  }

  @override
  void willUpdate() {
    updatedAt = DateTime.now().toUtc();
  }
}

class _Customer {
  @primaryKey
  int id;
  @Column(unique: true)
  String email;
  @Column()
  String firstName;
  @Column()
  String lastName;
  @Column()
  String mobilePhone;
  @Column()
  String phone;
  @Column()
  String fax;
  @Column()
  String streetAddress;
  @Column()
  String city;
  @Column()
  String zipCode;
  @Column()
  String state;
  ManagedSet<Account> accounts;
  ManagedSet<AchAccount> achAccounts;
  ManagedSet<CreditCard> creditCards;
  ManagedSet<Portfolio> portfolios;

  DateTime createdAt;
  DateTime updatedAt;
}
`

**Comment by SudhindraAnegondhi** [comment]
@primaryKey - the editor has capitalize 'P'. The source is correct.

**Comment by SudhindraAnegondhi** [comment]
Verified that the behavior is identical on Linux (Ubuntu 18.04 LTS) and Mac(Catalina 10.154 beta)
-- Aqueduct CLI Version: 3.2.1
-- Aqueduct project version: 3.2.1

**Comment by joeconwaystk** [comment]
Use Slack for questions like this: http://slackaqueductsignup.herokuapp.com/. Your issue is that you have `ManagedObject<Customer>` when it needs to be `ManagedObject<_Customer>`.
