### ISSUE TITLE
Cannot set both 'pageDescription' and use 'join' in query

### ISSUE THREAD

**Issue by disburden** [stablekernel/aqueduct#793]
Do I associate an object in the query and I can no longer perform pagination?
I got this error:
Bad state: Invalid query. Cannot set both 'pageDescription' and use 'join' in query

**Comment by disburden** [comment]
Ok,I found the solution.
Just don't use "pageBy"

**Comment by yurii-uvarov** [comment]
Faced the same now, so here is a little tip:
use sortBy, fetchLimit and offset instead of pageBy and you will get the same behavior.
