### ISSUE TITLE
Timed Jobs

### ISSUE THREAD

**Issue by mariogorki94** [stablekernel/aqueduct#794]
I am using the aqueduct framework for the backend of mobile application. I am using multi isolate startup to reduce the load due to using websockets intensively, I`ve created architecture to sync the state of the isolates between each other. But now i am facing another problem. I need timed jobs like once a day send notifications to specific devices. But i dont want this jobs to be for each isolate. I want only once instance of the job running. I would greatly appreciate some help or advice how to achieve this.

**Comment by joeconwaystk** [comment]
Don't use Aqueduct for cron tasks. It's a stateless HTTP web server. Prefer to use your hosting platform's cron jobs, functions, timed triggers, schedulers or whatever they might be named in your platform.

**Comment by juumixx** [comment]
Hi @mariogorki94,
I use `neat_periodic_task` and start a scheduler that just calls a secure path (`/scheduler` in my example) of the aqueduct application in its job. This way I can use the DB managed by aqueduct but it only gets called on a single isolate each time.
```
Future main() async {
  final app = Application<AppChannel>()
    ..options.configurationFilePath = 'config.yaml'
    ..options.port = port;

  await app.start(numberOfInstances: Platform.numberOfProcessors);
  print('Application started on port: ${app.options.port}.');

  final scheduler = await startScheduler();
  print('Scheduler started.');
  await ProcessSignal.sigterm.watch().first;
  print('Sigterm received, stopping scheduler.');
  await scheduler.stop();
  print('Stopping application.');
  await app.stop();
}

Future<void> scheduledTask() async {
  final url = 'http://localhost:$port/scheduler';
  final response = await http.post(url);
  print('Response status: ${response.statusCode}');
  print('Response body: ${response.body}');
}

Future<NeatPeriodicTaskScheduler> startScheduler() async =>
    NeatPeriodicTaskScheduler(
      interval: 10.seconds,
      name: 'hello-world',
      timeout: 5.seconds,
      task: scheduledTask,
      minCycle: 5.seconds,
    )..start();
```

**Comment by juumixx** [comment]
Btw. this currently only works when calling the `bin/main.dart` directly. I have not found a way to inject the scheduler into the aqueduct `Application` yet, so it also works with `aqueduct serve`. I will update you when I've found a way to do that.

**Comment by juumixx** [comment]
A different approach which should always work, even with `aqueduct serve` is to start/stop your scheduler only in your `ApplicationChannel` number one. I think I'll go with this solution now.

```
  @override
  Future prepare() async {
    if (server.identifier == 1) {
      scheduler = SchedulerService(context);
      await scheduler.start();
    }
  }

  @override
  Future close() {
    scheduler?.stop();
    return super.close();
  }
```

**Comment by joeconwaystk** [comment]
You can also do this at the global level with the static method `initializeApplication`: http://aqueduct.io/docs/application/channel/#initialization-callbacks.

**Comment by juumixx** [comment]
Thanks, that was exactly what I was looking for. I just didn't think of searching inside of the ApplicationChannel.

**Comment by joeconwaystk** [comment]
Great! It is admittedly a poor way of providing this service - since Dart doesn't inherit static methods, and therefore this isn't at true override. I think there is an annotation-based approach that'd be easier documented, but this will stay supported for the time being.
