### ISSUE TITLE
dartdocs.org 404

### ISSUE THREAD

**Issue by Urfoex** [stablekernel/aqueduct#808]
[http://www.dartdocs.org/](http://www.dartdocs.org/)
and therefore
[http://www.dartdocs.org/documentation/aqueduct/latest/](http://www.dartdocs.org/documentation/aqueduct/latest/)
doesn't work.

But
[https://pub.dev/documentation/aqueduct/latest/](https://pub.dev/documentation/aqueduct/latest/)
seems to work.

**Comment by brianmpalma-sk** [comment]
Broken links appear to have been temporary. Retested and all 3 links listed above work as expected. The dartdocs.org URLs redirect to their new pub.dev URL.
