### ISSUE TITLE
ManagedObjectController related entities

### ISSUE THREAD

**Issue by hauketoenjes** [stablekernel/aqueduct#818]
Hi, 

I have a question regarding the ManagedObjectController. Imagine the following situation:

`Book: id, author`
`Author: id List<book>`

These are added throught the OR Mapper in a Postgress db. When making a get request on the author, should it print out the books? This is not quite clear in the documentation. If not, is there any way of printing out the books in this case? Or any way of defining what to print?

**Comment by joeconwaystk** [comment]
By default, no, it will not include the books. ManagedObjectController configures and executes a Query object, so the docs for querying apply: http://aqueduct.io/docs/db/advanced_queries/#including-relationships-in-a-fetch-aka-joins. In a ManagedObjectController, you can override methods to configure the query that it configures & executes. 

For questions like these, you'll get answer faster in the Slack group: http://slackaqueductsignup.herokuapp.com/
