### ISSUE TITLE
How to change postgres schema?

### ISSUE THREAD

**Issue by Blackheart8788** [stablekernel/aqueduct#826]
when working with postgres, the use of schemas is a good way to segment data across de db. so far I haven't been able to find a way to make use of schemas, so please if anyone knows a way, share it, it would be greatly appreciated

**Comment by Reductions** [comment]
You could create different users for each schema and create different connections for each schema.

User schema could be set in such a way:
```sql
ALTER USER user_name SET search_path to 'schema'
``

**Comment by Reductions** [comment]
The only problem with having multiple schemas is that you will need to run migrations against each one of them.

**Comment by Blackheart8788** [comment]
Hi guys hope you’re fine and healthy. Thanks for your replies. I believe I will work for the time being without schemas.
