### ISSUE TITLE
Getting started Tutorial URL unavailable

### ISSUE THREAD

**Issue by cmyers78** [stablekernel/aqueduct#828]
http://aqueduct-tutorial.stablekernel.io that is mentioned in the `Getting Started` tutorial fails to load on either Safari or Chrome

**Comment by sashvoncurtis** [comment]
can verify - https://github.com/stablekernel/tour-of-heroes-dart/issues/1

**Comment by joeconwaystk** [comment]
Thanks for calling this to our attention, the cluster has been upgraded and this service should be available. Let me know if it is not!
