### ISSUE TITLE
How to display the result SQL query?

### ISSUE THREAD

**Issue by bambinoua** [stablekernel/aqueduct#829]
Is there any method to see the generate SQL query before its execution?

**Comment by Reductions** [comment]
No. But you could enable logging to 'FINEST' to see them printed in the log.

Consider asking such question in the slack channel.

**Comment by bambinoua** [comment]
> No. 

Why? It is very comfortable to call some method `query.asSql()` to see.

> But you could enable logging to 'FINEST' to see them printed in the log.

How I can do this? I didn't find anything in `aqueduct` docs.

> Consider asking such question in the slack channel.

I tried somehow. They are VERY slow to respond.

**Comment by bambinoua** [comment]
Well, I found how to do this.
