### ISSUE TITLE
How to implement `column1 || column2 || column3 LIKE '%expr%'`

### ISSUE THREAD

**Issue by bambinoua** [stablekernel/aqueduct#830]
I am trying to implement search by multiple columns. There is no any documentation on this so I created a transient column like:
```dart
String get searchBy => '$column1 $column2 $column3';
```
and use it in `where` clause:
```dart
query.where((record) => record.searchby).like('search');
```
I get an error `Invalid property selector. Must reference a single property only`. Should I use `computed` column on server side? But computed columns are supported only from PostgreSql 11.

**Comment by Reductions** [comment]
You could only use properties that are stored in the database for queries.

What you want to do can be done with query predicate:
[](http://aqueduct.io/docs/db/advanced_queries/#fallbacks
)
Consider asking such question in the slack channel.
