### ISSUE TITLE
Is it possilbe to use `where` and `predicate` simultaneously?

### ISSUE THREAD

**Issue by bambinoua** [stablekernel/aqueduct#831]
I need to implement condition like `condition1 AND condition2 OR condition3`. Is it possible in `aqueduct`? The documentation is poor if something more complex than `SELECT * FROM table` is required... :(

**Comment by Reductions** [comment]
It is possible. All `where` clauses and all `predicate` clauses are combined with `AND`. You could use `OR` in the predicate itself.
