### ISSUE TITLE
Related column isn't marked as foreign key

### ISSUE THREAD

**Issue by perfoWorks** [stablekernel/aqueduct#836]
Why related columns are not marked as foreign key in PostgreSQL? All querying works as they should like the column is foreign key but in the table column isn't marked as foreign key. Here is SO question related to it with more details https://stackoverflow.com/questions/61561193/clarification-on-foreign-key-in-aqueduct

**Comment by Reductions** [comment]
For me it adds foreign key constraint. Maybe it is some kind of bug with the GUI you are using to access your database.

**Comment by perfoWorks** [comment]
@joeconwaystk yes i think it is a bug in GUI.. I’m using pgadmin btw...
