### ISSUE TITLE
aqueduct db upgrade: "RangeError: Invalid value: Not in range 0..1114111, inclusive: -1"

### ISSUE THREAD

**Issue by BaptisteOue** [stablekernel/aqueduct#838]
Hello,

First thanks for this amazing framework !
Now I'm posting this issue without really knowing if it's on the flutter / dart / aqueduct side specifically...

The fact is I'm developping and application with Flutter as front-end and I'm using aqueduct to build my backend server. All worked pretty fine until I tried to move on the beta channel of flutter (to test flutter web) and then aqueduct suddenly failed interacting with the database (even if I come back to stable flutter channel).  I'm sorry I can't give any "steps to reproduce" as I don't really know what is causing this error.

I'm not sure if there is any conflicts in the dart' SDKs used by flutter and aqueduct but I thought I could switch from one version of flutter to another without affecting aqueduct. Here is an example of an error I have : 

```
D:\Documents\Dev\backend>aqueduct db upgrade --connect postgres://user:password@localhost:5432/app
-- Aqueduct CLI Version: 3.3.0
-- Aqueduct project version: 3.3.0
*** Uncaught error
    RangeError: Invalid value: Not in range 0..1114111, inclusive: -1
  **** Stacktrace
  * #0      StringBuffer.writeCharCode (dart:core-patch/string_buffer_patch.dart:76:9)
  * #1      PostgreSQLFormat.substitute (package:postgres/src/substituter.dart:83:29)
  * #2      Query.sendExtended (package:postgres/src/query.dart:61:38)
  * #3      _PostgreSQLConnectionStateIdle.processQuery (package:postgres/src/connection_fsm.dart:182:9)
  * #4      _PostgreSQLConnectionStateIdle.awake (package:postgres/src/connection_fsm.dart:168:14)
  * #5      _PostgreSQLExecutionContextMixin._enqueue (package:postgres/src/connection.dart:399:67)
  * #6      _PostgreSQLExecutionContextMixin.query (package:postgres/src/connection.dart:318:12)
  * #7      PostgreSQLPersistentStore.execute (package:aqueduct/src/db/postgresql/postgresql_persistent_store.dart:153:37)
  * <asynchronous suspension>
  * #8      PostgreSQLPersistentStore.schemaVersion (package:aqueduct/src/db/postgresql/postgresql_persistent_store.dart:216:26)
  * #9      CLIDatabaseUpgrade.handle (package:aqueduct/src/cli/commands/db_upgrade.dart:28:52)
  * #10     CLICommand.process (package:aqueduct/src/cli/command.dart:159:20)
  * <asynchronous suspension>
  * #11     CLICommand.process (package:aqueduct/src/cli/command.dart:135:12)
  * #12     CLICommand.process (package:aqueduct/src/cli/command.dart:135:12)
  * #13     main (file:///C:/Users/bapti/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/aqueduct-3.3.0/bin/aqueduct.dart:9:27)
  * #14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
  * #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
  ****`
```

Here are several outputs of my binaries paths (not sure if it's directly related):
```
D:\Documents\Dev\backend>where flutter
C:\flutter\bin\flutter
C:\flutter\bin\flutter.bat

D:\Documents\Dev\backend>where dart
C:\dart-sdk\bin\dart.exe
C:\flutter\bin\cache\dart-sdk\bin\dart.exe

D:\Documents\Dev\backend>where pub
C:\dart-sdk\bin\pub.bat
C:\flutter\bin\cache\dart-sdk\bin\pub.bat

D:\Documents\Dev\backend>where aqueduct
C:\Users\bapti\AppData\Roaming\Pub\Cache\bin\aqueduct.bat
```

Finnaly some outputs that may be usefull :
```
D:\Documents\Dev\backend>dart --version
Dart VM version: 2.8.1 (stable) (Thu Apr 30 09:25:21 2020 +0200) on "windows_x64"

D:\Documents\Dev\backend>flutter --version
Flutter 1.17.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (6 days ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1

D:\Documents\Dev\backend>aqueduct --version
Aqueduct CLI version: 3.3.0
```

Thanks in advance for your help, and I apologize if it's not related to aqueduct directly of if the error is on my side.

**EDIT**
It seems like it's due to dart lastest version (2.8.1) but still why would changing flutter channel impact dart SDK used by aqueduct ? 
Fluter dart SDK is 2.8.1 and I've downgraded "normal" dart SDK to 2.7.2. So aqueduct is supposed to use the lastest but if in my path _C:\flutter\bin\cache\dart-sdk\bin_ is before _C:\dart-sdk\bin_ then aqueduct use flutter's dart SDK (version 2.8.1 so it errors). Is this an expected behavior ?

**Comment by Reductions** [comment]
Yes it is an expected behavior. You usually would want either dart sdk or the one exported by flutter. I would recommend using `asdf vm` as it allows you use multiple version of dart (any supported language actually) at the same time and define the currently use on per project bases.

**Comment by mohmmedmalas** [comment]
I use this command, and that works for me

`pub run aqueduct db upgrade --connect postgres://postgres:123456789@localhost:5432/courses`
