### ISSUE TITLE
no build comamd

### ISSUE THREAD

**Issue by mengrant** [stablekernel/aqueduct#839]
when I run aqueduct build in my project director. ,

aqueduct build                                                                       
-- Aqueduct CLI Version: 3.3.0+1
Aqueduct is a tool for managing Aqueduct applications.

Usage: aqueduct <command> [arguments]

Options:
    --version            Prints version of this tool
    --[no-]color         Toggles ANSI color
                         (defaults to on)
-h, --help               Shows this
    --[no-]stacktrace    Shows the stacktrace if an error occurs
    --[no-]machine       Output is machine-readable, usable for creating tools on top of this CLI. Behavior varies by command.
Available sub-commands:
  document   Generates an OpenAPI specification of an application.
  create     Creates Aqueduct applications from templates.
  serve      Runs Aqueduct applications.
  setup      A one-time setup command for your development environment.
  auth       A tool for adding OAuth 2.0 clients to a database using the managed_auth package.
  db         Modifies, verifies and generates database schemas.

**Comment by joeconwaystk** [comment]
This command got moved to 4.0.0-b1 due to issues in version constraints that were selecting pre-release package instead of the stable release in ^3.0.0. I think `pub global activate aqueduct 4.0.0-b1` and then update your project's pubspec to match.
