### ISSUE TITLE
Problem when migrating an empty database

### ISSUE THREAD

**Issue by chrisnorman7** [stablekernel/aqueduct#841]
Hi,
I've got all the code for my database sorted. `flutter analyze --watch` continues to give me no errors (with the latest analysis file from https://raw.githubusercontent.com/flutter/flutter/master/analysis_options.yaml), but I am getting the following error when running `aqueduct db upgrade`.

I've successfully ran `aqueduct db generate`, and one file has been generated.

I've created by app user with the createdb permission, as directed by [the manual](https://aqueduct.io/docs/tut/executing-queries/).

Any help would be greatly appreciated.

-- Aqueduct CLI Version: 3.3.0+1
-- Aqueduct project version: 3.3.0-b1
*** Uncaught error
    RangeError: Invalid value: Not in range 0..1114111, inclusive: -1
  **** Stacktrace
  * #0      StringBuffer.writeCharCode (dart:core-patch/string_buffer_patch.dart:76:9)
  * #1      PostgreSQLFormat.substitute (package:postgres/src/substituter.dart:83:29)
  * #2      Query.sendExtended (package:postgres/src/query.dart:61:38)
  * #3      _PostgreSQLConnectionStateIdle.processQuery (package:postgres/src/connection_fsm.dart:182:9)
  * #4      _PostgreSQLConnectionStateIdle.awake (package:postgres/src/connection_fsm.dart:168:14)
  * #5      _PostgreSQLExecutionContextMixin._enqueue (package:postgres/src/connection.dart:399:67)
  * #6      _PostgreSQLExecutionContextMixin.query (package:postgres/src/connection.dart:318:12)
  * #7      PostgreSQLPersistentStore.execute (package:aqueduct/src/db/postgresql/postgresql_persistent_store.dart:153:37)
  * <asynchronous suspension>
  * #8      PostgreSQLPersistentStore.schemaVersion (package:aqueduct/src/db/postgresql/postgresql_persistent_store.dart:216:26)
  * #9      CLIDatabaseUpgrade.handle (package:aqueduct/src/cli/commands/db_upgrade.dart:28:52)
  * #10     CLICommand.process (package:aqueduct/src/cli/command.dart:159:20)
  * <asynchronous suspension>
  * #11     CLICommand.process (package:aqueduct/src/cli/command.dart:135:12)
  * #12     CLICommand.process (package:aqueduct/src/cli/command.dart:135:12)
  * #13     main (file:///home/chris/.pub-cache/hosted/pub.dartlang.org/aqueduct-3.3.0+1/bin/aqueduct.dart:9:27)
  * #14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
  * #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
  ****

**Comment by chrisnorman7** [comment]
Should probably have put my versions in here:

* Dart VM version: 2.8.2 (stable) (Unknown timestamp) on "linux_x64"
* Aqueduct CLI version: 3.3.0+1
* psql (PostgreSQL) 12.3

I'm more than happy to provide any other info that is relevant.

**Comment by joeconwaystk** [comment]
Switch to 4.0.0-b1, it depends on an updated postgres driver. Unfortunately, Dart 2.8 had a breaking change that impacted v1 of the postgres driver.

**Comment by chrisnorman7** [comment]
Hi,
Thanks for the quick reply. How do I get that version? I tried putting
aqueduct: '>= 4.0.0-b1'
in my pubspec.yaml file, but I get the error
Resolving dependencies...
Because backstreets depends on aqueduct >=4.0.0-b1 which doesn't match any
versions, version solving failed.

Sorry if I'm making beginner mistakes, but I am a beginner! :)

Take care,

Chris Norman

**Comment by joeconwaystk** [comment]
Strange - I thought 4.0.0 was available on pub, but it is not. A bad release went into pub and it caused all kinds of chaos that we unfortunately have not had the time to resolve yet. You might have to install Dart 2.7 and switch that and Dart 2.8 for Flutter/Aqueduct for the time being.

**Comment by chrisnorman7** [comment]
No problem. I can just wait. Any idea how long it'll take for the good
release to get uploaded?

I'm absolutely loving Aqueduct by the way! it's a wonderful library!

Take care,

Chris Norman

**Comment by tedwong** [comment]
does it means that it is not dart 2.8 ready?

**Comment by devisions** [comment]
@joeconwaystk Thanks for the feedback.
Indeed, a [version 2](https://pub.dev/packages/postgres/versions) (`2.1.1` actually) of `postgres` dependency exists. If that's the only change needed, then it should be quite easy to fix. How can we/I help in this case?

I love the quality of the documentation and the whole experience with this lovely framework, so I really try to help/contribute.

@tedwong Yes, for now. Although this particular issue it's not strictly related to Aqueduct.

**Comment by edufolly** [comment]
If you want to use dart > 2.7.0, you can add to `pubspec.yaml`:
```yaml
dependency_overrides:
  postgres: 2.1.1
```
To use aqueduct to upgrade the database:
`pub run aqueduct db upgrade`

I don't have problems to use aqueduct with recent PostgreSQL plugin.

**Comment by devisions** [comment]
@edufolly Thanks a lot for the help, Eduardo! Indeed, this approach is working just great.
I need to look into the details of `pub` to get the full picture.

**Comment by devisions** [comment]
Today Aqueduct version `4.0.0-b1` has been published on pub.dev.

You can install it using:
```
pub global activate aqueduct 4.0.0-b1
```
And in the project's `pubspec.yaml` you can use it, together with the updated version of `aqueduct_test` as below:
```
...
dependencies:
  aqueduct: ^4.0.0-b1

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^2.0.0-b1
```

And all of these using the recently released Dart SDK 2.8.3. Yay! 😄

**Comment by chrisnorman7** [comment]
Good work, thank you so much!!

Take care,

Chris Norman

**Comment by pst9354** [comment]
After upgrading to 4.0.0-b1, I tried to compile the project with:
dart2native bin\main.dart -k aot

error: import of dart:mirrors is not supported in the current Dart runtime

Failed to generate native files:
Generating AOT snapshot failed!

Did I miss something???

**Comment by devisions** [comment]
@pst9354 You're right, Patrik. The current - `4.0.0-b1` - version still includes `dart:mirrors` in multiple places.

@joeconwaystk I am seriously consider investing time and energy on this wonderful framework and try to contribute. Did you mentioned somewhere the strategy to get rid off the `dart:mirrors` dependency? I guess any alternative would be based on code generation before the final build, so indeed at runtime there won't be any dynamic nature of such reflection.
Not sure right now if an alternative such as [Reflectable](https://pub.dev/packages/reflectable) can be considered.

**Comment by devisions** [comment]
@chrisnorman7 Oh, just for the sake or having things organized, I would close this issue.

@pst9354 I found out the issue where the AOT topic is being "officially" addressed. This is #669 so all of us interested on this topic can talk/watch on it.

**Comment by chrisnorman7** [comment]
Yeah, sorry, I always forget I have to do that. :)
