### ISSUE TITLE
`aqueduct db upgrade` fails when using a String value containing a % sign as default value

### ISSUE THREAD

**Issue by chrisnorman7** [stablekernel/aqueduct#846]
Hi,
I have a model with the following column:

class _GameObject {
  ...
  /// The social which is used when this object connects to the game.
  @Column(defaultValue: '%1N %1has connected.')
  String connectSocial;
}

Running `aqueduct db generate` works fine, but when trying to sync the changes to the database, I get the following error:

-- Aqueduct CLI Version: 3.3.0+1
-- Aqueduct project version: 3.3.0+1
-- Updating to version 3 from version 2...
    Replaying versions: 1, 2...
    PostgreSQL connecting, backstreets_user@localhost:5432/backstreets.
    Applying migration version 3...
        ALTER TABLE game_objects ADD COLUMN connectSocial TEXT NOT NULL DEFAULT %1N %1has connected.
*** There was an issue. Reason: syntax error at or near "%". Table: null Column: null

Is there something I should be doing differently? Or is this something Aqueduct should be handling but isn't?

Cheers in advance.

**Comment by chrisnorman7** [comment]
OK, so upon playing with this a little more, it seems the defaultValue value is being sent to the database, sans quote marks.

After trying replacements for the percent sign, including backslash, $ (which really failed), and finally `, I tried putting quotes around the string:

```
@Column(defaultValue: '"%1N %1has connected."')
```

This really messed things up, causing a problem in the migration file, because it seems they use double quote marks instead of apostrophes, which is fine, except that I'm a stickler for linter rules, and I'm using the ones from Google which tell me to only use double quotes if the string contains single quotes.

So finally, I arrived at a solution: to enclode my single-quoted string in double quotes.

```
@Column(defaultValue: "'%1N %1has connected.'")
```

If this is the right approach, and what I should have been doing all along, I'll close this issue.

Either way, there should probably be something in the manual about this.

Thanks in advance.

**Comment by Reductions** [comment]
You are right this is the right approach:
"""dart
@Column(defaultValue: "'%1N %1has connected.'")
"""
this is so you could set an integer as default e.g: `@Column(defaultValue: "1")`

**Comment by chrisnorman7** [comment]
That's perfect, thank you.

Is it worth mentioning this somewhere in the manual? I may have missed it, but I've been reading the docs quite a lot recently.

If it's something that there's interest for, I'm more than happy to look through the docs and submit a PR with some changes.
