### ISSUE TITLE
File not found after following tutorial https://aqueduct.io/docs/http/serving_files/

### ISSUE THREAD

**Issue by bahadurvaibhav** [stablekernel/aqueduct#852]
After creating project "aqueduct create project_name", I added the below code in channel.dart "get entryPoint"

`router.route("/files/*").link(() => FileController(
      "images/",
      onFileNotFound: (FileController controller, Request req) {
        print('File not found');
      },
    ));`

It's printing "file not found" in console

![image](https://user-images.githubusercontent.com/13390257/83282060-b04bb600-a1f6-11ea-997d-441df6b6d1a9.png)

What I am missing here?

**Comment by devisions** [comment]
I guess you have a _typo_ there: you refer to `images`, but in your file system there is `image`.
