### ISSUE TITLE
How to Get Current URL Full Address

### ISSUE THREAD

**Issue by 5lineofcode** [stablekernel/aqueduct#863]
How to get current url Full Address in GET Request?

  router.route("/").linkFunction((request) async {
    // final page = request.path.variables["page"];
    @Bind.query("page")
    String page;

    print(request.path.toString());
    print(request.connectionInfo.remoteAddress.address);
    print(request.connectionInfo.remoteAddress.host);
    print(request.connectionInfo.remoteAddress.rawAddress);
    print(router.basePath);

    print("PAGE: $page");

    return json(page);
  });

i Want to get http://localhost:8888/
Thanks

**Comment by brianmpalma-sk** [comment]
Each `Request` instance has a [raw](https://pub.dev/documentation/aqueduct/latest/aqueduct/Request/raw.html) property that provides access to the underlying [HttpRequest](https://api.dart.dev/stable/2.8.4/dart-io/HttpRequest-class.html). Access to the full path is done using the [requestedUri](https://api.dart.dev/stable/2.8.4/dart-io/HttpRequest/requestedUri.html) property of the underlying `HttpRequest`.

```
router
  .route("/example")
  .linkFunction((request) async {
    return Response.ok({"requestedUri": "${request.raw.requestedUri}"});
  });
```

This produces the following output: `{"requestedUri":"http://localhost:8888/example"}`

**Comment by 5lineofcode** [comment]
> Each `Request` instance has a [raw](https://pub.dev/documentation/aqueduct/latest/aqueduct/Request/raw.html) property that provides access to the underlying [HttpRequest](https://api.dart.dev/stable/2.8.4/dart-io/HttpRequest-class.html). Access to the full path is done using the [requestedUri](https://api.dart.dev/stable/2.8.4/dart-io/HttpRequest/requestedUri.html) property of the underlying `HttpRequest`.
> 
> ```
> router
>   .route("/example")
>   .linkFunction((request) async {
>     return Response.ok({"requestedUri": "${request.raw.requestedUri}"});
>   });
> ```
> 
> This produces the following output: `{"requestedUri":"http://localhost:8888/example"}`

thanks. solved!
