### ISSUE TITLE
error after upgrade

### ISSUE THREAD

**Issue by DiegoLimeiradaSilva** [stablekernel/aqueduct#865]
after upgrading to aqueduct version 4.0.0-b1, I can only access the server through 127.0.0.1:8888 or localhost: 8888 externally it stopped working ... already I checked firewall and antivirus

**Comment by jken785** [comment]
Did you figure this out? I am running into the same issue. @DiegoLimeiradaSilva

**Comment by DiegoLimeiradaSilva** [comment]
I gave up using it
