### ISSUE TITLE
Query results with fields name

### ISSUE THREAD

**Issue by luX0r-reload** [stablekernel/aqueduct#870]
It's possible to have fields name in executeQuery results? I think it could be very useful.

**Comment by luX0r-reload** [comment]
Nobody? Using ORM it's not a valid solution for complex query and for a professional team with a expert DB architect knowing SQL but no Dart.

**Comment by joeconwaystk** [comment]
This method is more or less just a redirect to the underlying postgresql driver: https://github.com/stablekernel/postgresql-dart. You can use the driver directly and it may have that capability; the repo is a good place to start.

**Comment by luX0r-reload** [comment]
Nice! Thanks for suggest.
