### ISSUE TITLE
RangeError when run aqueduck on ubuntu 20.04 to connect postgresql 12.3

### ISSUE THREAD

**Issue by Logan-lu** [stablekernel/aqueduct#876]
Hi there,

I'm a newbie on aqueduct, and stuck when following up tutorial hero project. Here is the error message:
 
RangeError: Invalid value: Not in range 0..1114111, inclusive: -1 
#0      StringBuffer.writeCharCode (dart:core-patch/string_buffer_patch.dart:76:9)
#1      PostgreSQLFormat.substitute (package:postgres/src/substituter.dart:83:29)
#2      Query.sendExtended (package:postgres/src/query.dart:61:38)
#3      _PostgreSQLConnectionStateIdle.processQuery (package:postgres/src/connection_fsm.dart:182:9)
#4      _PostgreSQLConnectionStateIdle.awake (package:postgres/src/connection_fsm.dart:168:14)
#5      _PostgreSQLExecutionContextMixin._enqueue (package:postgres/src/connection.dart:399:67)
#6      _PostgreSQLExecutionContextMixin.query (package:postgres/src/connection.dart:318:12)
#7      PostgreSQLPersistentStore.executeQuery (package:aqueduct/src/db/postgresql/postgresql_persistent_store.dart:297:38)
<asynchronous suspension>
#8      PostgresQuery._fetch (package:aqueduct/src/db/postgresql/postgresql_query.dart:184:10)
#9      PostgresQuery.fetch (package:aqueduct/src/db/postgresql/postgresql_query.dart:140:12)
#10     HeroesController.getAllHeroes (package:heroes/controller/heroes_controller.dart:13:36)
#11     _InstanceMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:339:37)
#12     _InstanceMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:335:25)
#13     BoundOperation.invoke (package:aqueduct/src/http/resource_controller_internal/controller.dart:24:10)
#14     ResourceController._process (package:aqueduct/src/http/resource_controller.dart:371:36)
<asynchronous suspension>
#15     ResourceController.handle (package:aqueduct/src/http/resource_controller.dart:138:14)
<asynchronous suspension>
#16     Controller.receive (package:aqueduct/src/http/controller.dart:174:30)
#17     _ControllerRecycler.receive (package:aqueduct/src/http/controller.dart:402:17)
#18     Controller.receive (package:aqueduct/src/http/controller.dart:206:28)
<asynchronous suspension>
#19     Router.receive (package:aqueduct/src/http/router.dart:139:18)
#20     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#23     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:134:11)
#24     _MapStream._handleData (dart:async/stream_pipe.dart:234:10)
#25     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166:13)
#26     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#29     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#30     _StreamController._add (dart:async/stream_controller.dart:655:7)
#31     _StreamController.add (dart:async/stream_controller.dart:597:5)
#32     _HttpServer._handleRequest (dart:_http/http_impl.dart:2837:19)
#33     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2596:19)
#34     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#37     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#38     _StreamController._add (dart:async/stream_controller.dart:655:7)
#39     _StreamController.add (dart:async/stream_controller.dart:597:5)
#40     _HttpParser._headersEnd (dart:_http/http_parser.dart:399:19)
#41     _HttpParser._doParse (dart:_http/http_parser.dart:739:15)
#42     _HttpParser._parse (dart:_http/http_parser.dart:328:7)
#43     _HttpParser._onData (dart:_http/http_parser.dart:850:5)
#44     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#45     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#46     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#47     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#48     _StreamController._add (dart:async/stream_controller.dart:655:7)
#49     _StreamController.add (dart:async/stream_controller.dart:597:5)
#50     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)
#51     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#54     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#55     _StreamController._add (dart:async/stream_controller.dart:655:7)
#56     _StreamController.add (dart:async/stream_controller.dart:597:5)
#57     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1527:33)
#58     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1019:14)
#59     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#60     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#61     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#62     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

It seems there are some invalid characters, but I'm sure I didn't type any string literal.
The error message occur when I ran "aqueduct db upgrade". 
After that, I try to create the table manually, and try to do query, the same error stacktrace was shown.

My enviornment: Ubuntu 20.04, PostgreSQL 12.3,  dart 2.8.4 stable, aqueduct CLI Version: 3.3.0+1

Any help, appreciate!

**Comment by Reductions** [comment]
Oh only if there was another issue about that! Oh wait:
https://github.com/stablekernel/aqueduct/issues/869
https://github.com/stablekernel/aqueduct/issues/844

**Comment by Logan-lu** [comment]
Sure, thanks
