### ISSUE TITLE
Any way to get a Schema from PostgreSQLPersistentStore

### ISSUE THREAD

**Issue by unlimitedcoder2** [stablekernel/aqueduct#878]
Is there any way to generate a Schema object from my PostgreSQLPersistentStore?

**Comment by joeconwaystk** [comment]
A `ManagedContext` is a container for a persistent store and a data model. The persistent store is a connection between the ORM and the database. The data model is the definition of managed objects and their entities - this translates to a schema and can be done via [one of its constructors](https://pub.dev/documentation/aqueduct/latest/aqueduct/Schema/Schema.fromDataModel.html).

**Comment by unlimitedcoder2** [comment]
![image](https://user-images.githubusercontent.com/16884313/88594168-a7415e80-d058-11ea-8fc7-9b36f94e9bb7.png)
![image](https://user-images.githubusercontent.com/16884313/88594190-b2948a00-d058-11ea-9b8d-cc7e17bb2f32.png)
That does not seem to be working. Any ideas why?

**Comment by Reductions** [comment]
It works.
You have your difference printed. -> []

**Comment by unlimitedcoder2** [comment]
![image](https://user-images.githubusercontent.com/16884313/88647909-6714c700-d0be-11ea-90ae-076d1b46ae9a.png)
![image](https://user-images.githubusercontent.com/16884313/88647962-7267f280-d0be-11ea-9c77-4d9e0f1819f0.png)
There should be a difference though, my database has no tables and my datamodel has 2

**Comment by joeconwaystk** [comment]
The code you have is not comparing the data model in your database to a data model you have defined in code. It actually compares the data model you have in code to the data model you have in code - you're taking the difference of the same object. There is no way to query a live database to understand if all of its table match the schema you have defined in code. Instead, aqueduct uses a hidden version table in your database and your migration files to reconstruct the schema and then look for differences between that schema and your codebase.
