### ISSUE TITLE
Using 4.0.0-b1 can't get access from my local IP. 

### ISSUE THREAD

**Issue by tedwong** [stablekernel/aqueduct#889]
I access my server via 192.168.x.x using 3.x.x . 
But after upgraded to the 4.0.0-b1, it can't access anymore, double checked the firewall is open related port. Thanks.

**Comment by Reductions** [comment]
1. Can you check which socket has the server bound.
2. What happens exactly? Do you get response when you make a request? Does the sever log anything?

**Comment by tedwong** [comment]
Solved by launching the server using `aqueduct serve -a 0.0.0.0`
