### ISSUE TITLE
Getting Socket exception after restarting the aqueduct app

### ISSUE THREAD

**Issue by 91priyansh** [stablekernel/aqueduct#944]
Exited (1)
Unhandled exception:
SocketException: Failed to create server socket (OS Error: Only one usage of each socket address (protocol/network address/port) is normally permitted.

, errno = 10048), address = 0.0.0.0, port = 8888
[38;5;244m#0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:821:7)[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;244m#1      _RawServerSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart)[39;49m
[38;5;244m<asynchronous suspension>[39;49m

Exited (255)

**Comment by Reductions** [comment]
I think that the previous dart process didn't close and is keeping the socket busy.

**Comment by 91priyansh** [comment]
i am running app in debug mode using vs code and i also close the debug session still getting the same error

**Comment by jairoFernandez** [comment]
kill the process for this port friend

**Comment by 91priyansh** [comment]
@jairoFernandez yaa found the solution
