### ISSUE TITLE
How to install aqueduct on macOS?

### ISSUE THREAD

**Issue by NTMS2017** [stablekernel/aqueduct#946]
Hi,

I have install flutter stable version as shown below. But when try to install aqueduct using "pub global activate aqueduct" command I got error as shown below.

How to install aqueduct on macOS big sur?

**My Dart Version in flutter package is:**
```
myname@ myname-MBP ~ % dart --version
Dart SDK version: 2.10.5 (stable) (Tue Jan 19 13:05:37 2021 +0100) on "macos_x64"
```

**Error:**
```
myname@ myname-MBP ~ % pub global activate aqueduct
zsh: command not found: pub
```

**Flutter doctor -v**
```
myname@myname-MBP ~ % flutter doctor -v
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2 20D64 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/*******/flutter
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

```

**Comment by jairoFernandez** [comment]
hey friend, I created a tool for helping https://github.com/jairoFernandez/commons, 
1. Clone https://github.com/jairoFernandez/commons
2. Inside the commons, execute `./install.sh`
3. Execute `fd_console dart_sdk 2.7.0` and `fd_console set_dart_sdk 2.7.0`
4. Test pub and dart commands

**Comment by jairoFernandez** [comment]
Inside the aqueduct project please execute `fd_console project setup`, for more options for ypur aqueduct project `fd_console project`

**Comment by NTMS2017** [comment]
Thanks, but I found out after looking your github project. 

First I create a path (/user/****/.pub-cache/bin) for flutter dart. 

So every time I update stable version my path always see the dart path. 

Than I use “dart pub global activate aqueduct” to get aqueduct. 

Now its working perfectly. Thanks

**Comment by jairoFernandez** [comment]
Super, please close the issue 🙏
