### ISSUE TITLE
How to I change aqueduct serve default port?

### ISSUE THREAD

**Issue by NTMS2017** [stablekernel/aqueduct#947]
How to I change aqueduct serve default port without running "aqueduct serve --port 8889"?

Can I change or configure  port to 8889 and just run "aqueduct serve"?

Does plugin has and configuration to change following or should I have to do manually?

In src/cli/commands has defaultsTo:8888
In src/application has int port = 8888;
and In src/cli/scripts has final baseUri = document.servers?.first?.url ?? Uri.parse("http://localhost:8888");

**Comment by jairoFernandez** [comment]
maybe in `bin/main.dart` in your project

**Comment by NTMS2017** [comment]
Thanks, but didnt work. I need to run 2 aqueduct server side by side for 6 months. After migrarion I will delete/shut second one.

**Comment by jairoFernandez** [comment]
> Thanks, but didnt work. I need to run 2 aqueduct server side by side for 6 months. After migrarion I will delete/shut second one. 

Are you talking about the scalling? 🧐

**Comment by cmalbuquerque** [comment]
There are 2 ways to change server configs:

1. Using flags, if you want to **change the port** you need to run `aqueduct serve --port 8889`
2. Edit configs in `bin/main.dart` file

If you edit this file, you **cannot run** 'aqueduct serve' command, you need to run your server through the Dart file doing `dart bin/main.dart`.

PS: I think you can now close this issue 😁

**Comment by NTMS2017** [comment]
Thanks @cmalbuquerque yes I did use aqueduct serve --port 8889 and now I run 2 aqueduct side by side. Thank you.
