### ISSUE TITLE
How can I create a push notification with aqueduct?

### ISSUE THREAD

**Issue by NTMS2017** [stablekernel/aqueduct#948]
I run my aqueduct server in my work. While my server is running, is it possible to send notification to flutter app?

To me to expensive to buy push notification. First I have only less than 10000 user for my product. My app has country restricon and only can download from cypriot app store or google play. Every morninh I need to send a notification to user for special offers. 

So, I am thinking to build a push notification using aqueduct. My problem is; first I dont know any knowledge about push botification and secondly I dont see any aqueduct example for this.

How can I create a push notification with aqueduct?

**Comment by ayazemre** [comment]
It is a bit long but not that hard. Push notifications with flutter you need to implement some basic Android and IOS code. Firebase provides that for "free". You will need to use specific functions which are not free after some extend. You can use Aqueduct with Firebase and implement your own functions which costs nothing.

https://medium.com/@SebastianEngel/easy-push-notifications-with-flutter-and-firebase-cloud-messaging-d96084f5954f 

this is the basics of push notifications.

https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages 

this is the REST API docs of firebase. You can interact with it using Aqueduct and POSTing requests through with custom logic. 

I do not know your case's details so I can help this much.

**Comment by NTMS2017** [comment]
thanks @ayazthemre
