### ISSUE TITLE
Dart 2.12 and new features

### ISSUE THREAD

**Issue by EhsanAramide** [stablekernel/aqueduct#953]
### Dart 2.12 update
Do you have any plans about new update of dart?
the framework will update too , or not?

**Comment by j4qfrost** [comment]
Copy of this https://github.com/stablekernel/aqueduct/issues/917

**Comment by EhsanAramide** [comment]
> Copy of this #917

thank 
I saw that before but it was for months ago and I just wanted to notice that the last commit was for 31 Aug in 2020 because I want to use the Aqueduct on the medium project (or not exactly large project in production) and these stuffs worried me about updates and new features.
thank the team and we hope new updates, changes and new features and keep the framework upgrade with better usage.

**Comment by EhsanAramide** [comment]
I have dart 2.12.0 which is stable and support sound and unsound null safety.
When I run ```aqueduct serve``` I get an error which it says the script don't use null-safety because of this I get error and I can't do anything like migration and other commands did team have any solution for this kind of error?
